// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"context"
	"encoding/json"
)

// AdminConversationsArchiveResponse Schema for successful response of admin.conversations.archive
type AdminConversationsArchiveResponse struct {
	Ok DefsOkTrue `json:"ok"`
}

func (value *AdminConversationsArchiveResponse) UnmarshalJSON(data []byte) error {
	type AdminConversationsArchiveResponseAlias AdminConversationsArchiveResponse
	var decoded AdminConversationsArchiveResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = AdminConversationsArchiveResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewAdminConversationsArchiveResponse returns a validated AdminConversationsArchiveResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAdminConversationsArchiveResponse(fields AdminConversationsArchiveResponse) (*AdminConversationsArchiveResponse, error) {
	return ConstructModel(fields)
}

// AdminConversationsConvertToPrivateResponse Schema for successful response of admin.conversations.convertToPrivate
type AdminConversationsConvertToPrivateResponse struct {
	Ok DefsOkTrue `json:"ok"`
}

func (value *AdminConversationsConvertToPrivateResponse) UnmarshalJSON(data []byte) error {
	type AdminConversationsConvertToPrivateResponseAlias AdminConversationsConvertToPrivateResponse
	var decoded AdminConversationsConvertToPrivateResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = AdminConversationsConvertToPrivateResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewAdminConversationsConvertToPrivateResponse returns a validated AdminConversationsConvertToPrivateResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAdminConversationsConvertToPrivateResponse(fields AdminConversationsConvertToPrivateResponse) (*AdminConversationsConvertToPrivateResponse, error) {
	return ConstructModel(fields)
}

// AdminConversationsCreateResponse Schema for successful response of admin.conversations.create
type AdminConversationsCreateResponse struct {
	ChannelId *string    `json:"channel_id,omitempty"`
	Ok        DefsOkTrue `json:"ok"`
}

func (value *AdminConversationsCreateResponse) UnmarshalJSON(data []byte) error {
	type AdminConversationsCreateResponseAlias AdminConversationsCreateResponse
	var decoded AdminConversationsCreateResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = AdminConversationsCreateResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok"}); err != nil {
		return err
	}
	if value.ChannelId != nil {
		if err := ValidatePattern("channel_id", *value.ChannelId, "^[C][A-Z0-9]{2,}$"); err != nil {
			return err
		}
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewAdminConversationsCreateResponse returns a validated AdminConversationsCreateResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAdminConversationsCreateResponse(fields AdminConversationsCreateResponse) (*AdminConversationsCreateResponse, error) {
	return ConstructModel(fields)
}

// AdminConversationsDeleteResponse Schema for successful response of admin.conversations.delete
type AdminConversationsDeleteResponse struct {
	Ok DefsOkTrue `json:"ok"`
}

func (value *AdminConversationsDeleteResponse) UnmarshalJSON(data []byte) error {
	type AdminConversationsDeleteResponseAlias AdminConversationsDeleteResponse
	var decoded AdminConversationsDeleteResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = AdminConversationsDeleteResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewAdminConversationsDeleteResponse returns a validated AdminConversationsDeleteResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAdminConversationsDeleteResponse(fields AdminConversationsDeleteResponse) (*AdminConversationsDeleteResponse, error) {
	return ConstructModel(fields)
}

// AdminConversationsDisconnectSharedResponse Schema for successful response of admin.conversations.disconnectShared
type AdminConversationsDisconnectSharedResponse struct {
	Ok DefsOkTrue `json:"ok"`
}

func (value *AdminConversationsDisconnectSharedResponse) UnmarshalJSON(data []byte) error {
	type AdminConversationsDisconnectSharedResponseAlias AdminConversationsDisconnectSharedResponse
	var decoded AdminConversationsDisconnectSharedResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = AdminConversationsDisconnectSharedResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewAdminConversationsDisconnectSharedResponse returns a validated AdminConversationsDisconnectSharedResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAdminConversationsDisconnectSharedResponse(fields AdminConversationsDisconnectSharedResponse) (*AdminConversationsDisconnectSharedResponse, error) {
	return ConstructModel(fields)
}

// AdminConversationsGetConversationPrefsResponse Schema for successful response of admin.conversations.getConversationPrefs
type AdminConversationsGetConversationPrefsResponse struct {
	Ok    DefsOkTrue                                           `json:"ok"`
	Prefs *AdminConversationsGetConversationPrefsResponsePrefs `json:"prefs,omitempty"`
}

func (value *AdminConversationsGetConversationPrefsResponse) UnmarshalJSON(data []byte) error {
	type AdminConversationsGetConversationPrefsResponseAlias AdminConversationsGetConversationPrefsResponse
	var decoded AdminConversationsGetConversationPrefsResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = AdminConversationsGetConversationPrefsResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewAdminConversationsGetConversationPrefsResponse returns a validated AdminConversationsGetConversationPrefsResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAdminConversationsGetConversationPrefsResponse(fields AdminConversationsGetConversationPrefsResponse) (*AdminConversationsGetConversationPrefsResponse, error) {
	return ConstructModel(fields)
}

type AdminConversationsGetConversationPrefsResponsePrefs struct {
	CanThread  *AdminConversationsGetConversationPrefsResponsePrefsCanThread  `json:"can_thread,omitempty"`
	WhoCanPost *AdminConversationsGetConversationPrefsResponsePrefsWhoCanPost `json:"who_can_post,omitempty"`
}

// NewAdminConversationsGetConversationPrefsResponsePrefs returns a validated AdminConversationsGetConversationPrefsResponsePrefs built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAdminConversationsGetConversationPrefsResponsePrefs(fields AdminConversationsGetConversationPrefsResponsePrefs) (*AdminConversationsGetConversationPrefsResponsePrefs, error) {
	return ConstructModel(fields)
}

type AdminConversationsGetConversationPrefsResponsePrefsCanThread struct {
	Type []string `json:"type,omitempty"`
	User []string `json:"user,omitempty"`
}

// NewAdminConversationsGetConversationPrefsResponsePrefsCanThread returns a validated AdminConversationsGetConversationPrefsResponsePrefsCanThread built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAdminConversationsGetConversationPrefsResponsePrefsCanThread(fields AdminConversationsGetConversationPrefsResponsePrefsCanThread) (*AdminConversationsGetConversationPrefsResponsePrefsCanThread, error) {
	return ConstructModel(fields)
}

type AdminConversationsGetConversationPrefsResponsePrefsWhoCanPost struct {
	Type []string `json:"type,omitempty"`
	User []string `json:"user,omitempty"`
}

// NewAdminConversationsGetConversationPrefsResponsePrefsWhoCanPost returns a validated AdminConversationsGetConversationPrefsResponsePrefsWhoCanPost built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAdminConversationsGetConversationPrefsResponsePrefsWhoCanPost(fields AdminConversationsGetConversationPrefsResponsePrefsWhoCanPost) (*AdminConversationsGetConversationPrefsResponsePrefsWhoCanPost, error) {
	return ConstructModel(fields)
}

// AdminConversationsGetTeamsResponse Schema for successful response of admin.conversations.getTeams
type AdminConversationsGetTeamsResponse struct {
	Ok               DefsOkTrue                                          `json:"ok"`
	ResponseMetadata *AdminConversationsGetTeamsResponseResponseMetadata `json:"response_metadata,omitempty"`
	TeamIds          []string                                            `json:"team_ids"`
}

func (value *AdminConversationsGetTeamsResponse) UnmarshalJSON(data []byte) error {
	type AdminConversationsGetTeamsResponseAlias AdminConversationsGetTeamsResponse
	var decoded AdminConversationsGetTeamsResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = AdminConversationsGetTeamsResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok", "team_ids"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewAdminConversationsGetTeamsResponse returns a validated AdminConversationsGetTeamsResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAdminConversationsGetTeamsResponse(fields AdminConversationsGetTeamsResponse) (*AdminConversationsGetTeamsResponse, error) {
	return ConstructModel(fields)
}

type AdminConversationsGetTeamsResponseResponseMetadata struct {
	NextCursor string `json:"next_cursor"`
}

func (value *AdminConversationsGetTeamsResponseResponseMetadata) UnmarshalJSON(data []byte) error {
	type AdminConversationsGetTeamsResponseResponseMetadataAlias AdminConversationsGetTeamsResponseResponseMetadata
	var decoded AdminConversationsGetTeamsResponseResponseMetadataAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = AdminConversationsGetTeamsResponseResponseMetadata(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"next_cursor"}); err != nil {
		return err
	}
	return nil
}

// NewAdminConversationsGetTeamsResponseResponseMetadata returns a validated AdminConversationsGetTeamsResponseResponseMetadata built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAdminConversationsGetTeamsResponseResponseMetadata(fields AdminConversationsGetTeamsResponseResponseMetadata) (*AdminConversationsGetTeamsResponseResponseMetadata, error) {
	return ConstructModel(fields)
}

// AdminConversationsInviteResponse Schema for successful response of admin.conversations.invite
type AdminConversationsInviteResponse struct {
	Ok DefsOkTrue `json:"ok"`
}

func (value *AdminConversationsInviteResponse) UnmarshalJSON(data []byte) error {
	type AdminConversationsInviteResponseAlias AdminConversationsInviteResponse
	var decoded AdminConversationsInviteResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = AdminConversationsInviteResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewAdminConversationsInviteResponse returns a validated AdminConversationsInviteResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAdminConversationsInviteResponse(fields AdminConversationsInviteResponse) (*AdminConversationsInviteResponse, error) {
	return ConstructModel(fields)
}

// AdminConversationsRenameResponse Schema for successful response of admin.conversations.rename
type AdminConversationsRenameResponse struct {
	Ok DefsOkTrue `json:"ok"`
}

func (value *AdminConversationsRenameResponse) UnmarshalJSON(data []byte) error {
	type AdminConversationsRenameResponseAlias AdminConversationsRenameResponse
	var decoded AdminConversationsRenameResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = AdminConversationsRenameResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewAdminConversationsRenameResponse returns a validated AdminConversationsRenameResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAdminConversationsRenameResponse(fields AdminConversationsRenameResponse) (*AdminConversationsRenameResponse, error) {
	return ConstructModel(fields)
}

// AdminConversationsSearchResponse Schema for successful response of admin.conversations.search
type AdminConversationsSearchResponse struct {
	Channels   []ObjsChannel `json:"channels"`
	NextCursor string        `json:"next_cursor"`
}

func (value *AdminConversationsSearchResponse) UnmarshalJSON(data []byte) error {
	type AdminConversationsSearchResponseAlias AdminConversationsSearchResponse
	var decoded AdminConversationsSearchResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = AdminConversationsSearchResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"channels", "next_cursor"}); err != nil {
		return err
	}
	return nil
}

// NewAdminConversationsSearchResponse returns a validated AdminConversationsSearchResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAdminConversationsSearchResponse(fields AdminConversationsSearchResponse) (*AdminConversationsSearchResponse, error) {
	return ConstructModel(fields)
}

// AdminConversationsSetConversationPrefsResponse Schema for successful response of admin.conversations.setConversationPrefs
type AdminConversationsSetConversationPrefsResponse struct {
	Ok DefsOkTrue `json:"ok"`
}

func (value *AdminConversationsSetConversationPrefsResponse) UnmarshalJSON(data []byte) error {
	type AdminConversationsSetConversationPrefsResponseAlias AdminConversationsSetConversationPrefsResponse
	var decoded AdminConversationsSetConversationPrefsResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = AdminConversationsSetConversationPrefsResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewAdminConversationsSetConversationPrefsResponse returns a validated AdminConversationsSetConversationPrefsResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAdminConversationsSetConversationPrefsResponse(fields AdminConversationsSetConversationPrefsResponse) (*AdminConversationsSetConversationPrefsResponse, error) {
	return ConstructModel(fields)
}

// AdminConversationsUnarchiveResponse Schema for successful response of admin.conversations.unarchive
type AdminConversationsUnarchiveResponse struct {
	Ok DefsOkTrue `json:"ok"`
}

func (value *AdminConversationsUnarchiveResponse) UnmarshalJSON(data []byte) error {
	type AdminConversationsUnarchiveResponseAlias AdminConversationsUnarchiveResponse
	var decoded AdminConversationsUnarchiveResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = AdminConversationsUnarchiveResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewAdminConversationsUnarchiveResponse returns a validated AdminConversationsUnarchiveResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAdminConversationsUnarchiveResponse(fields AdminConversationsUnarchiveResponse) (*AdminConversationsUnarchiveResponse, error) {
	return ConstructModel(fields)
}

// AdminConversationsArchive archives a public or private channel. Supply `channel_id` in the form body and authenticate with a `token` that has the `admin.conversations:write` scope.
//
// Archive a public or private channel.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.conversations:write`
//	channelId: The channel to archive.
func AdminConversationsArchive(ctx context.Context, clientConfig ClientConfig, token string, channelId string) (*AdminConversationsArchiveResponse, error) {
	resp, err := DoCfg[AdminConversationsArchiveResponse](ctx, &clientConfig, "POST", "/admin.conversations.archive", &RequestOpts{
		Body: map[string]any{
			"channel_id": channelId,
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "AdminConversationsArchive",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// AdminConversationsConvertToPrivate converts a public channel to a private channel. Supply `channel_id` in the form body and authenticate with a `token` that has the `admin.conversations:write` scope.
//
// Convert a public channel to a private channel.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.conversations:write`
//	channelId: The channel to convert to private.
func AdminConversationsConvertToPrivate(ctx context.Context, clientConfig ClientConfig, token string, channelId string) (*AdminConversationsConvertToPrivateResponse, error) {
	resp, err := DoCfg[AdminConversationsConvertToPrivateResponse](ctx, &clientConfig, "POST", "/admin.conversations.convertToPrivate", &RequestOpts{
		Body: map[string]any{
			"channel_id": channelId,
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "AdminConversationsConvertToPrivate",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// AdminConversationsCreate creates a public or private channel-based conversation. Supply `name` and `is_private`, and provide `team_id` unless `org_wide` is true; the response includes the new channel identifier.
//
// Create a public or private channel-based conversation.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.conversations:write`
//	name: Name of the public or private channel to create.
//	isPrivate: When `true`, creates a private channel instead of a public
//	channel
//	description: Description of the public or private channel to create.
//	orgWide: When `true`, the channel will be available org-wide. Note: if the
//	channel is not `org_wide=true`, you must specify a `team_id` for this
//	channel
//	teamId: The workspace to create the channel in. Note: this argument is
//	required unless you set `org_wide=true`.
func AdminConversationsCreate(ctx context.Context, clientConfig ClientConfig, token string, name string, isPrivate bool, description *string, orgWide *bool, teamId *string) (*AdminConversationsCreateResponse, error) {
	resp, err := DoCfg[AdminConversationsCreateResponse](ctx, &clientConfig, "POST", "/admin.conversations.create", &RequestOpts{
		Body: map[string]any{
			"name":        name,
			"is_private":  isPrivate,
			"description": description,
			"org_wide":    orgWide,
			"team_id":     teamId,
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "AdminConversationsCreate",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// AdminConversationsDelete deletes a public or private channel. Supply `channel_id` in the form body and authenticate with a `token` that has the `admin.conversations:write` scope.
//
// Delete a public or private channel.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.conversations:write`
//	channelId: The channel to delete.
func AdminConversationsDelete(ctx context.Context, clientConfig ClientConfig, token string, channelId string) (*AdminConversationsDeleteResponse, error) {
	resp, err := DoCfg[AdminConversationsDeleteResponse](ctx, &clientConfig, "POST", "/admin.conversations.delete", &RequestOpts{
		Body: map[string]any{
			"channel_id": channelId,
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "AdminConversationsDelete",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// AdminConversationsDisconnectShared disconnects a connected channel from one or more workspaces. Supply `channel_id` and optionally use `leaving_team_ids` to identify the workspace to remove; only one workspace identifier can currently be specified.
//
// Disconnect a connected channel from one or more workspaces.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.conversations:write`
//	channelId: The channel to be disconnected from some workspaces.
//	leavingTeamIds: The team to be removed from the channel. Currently only a
//	single team id can be specified.
func AdminConversationsDisconnectShared(ctx context.Context, clientConfig ClientConfig, token string, channelId string, leavingTeamIds *string) (*AdminConversationsDisconnectSharedResponse, error) {
	resp, err := DoCfg[AdminConversationsDisconnectSharedResponse](ctx, &clientConfig, "POST", "/admin.conversations.disconnectShared", &RequestOpts{
		Body: map[string]any{
			"channel_id":       channelId,
			"leaving_team_ids": leavingTeamIds,
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "AdminConversationsDisconnectShared",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// AdminConversationsGetConversationPrefs retrieves posting preferences for a public or private channel. Supply `channel_id` to identify the channel whose thread and posting permissions you want to inspect. The authentication token must include the required administrative read scope.
//
// Get conversation preferences for a public or private channel.
//
// Parameters:
//
//	channelId: The channel to get preferences for.
//	token: Authentication token. Requires scope: `admin.conversations:read`
func AdminConversationsGetConversationPrefs(ctx context.Context, clientConfig ClientConfig, channelId string, token string) (*AdminConversationsGetConversationPrefsResponse, error) {
	resp, err := DoCfg[AdminConversationsGetConversationPrefsResponse](ctx, &clientConfig, "GET", "/admin.conversations.getConversationPrefs", &RequestOpts{
		Query: map[string]any{
			"channel_id": QueryValue{Value: channelId, Style: "form", Explode: true},
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		OperationID: "AdminConversationsGetConversationPrefs",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// AdminConversationsGetTeams lists the workspaces within an Enterprise organization to which a public or private channel is connected. Supply `channel_id` to identify the channel, then use `cursor` to retrieve additional pages. Use `limit` to control the page size.
//
// Get all the workspaces a given public or private channel is connected to within this Enterprise org.
//
// Parameters:
//
//	channelId: The channel to determine connected workspaces within the
//	organization for.
//	token: Authentication token. Requires scope: `admin.conversations:read`
//	cursor: Set `cursor` to `next_cursor` returned by the previous call to list
//	items in the next page
//	limit: The maximum number of items to return. Must be between 1 - 1000 both
//	inclusive.
func AdminConversationsGetTeams(ctx context.Context, clientConfig ClientConfig, channelId string, token string, cursor *string, limit *int64) (*AdminConversationsGetTeamsResponse, error) {
	resp, err := DoCfg[AdminConversationsGetTeamsResponse](ctx, &clientConfig, "GET", "/admin.conversations.getTeams", &RequestOpts{
		Query: map[string]any{
			"channel_id": QueryValue{Value: channelId, Style: "form", Explode: true},
			"cursor":     QueryValue{Value: cursor, Style: "form", Explode: true},
			"limit":      QueryValue{Value: limit, Style: "form", Explode: true},
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		OperationID: "AdminConversationsGetTeams",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// AdminConversationsInvite invites one or more users to a public or private channel. Supply `user_ids` and `channel_id` in the form-encoded request body to identify the invitees and destination. The authenticated user must use a token with the administrative write scope.
//
// Invite a user to a public or private channel.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.conversations:write`
//	userIds: The users to invite.
//	channelId: The channel that the users will be invited to.
func AdminConversationsInvite(ctx context.Context, clientConfig ClientConfig, token string, userIds string, channelId string) (*AdminConversationsInviteResponse, error) {
	resp, err := DoCfg[AdminConversationsInviteResponse](ctx, &clientConfig, "POST", "/admin.conversations.invite", &RequestOpts{
		Body: map[string]any{
			"user_ids":   userIds,
			"channel_id": channelId,
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "AdminConversationsInvite",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}
