// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

// AdminConversationsEkmListOriginalConnectedChannelInfo lists disconnected channels and their original channel IDs for Enterprise Key Management key revocation. Use `channel_ids` or `team_ids` to filter the results, and use `cursor` to retrieve subsequent pages. Set `limit` to control the maximum number of items returned.
//
// List all disconnected channels—i.e., channels that were once connected to other workspaces and then disconnected—and the corresponding original channel IDs for key revocation with EKM.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.conversations:read`
//	channelIds: A comma-separated list of channels to filter to.
//	teamIds: A comma-separated list of the workspaces to which the channels you
//	would like returned belong.
//	limit: The maximum number of items to return. Must be between 1 - 1000 both
//	inclusive.
//	cursor: Set `cursor` to `next_cursor` returned by the previous call to list
//	items in the next page.
func AdminConversationsEkmListOriginalConnectedChannelInfo(ctx context.Context, clientConfig ClientConfig, token string, channelIds *string, teamIds *string, limit *int64, cursor *string) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "GET", "/admin.conversations.ekm.listOriginalConnectedChannelInfo", &RequestOpts{
		Query: map[string]any{
			"token":       QueryValue{Value: token, Style: "form", Explode: true},
			"channel_ids": QueryValue{Value: channelIds, Style: "form", Explode: true},
			"team_ids":    QueryValue{Value: teamIds, Style: "form", Explode: true},
			"limit":       QueryValue{Value: limit, Style: "form", Explode: true},
			"cursor":      QueryValue{Value: cursor, Style: "form", Explode: true},
		},
		OperationID: "AdminConversationsEkmListOriginalConnectedChannelInfo",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}
