// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

// AdminTeamsAdminsList lists administrators for a specified workspace. Provide `team_id` to select the workspace, and use `cursor` and `limit` to control pagination and page size. Authenticate with a token that has the `admin.teams:read` scope.
//
// List all of the admins on a given workspace.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.teams:read`
//	limit: The maximum number of items to return.
//	cursor: Set `cursor` to `next_cursor` returned by the previous call to list
//	items in the next page.
func AdminTeamsAdminsList(ctx context.Context, clientConfig ClientConfig, token string, teamId string, limit *int64, cursor *string) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "GET", "/admin.teams.admins.list", &RequestOpts{
		Query: map[string]any{
			"token":   QueryValue{Value: token, Style: "form", Explode: true},
			"team_id": QueryValue{Value: teamId, Style: "form", Explode: true},
			"limit":   QueryValue{Value: limit, Style: "form", Explode: true},
			"cursor":  QueryValue{Value: cursor, Style: "form", Explode: true},
		},
		OperationID: "AdminTeamsAdminsList",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}
