// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

// AdminUsersAssign adds an Enterprise user to a workspace. Provide `team_id` and `user_id`, and optionally configure guest access with `is_restricted`, `is_ultra_restricted`, and `channel_ids`. Use a token with the `admin.users:write` scope to authorize the assignment.
//
// Add an Enterprise user to a workspace.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.users:write`
//	teamId: The ID (`T1234`) of the workspace.
//	userId: The ID of the user to add to the workspace.
//	isRestricted: True if user should be added to the workspace as a guest.
//	isUltraRestricted: True if user should be added to the workspace as a
//	single-channel guest.
//	channelIds: Comma separated values of channel IDs to add user in the new
//	workspace.
func AdminUsersAssign(ctx context.Context, clientConfig ClientConfig, token string, teamId string, userId string, isRestricted *bool, isUltraRestricted *bool, channelIds *string) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "POST", "/admin.users.assign", &RequestOpts{
		Body: map[string]any{
			"team_id":             teamId,
			"user_id":             userId,
			"is_restricted":       isRestricted,
			"is_ultra_restricted": isUltraRestricted,
			"channel_ids":         channelIds,
		},
		Headers: OperationHeaders(map[string]any{
					"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "AdminUsersAssign",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}

// AdminUsersInvite invites a user to a workspace. Supply `team_id`, `email`, and at least one channel in `channel_ids`, then optionally configure the invite message, guest status, resend behavior, and account expiration. Use a token with the `admin.users:write` scope to authorize the invitation.
//
// Invite a user to a workspace.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.users:write`
//	teamId: The ID (`T1234`) of the workspace.
//	email: The email address of the person to invite.
//	channelIds: A comma-separated list of `channel_id`s for this user to join.
//	At least one channel is required.
//	customMessage: An optional message to send to the user in the invite email.
//	realName: Full name of the user.
//	resend: Allow this invite to be resent in the future if a user has not
//	signed up yet. (default: false)
//	isRestricted: Is this user a multi-channel guest user? (default: false)
//	isUltraRestricted: Is this user a single channel guest user? (default:
//	false)
//	guestExpirationTs: Timestamp when guest account should be disabled. Only
//	include this timestamp if you are inviting a guest user and you want their
//	account to expire on a certain date.
func AdminUsersInvite(ctx context.Context, clientConfig ClientConfig, token string, teamId string, email string, channelIds string, customMessage *string, realName *string, resend *bool, isRestricted *bool, isUltraRestricted *bool, guestExpirationTs *string) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "POST", "/admin.users.invite", &RequestOpts{
		Body: map[string]any{
			"team_id":             teamId,
			"email":               email,
			"channel_ids":         channelIds,
			"custom_message":      customMessage,
			"real_name":           realName,
			"resend":              resend,
			"is_restricted":       isRestricted,
			"is_ultra_restricted": isUltraRestricted,
			"guest_expiration_ts": guestExpirationTs,
		},
		Headers: OperationHeaders(map[string]any{
					"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "AdminUsersInvite",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}

// AdminUsersList lists users on a workspace. Provide `team_id` to select the workspace, and use `cursor` and `limit` to control cursor-based pagination. Pass the returned `next_cursor` as `cursor` to retrieve the next page.
//
// List users on a workspace
//
// Parameters:
//
//	teamId: The ID (`T1234`) of the workspace.
//	token: Authentication token. Requires scope: `admin.users:read`
//	cursor: Set `cursor` to `next_cursor` returned by the previous call to list
//	items in the next page.
//	limit: Limit for how many users to be retrieved per page
func AdminUsersList(ctx context.Context, clientConfig ClientConfig, teamId string, token string, cursor *string, limit *int64) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "GET", "/admin.users.list", &RequestOpts{
		Query: map[string]any{
			"team_id": QueryValue{Value: teamId, Style: "form", Explode: true},
			"cursor":  QueryValue{Value: cursor, Style: "form", Explode: true},
			"limit":   QueryValue{Value: limit, Style: "form", Explode: true},
		},
		Headers: OperationHeaders(map[string]any{
					"token": token,
		}),
		OperationID: "AdminUsersList",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}

// AdminUsersRemove removes a user from a workspace. Provide the workspace identifier in `team_id` and the user identifier in `user_id` to identify the membership to remove. Authenticate with a token that has the `admin.users:write` scope.
//
// Remove a user from a workspace.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.users:write`
//	teamId: The ID (`T1234`) of the workspace.
//	userId: The ID of the user to remove.
func AdminUsersRemove(ctx context.Context, clientConfig ClientConfig, token string, teamId string, userId string) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "POST", "/admin.users.remove", &RequestOpts{
		Body: map[string]any{
			"team_id": teamId,
			"user_id": userId,
		},
		Headers: OperationHeaders(map[string]any{
					"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "AdminUsersRemove",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}

// AdminUsersSetAdmin promotes an existing guest, regular user, or owner to an admin user in a workspace. Supply `team_id` and `user_id` to identify the workspace and user whose role you want to change. The authenticated user must provide an administrative token with the required write scope.
//
// Set an existing guest, regular user, or owner to be an admin user.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.users:write`
//	teamId: The ID (`T1234`) of the workspace.
//	userId: The ID of the user to designate as an admin.
func AdminUsersSetAdmin(ctx context.Context, clientConfig ClientConfig, token string, teamId string, userId string) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "POST", "/admin.users.setAdmin", &RequestOpts{
		Body: map[string]any{
			"team_id": teamId,
			"user_id": userId,
		},
		Headers: OperationHeaders(map[string]any{
					"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "AdminUsersSetAdmin",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}

// AdminUsersSetExpiration sets an expiration timestamp for a guest user in a workspace. Supply `team_id`, `user_id`, and `expiration_ts` to identify the guest account and the time when it should be disabled. The authenticated user must provide an administrative token with the required write scope.
//
// Set an expiration for a guest user
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.users:write`
//	teamId: The ID (`T1234`) of the workspace.
//	userId: The ID of the user to set an expiration for.
//	expirationTs: Timestamp when guest account should be disabled.
func AdminUsersSetExpiration(ctx context.Context, clientConfig ClientConfig, token string, teamId string, userId string, expirationTs int64) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "POST", "/admin.users.setExpiration", &RequestOpts{
		Body: map[string]any{
			"team_id":       teamId,
			"user_id":       userId,
			"expiration_ts": expirationTs,
		},
		Headers: OperationHeaders(map[string]any{
					"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "AdminUsersSetExpiration",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}

// AdminUsersSetOwner promotes an existing guest, regular user, or admin user to workspace owner. Supply `team_id` and `user_id` to identify the workspace and user whose role you want to change. The authenticated user must provide an administrative token with the required write scope.
//
// Set an existing guest, regular user, or admin user to be a workspace owner.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.users:write`
//	teamId: The ID (`T1234`) of the workspace.
//	userId: Id of the user to promote to owner.
func AdminUsersSetOwner(ctx context.Context, clientConfig ClientConfig, token string, teamId string, userId string) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "POST", "/admin.users.setOwner", &RequestOpts{
		Body: map[string]any{
			"team_id": teamId,
			"user_id": userId,
		},
		Headers: OperationHeaders(map[string]any{
					"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "AdminUsersSetOwner",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}

// AdminUsersSetRegular changes an existing guest, admin, or owner to a regular user in a workspace. Supply `team_id` and `user_id` to identify the workspace and user whose role you want to change. The authenticated user must provide an administrative token with the required write scope.
//
// Set an existing guest user, admin user, or owner to be a regular user.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.users:write`
//	teamId: The ID (`T1234`) of the workspace.
//	userId: The ID of the user to designate as a regular user.
func AdminUsersSetRegular(ctx context.Context, clientConfig ClientConfig, token string, teamId string, userId string) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "POST", "/admin.users.setRegular", &RequestOpts{
		Body: map[string]any{
			"team_id": teamId,
			"user_id": userId,
		},
		Headers: OperationHeaders(map[string]any{
					"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "AdminUsersSetRegular",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}
