// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

// AdminTeamsCreate creates an Enterprise team. Supply `team_domain` and `team_name`, and optionally provide its description and discoverability setting. If provided, `team_discoverability` must be `open`, `closed`, `invite_only`, or `unlisted`.
//
// Create an Enterprise team.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.teams:write`
//	teamDomain: Team domain (for example, slacksoftballteam).
//	teamName: Team name (for example, Slack Softball Team).
//	teamDescription: Description for the team.
//	teamDiscoverability: Who can join the team. A team's discoverability can be
//	`open`, `closed`, `invite_only`, or `unlisted`.
func AdminTeamsCreate(ctx context.Context, clientConfig ClientConfig, token string, teamDomain string, teamName string, teamDescription *string, teamDiscoverability *string) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "POST", "/admin.teams.create", &RequestOpts{
		Body: map[string]any{
			"team_domain":          teamDomain,
			"team_name":            teamName,
			"team_description":     teamDescription,
			"team_discoverability": teamDiscoverability,
		},
		Headers: OperationHeaders(map[string]any{
					"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "AdminTeamsCreate",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}

// AdminTeamsList lists all teams in an Enterprise organization. Use `cursor` to retrieve subsequent pages and `limit` to control the number of teams returned per request. Authenticate with a token that has the `admin.teams:read` scope.
//
// List all teams on an Enterprise organization
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.teams:read`
//	limit: The maximum number of items to return. Must be between 1 - 100 both
//	inclusive.
//	cursor: Set `cursor` to `next_cursor` returned by the previous call to list
//	items in the next page.
func AdminTeamsList(ctx context.Context, clientConfig ClientConfig, token string, limit *int64, cursor *string) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "GET", "/admin.teams.list", &RequestOpts{
		Query: map[string]any{
			"limit":  QueryValue{Value: limit, Style: "form", Explode: true},
			"cursor": QueryValue{Value: cursor, Style: "form", Explode: true},
		},
		Headers: OperationHeaders(map[string]any{
					"token": token,
		}),
		OperationID: "AdminTeamsList",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}
