// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

// AdminEmojiAdd adds a custom emoji to an Enterprise Grid organization. Provide the emoji `name` and an image `url` so the organization can use the new emoji.
//
// Add an emoji.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.teams:write`
//	name: The name of the emoji to be removed. Colons (`:myemoji:`) around the
//	value are not required, although they may be included.
//	url: The URL of a file to use as an image for the emoji. Square images under
//	128KB and with transparent backgrounds work best.
func AdminEmojiAdd(ctx context.Context, clientConfig ClientConfig, token string, name string, url string) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "POST", "/admin.emoji.add", &RequestOpts{
		Body: map[string]any{
			"token": token,
			"name":  name,
			"url":   url,
		},
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "AdminEmojiAdd",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}

// AdminEmojiAddAlias adds an alias for an existing custom emoji. Provide the emoji `name` and the `alias_for` value to associate the alias with its target emoji.
//
// Add an emoji alias.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.teams:write`
//	name: The name of the emoji to be aliased. Colons (`:myemoji:`) around the
//	value are not required, although they may be included.
//	aliasFor: The alias of the emoji.
func AdminEmojiAddAlias(ctx context.Context, clientConfig ClientConfig, token string, name string, aliasFor string) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "POST", "/admin.emoji.addAlias", &RequestOpts{
		Body: map[string]any{
			"token":     token,
			"name":      name,
			"alias_for": aliasFor,
		},
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "AdminEmojiAddAlias",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}

// AdminEmojiList lists custom emoji for an Enterprise Grid organization. Use `cursor` to retrieve subsequent pages and `limit` to control the number of items returned in each page.
//
// List emoji for an Enterprise Grid organization.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.teams:read`
//	cursor: Set `cursor` to `next_cursor` returned by the previous call to list
//	items in the next page
//	limit: The maximum number of items to return. Must be between 1 - 1000 both
//	inclusive.
func AdminEmojiList(ctx context.Context, clientConfig ClientConfig, token string, cursor *string, limit *int64) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "GET", "/admin.emoji.list", &RequestOpts{
		Query: map[string]any{
			"token":  QueryValue{Value: token, Style: "form", Explode: true},
			"cursor": QueryValue{Value: cursor, Style: "form", Explode: true},
			"limit":  QueryValue{Value: limit, Style: "form", Explode: true},
		},
		OperationID: "AdminEmojiList",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}

// AdminEmojiRemove removes a custom emoji across an Enterprise Grid organization. Provide the emoji `name` together with an authentication token that has the required administrative scope.
//
// # Remove an emoji across an Enterprise Grid organization
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.teams:write`
//	name: The name of the emoji to be removed. Colons (`:myemoji:`) around the
//	value are not required, although they may be included.
func AdminEmojiRemove(ctx context.Context, clientConfig ClientConfig, token string, name string) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "POST", "/admin.emoji.remove", &RequestOpts{
		Body: map[string]any{
			"token": token,
			"name":  name,
		},
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "AdminEmojiRemove",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}

// AdminEmojiRename renames a custom emoji in an Enterprise Grid organization. Provide the current emoji `name` and the replacement value in `new_name`.
//
// Rename an emoji.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.teams:write`
//	name: The name of the emoji to be renamed. Colons (`:myemoji:`) around the
//	value are not required, although they may be included.
//	newName: The new name of the emoji.
func AdminEmojiRename(ctx context.Context, clientConfig ClientConfig, token string, name string, newName string) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "POST", "/admin.emoji.rename", &RequestOpts{
		Body: map[string]any{
			"token":    token,
			"name":     name,
			"new_name": newName,
		},
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "AdminEmojiRename",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}
