// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

// AdminUsersSessionInvalidate invalidates one session belonging to a specified user. Supply `team_id` and `session_id` to identify the workspace session you want to invalidate. The authenticated user must provide an administrative token with the required write scope.
//
// Invalidate a single session for a user by session_id
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.users:write`
//	teamId: ID of the team that the session belongs to
func AdminUsersSessionInvalidate(ctx context.Context, clientConfig ClientConfig, token string, teamId string, sessionId int64) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "POST", "/admin.users.session.invalidate", &RequestOpts{
		Body: map[string]any{
			"team_id":    teamId,
			"session_id": sessionId,
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "AdminUsersSessionInvalidate",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}

// AdminUsersSessionReset invalidates all valid sessions for a specified user across all devices. Supply `user_id` and optionally limit invalidation to mobile or web sessions with `mobile_only` or `web_only`. The authenticated user must provide an administrative token with the required write scope.
//
// # Wipes all valid sessions on all devices for a given user
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.users:write`
//	userId: The ID of the user to wipe sessions for
//	mobileOnly: Only expire mobile sessions (default: false)
//	webOnly: Only expire web sessions (default: false)
func AdminUsersSessionReset(ctx context.Context, clientConfig ClientConfig, token string, userId string, mobileOnly *bool, webOnly *bool) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "POST", "/admin.users.session.reset", &RequestOpts{
		Body: map[string]any{
			"user_id":     userId,
			"mobile_only": mobileOnly,
			"web_only":    webOnly,
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "AdminUsersSessionReset",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}
