// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

// AdminInviteRequestsApprove approves a workspace invite request. Supply `invite_request_id` to identify the request, and use `team_id` when you need to specify the workspace where it was made.
//
// Approve a workspace invite request.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.invites:write`
//	inviteRequestId: ID of the request to invite.
//	teamId: ID for the workspace where the invite request was made.
func AdminInviteRequestsApprove(ctx context.Context, clientConfig ClientConfig, token string, inviteRequestId string, teamId *string) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "POST", "/admin.inviteRequests.approve", &RequestOpts{
		Body: map[string]any{
			"invite_request_id": inviteRequestId,
			"team_id":           teamId,
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "AdminInviteRequestsApprove",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}

// AdminInviteRequestsDeny denies a pending workspace invite request. Supply `invite_request_id` to identify the request and optionally provide `team_id` to identify its workspace. Authenticate with a token that has the `admin.invites:write` scope.
//
// Deny a workspace invite request.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.invites:write`
//	inviteRequestId: ID of the request to invite.
//	teamId: ID for the workspace where the invite request was made.
func AdminInviteRequestsDeny(ctx context.Context, clientConfig ClientConfig, token string, inviteRequestId string, teamId *string) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "POST", "/admin.inviteRequests.deny", &RequestOpts{
		Body: map[string]any{
			"invite_request_id": inviteRequestId,
			"team_id":           teamId,
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "AdminInviteRequestsDeny",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}

// AdminInviteRequestsList lists pending workspace invite requests. Use `team_id` to limit results to one workspace, `cursor` to continue from a previous page, and `limit` to control the number of results returned. Authenticate with a token that has the `admin.invites:read` scope.
//
// List all pending workspace invite requests.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.invites:read`
//	teamId: ID for the workspace where the invite requests were made.
//	cursor: Value of the `next_cursor` field sent as part of the previous API
//	response
//	limit: The number of results that will be returned by the API on each
//	invocation. Must be between 1 - 1000, both inclusive
func AdminInviteRequestsList(ctx context.Context, clientConfig ClientConfig, token string, teamId *string, cursor *string, limit *int64) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "GET", "/admin.inviteRequests.list", &RequestOpts{
		Query: map[string]any{
			"team_id": QueryValue{Value: teamId, Style: "form", Explode: true},
			"cursor":  QueryValue{Value: cursor, Style: "form", Explode: true},
			"limit":   QueryValue{Value: limit, Style: "form", Explode: true},
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		OperationID: "AdminInviteRequestsList",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}
