// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

// AdminAppsRestrictedList lists apps restricted from installation for an organization or workspace. Use `limit` to control the page size and pass the returned `next_cursor` in `cursor` to retrieve the next page.
//
// List restricted apps for an org or workspace.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.apps:read`
//	limit: The maximum number of items to return. Must be between 1 - 1000 both
//	inclusive.
//	cursor: Set `cursor` to `next_cursor` returned by the previous call to list
//	items in the next page
func AdminAppsRestrictedList(ctx context.Context, clientConfig ClientConfig, token string, limit *int64, cursor *string, teamId *string, enterpriseId *string) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "GET", "/admin.apps.restricted.list", &RequestOpts{
		Query: map[string]any{
			"token":         QueryValue{Value: token, Style: "form", Explode: true},
			"limit":         QueryValue{Value: limit, Style: "form", Explode: true},
			"cursor":        QueryValue{Value: cursor, Style: "form", Explode: true},
			"team_id":       QueryValue{Value: teamId, Style: "form", Explode: true},
			"enterprise_id": QueryValue{Value: enterpriseId, Style: "form", Explode: true},
		},
		OperationID: "AdminAppsRestrictedList",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}
