// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

// AdminConversationsRename updates the name of a public or private channel. Supply `channel_id` and the new `name` in the form-encoded request body. The authenticated user must use a token with the administrative write scope.
//
// Rename a public or private channel.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.conversations:write`
//	channelId: The channel to rename.
func AdminConversationsRename(ctx context.Context, clientConfig ClientConfig, token string, channelId string, name string) (*AdminConversationsRenameResponse, error) {
	resp, err := DoCfg[AdminConversationsRenameResponse](ctx, &clientConfig, "POST", "/admin.conversations.rename", &RequestOpts{
		Body: map[string]any{
			"channel_id": channelId,
			"name":       name,
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "AdminConversationsRename",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// AdminConversationsSearch searches public and private channels across an Enterprise organization. Use `query`, `team_ids`, and `search_channel_types` to narrow the search, and use `sort` with `sort_dir` to control result ordering. Pass `cursor` from the previous response to retrieve the next page.
//
// Search for public or private channels in an Enterprise organization.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.conversations:read`
//	teamIds: Comma separated string of team IDs, signifying the workspaces to
//	search through.
//	query: Name of the the channel to query by.
//	limit: Maximum number of items to be returned. Must be between 1 - 20 both
//	inclusive. Default is 10.
//	cursor: Set `cursor` to `next_cursor` returned by the previous call to list
//	items in the next page.
//	searchChannelTypes: The type of channel to include or exclude in the search.
//	For example `private` will search private channels, while `private_exclude`
//	will exclude them. For a full list of types, check the Types section.
//	sort: Possible values are `relevant` (search ranking based on what we think
//	is closest), `name` (alphabetical), `member_count` (number of users in the
//	channel), and `created` (date channel was created). You can optionally pair
//	this with the `sort_dir` arg to change how it is sorted
//	sortDir: Sort direction. Possible values are `asc` for ascending order like
//	(1, 2, 3) or (a, b, c), and `desc` for descending order like (3, 2, 1) or
//	(c, b, a)
func AdminConversationsSearch(ctx context.Context, clientConfig ClientConfig, token string, teamIds *string, query *string, limit *int64, cursor *string, searchChannelTypes *string, sort *string, sortDir *string) (*AdminConversationsSearchResponse, error) {
	resp, err := DoCfg[AdminConversationsSearchResponse](ctx, &clientConfig, "GET", "/admin.conversations.search", &RequestOpts{
		Query: map[string]any{
			"team_ids":             QueryValue{Value: teamIds, Style: "form", Explode: true},
			"query":                QueryValue{Value: query, Style: "form", Explode: true},
			"limit":                QueryValue{Value: limit, Style: "form", Explode: true},
			"cursor":               QueryValue{Value: cursor, Style: "form", Explode: true},
			"search_channel_types": QueryValue{Value: searchChannelTypes, Style: "form", Explode: true},
			"sort":                 QueryValue{Value: sort, Style: "form", Explode: true},
			"sort_dir":             QueryValue{Value: sortDir, Style: "form", Explode: true},
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		OperationID: "AdminConversationsSearch",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// AdminConversationsSearchPaginated searches public and private channels across an Enterprise organization. Use `query`, `team_ids`, and `search_channel_types` to narrow the search, and use `sort` with `sort_dir` to control result ordering. Pass `cursor` from the previous response to retrieve the next page.
//
// Search for public or private channels in an Enterprise organization.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.conversations:read`
//	teamIds: Comma separated string of team IDs, signifying the workspaces to
//	search through.
//	query: Name of the the channel to query by.
//	limit: Maximum number of items to be returned. Must be between 1 - 20 both
//	inclusive. Default is 10.
//	cursor: Set `cursor` to `next_cursor` returned by the previous call to list
//	items in the next page.
//	searchChannelTypes: The type of channel to include or exclude in the search.
//	For example `private` will search private channels, while `private_exclude`
//	will exclude them. For a full list of types, check the Types section.
//	sort: Possible values are `relevant` (search ranking based on what we think
//	is closest), `name` (alphabetical), `member_count` (number of users in the
//	channel), and `created` (date channel was created). You can optionally pair
//	this with the `sort_dir` arg to change how it is sorted
//	sortDir: Sort direction. Possible values are `asc` for ascending order like
//	(1, 2, 3) or (a, b, c), and `desc` for descending order like (3, 2, 1) or
//	(c, b, a)
func AdminConversationsSearchPaginated(ctx context.Context, clientConfig ClientConfig, token string, teamIds *string, query *string, limit *int64, cursor *string, searchChannelTypes *string, sort *string, sortDir *string, yield func(*ObjsChannel) bool) error {
	_cursor := cursor
	for {
		_page, err := AdminConversationsSearch(ctx, clientConfig, token, teamIds, query, limit, _cursor, searchChannelTypes, sort, sortDir)
		if err != nil {
			return err
		}
		if _page == nil {
			return nil
		}
		if len(_page.Channels) == 0 {
			return nil
		}
		for i := range _page.Channels {
			if !yield(&_page.Channels[i]) {
				return nil
			}
		}
		_next := _page.NextCursor
		_cursor = &_next
	}
}

type AdminConversationsSearchPage struct {
	Data    *AdminConversationsSearchResponse
	Items   []ObjsChannel
	HasMore bool
}

func AdminConversationsSearchPages(ctx context.Context, clientConfig ClientConfig, token string, teamIds *string, query *string, limit *int64, cursor *string, searchChannelTypes *string, sort *string, sortDir *string, yieldPage func(AdminConversationsSearchPage) bool) error {
	_cursor := cursor
	for {
		_page, err := AdminConversationsSearch(ctx, clientConfig, token, teamIds, query, limit, _cursor, searchChannelTypes, sort, sortDir)
		if err != nil {
			return err
		}
		if _page == nil || len(_page.Channels) == 0 {
			return nil
		}
		_hasMore := true
		if !yieldPage(AdminConversationsSearchPage{Data: _page, Items: _page.Channels, HasMore: _hasMore}) {
			return nil
		}
		if !_hasMore {
			return nil
		}
		_next := _page.NextCursor
		_cursor = &_next
	}
}

// AdminConversationsSetConversationPrefs updates the posting permissions for a public or private channel. Supply `channel_id` and a stringified JSON `prefs` value describing the desired conversation preferences. The authenticated user must use a token with the administrative write scope.
//
// Set the posting permissions for a public or private channel.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.conversations:write`
//	channelId: The channel to set the prefs for
//	prefs: The prefs for this channel in a stringified JSON format.
func AdminConversationsSetConversationPrefs(ctx context.Context, clientConfig ClientConfig, token string, channelId string, prefs string) (*AdminConversationsSetConversationPrefsResponse, error) {
	resp, err := DoCfg[AdminConversationsSetConversationPrefsResponse](ctx, &clientConfig, "POST", "/admin.conversations.setConversationPrefs", &RequestOpts{
		Body: map[string]any{
			"channel_id": channelId,
			"prefs":      prefs,
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "AdminConversationsSetConversationPrefs",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// AdminConversationsSetTeams sets the workspaces connected to a public or private channel in an Enterprise Grid organization. Supply `channel_id`, and use `team_id`, `target_team_ids`, or `org_channel` to control the channel's workspace sharing.
//
// Set the workspaces in an Enterprise grid org that connect to a public or private channel.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.conversations:write`
//	channelId: The encoded `channel_id` to add or remove to workspaces.
//	teamId: The workspace to which the channel belongs. Omit this argument if
//	the channel is a cross-workspace shared channel.
//	targetTeamIds: A comma-separated list of workspaces to which the channel
//	should be shared. Not required if the channel is being shared org-wide.
//	orgChannel: True if channel has to be converted to an org channel
func AdminConversationsSetTeams(ctx context.Context, clientConfig ClientConfig, token string, channelId string, teamId *string, targetTeamIds *string, orgChannel *bool) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "POST", "/admin.conversations.setTeams", &RequestOpts{
		Body: map[string]any{
			"channel_id":      channelId,
			"team_id":         teamId,
			"target_team_ids": targetTeamIds,
			"org_channel":     orgChannel,
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "AdminConversationsSetTeams",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}

// AdminConversationsUnarchive unarchives a public or private channel. Supply the channel identifier in `channel_id` and use an authentication token with the required administrative scope.
//
// Unarchive a public or private channel.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.conversations:write`
//	channelId: The channel to unarchive.
func AdminConversationsUnarchive(ctx context.Context, clientConfig ClientConfig, token string, channelId string) (*AdminConversationsUnarchiveResponse, error) {
	resp, err := DoCfg[AdminConversationsUnarchiveResponse](ctx, &clientConfig, "POST", "/admin.conversations.unarchive", &RequestOpts{
		Body: map[string]any{
			"channel_id": channelId,
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "AdminConversationsUnarchive",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}
