// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

// ApiTest checks whether the API calling code can make a request and optionally returns a supplied test value. Use `error` to request an artificial error response and `foo` to include an example property in the response. This method is useful for validating request handling and response parsing.
//
// Checks API calling code.
//
// Parameters:
//
//	error_: Error response to return
//	foo: example property to return
func ApiTest(ctx context.Context, clientConfig ClientConfig, error_ *string, foo *string) (map[string]map[string]interface{}, error) {
	resp, err := DoCfg[map[string]map[string]interface{}](ctx, &clientConfig, "GET", "/api.test", &RequestOpts{
		Query: map[string]any{
			"error": QueryValue{Value: error_, Style: "form", Explode: true},
			"foo":   QueryValue{Value: foo, Style: "form", Explode: true},
		},
		OperationID: "ApiTest",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}
