// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

// AppsEventAuthorizationsList lists the app installations authorized to receive events for a specified event context. Supply `event_context` to identify the event and use `cursor` and `limit` to page through the available authorizations. The authenticated user must provide a token with the `authorizations:read` scope.
//
// Get a list of authorizations for the given event context. Each authorization represents an app installation that the event is visible to.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `authorizations:read`
func AppsEventAuthorizationsList(ctx context.Context, clientConfig ClientConfig, eventContext string, token string, cursor *string, limit *int64) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "GET", "/apps.event.authorizations.list", &RequestOpts{
		Query: map[string]any{
			"event_context": QueryValue{Value: eventContext, Style: "form", Explode: true},
			"cursor":        QueryValue{Value: cursor, Style: "form", Explode: true},
			"limit":         QueryValue{Value: limit, Style: "form", Explode: true},
		},
		Headers: OperationHeaders(map[string]any{
					"token": token,
		}),
		OperationID: "AppsEventAuthorizationsList",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}
