// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"context"
	"encoding/json"
)

// AppsPermissionsInfoResponse Schema for successful response from apps.permissions.info method
type AppsPermissionsInfoResponse struct {
	Info AppsPermissionsInfoResponseInfo `json:"info"`
	Ok   DefsOkTrue                      `json:"ok"`
}

func (value *AppsPermissionsInfoResponse) UnmarshalJSON(data []byte) error {
	type AppsPermissionsInfoResponseAlias AppsPermissionsInfoResponse
	var decoded AppsPermissionsInfoResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = AppsPermissionsInfoResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok", "info"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewAppsPermissionsInfoResponse returns a validated AppsPermissionsInfoResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAppsPermissionsInfoResponse(fields AppsPermissionsInfoResponse) (*AppsPermissionsInfoResponse, error) {
	return ConstructModel(fields)
}

type AppsPermissionsInfoResponseInfo struct {
	AppHome AppsPermissionsInfoResponseInfoAppHome `json:"app_home"`
	Channel AppsPermissionsInfoResponseInfoChannel `json:"channel"`
	Group   AppsPermissionsInfoResponseInfoGroup   `json:"group"`
	Im      AppsPermissionsInfoResponseInfoIm      `json:"im"`
	Mpim    AppsPermissionsInfoResponseInfoMpim    `json:"mpim"`
	Team    AppsPermissionsInfoResponseInfoTeam    `json:"team"`
}

func (value *AppsPermissionsInfoResponseInfo) UnmarshalJSON(data []byte) error {
	type AppsPermissionsInfoResponseInfoAlias AppsPermissionsInfoResponseInfo
	var decoded AppsPermissionsInfoResponseInfoAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = AppsPermissionsInfoResponseInfo(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"team", "channel", "group", "mpim", "im", "app_home"}); err != nil {
		return err
	}
	return nil
}

// NewAppsPermissionsInfoResponseInfo returns a validated AppsPermissionsInfoResponseInfo built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAppsPermissionsInfoResponseInfo(fields AppsPermissionsInfoResponseInfo) (*AppsPermissionsInfoResponseInfo, error) {
	return ConstructModel(fields)
}

type AppsPermissionsInfoResponseInfoAppHome struct {
	Resources *ObjsResources `json:"resources,omitempty"`
	Scopes    []string       `json:"scopes,omitempty"`
}

// NewAppsPermissionsInfoResponseInfoAppHome returns a validated AppsPermissionsInfoResponseInfoAppHome built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAppsPermissionsInfoResponseInfoAppHome(fields AppsPermissionsInfoResponseInfoAppHome) (*AppsPermissionsInfoResponseInfoAppHome, error) {
	return ConstructModel(fields)
}

type AppsPermissionsInfoResponseInfoChannel struct {
	Resources *ObjsResources `json:"resources,omitempty"`
	Scopes    []string       `json:"scopes,omitempty"`
}

// NewAppsPermissionsInfoResponseInfoChannel returns a validated AppsPermissionsInfoResponseInfoChannel built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAppsPermissionsInfoResponseInfoChannel(fields AppsPermissionsInfoResponseInfoChannel) (*AppsPermissionsInfoResponseInfoChannel, error) {
	return ConstructModel(fields)
}

type AppsPermissionsInfoResponseInfoGroup struct {
	Resources *ObjsResources `json:"resources,omitempty"`
	Scopes    []string       `json:"scopes,omitempty"`
}

// NewAppsPermissionsInfoResponseInfoGroup returns a validated AppsPermissionsInfoResponseInfoGroup built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAppsPermissionsInfoResponseInfoGroup(fields AppsPermissionsInfoResponseInfoGroup) (*AppsPermissionsInfoResponseInfoGroup, error) {
	return ConstructModel(fields)
}

type AppsPermissionsInfoResponseInfoIm struct {
	Resources *ObjsResources `json:"resources,omitempty"`
	Scopes    []string       `json:"scopes,omitempty"`
}

// NewAppsPermissionsInfoResponseInfoIm returns a validated AppsPermissionsInfoResponseInfoIm built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAppsPermissionsInfoResponseInfoIm(fields AppsPermissionsInfoResponseInfoIm) (*AppsPermissionsInfoResponseInfoIm, error) {
	return ConstructModel(fields)
}

type AppsPermissionsInfoResponseInfoMpim struct {
	Resources *ObjsResources `json:"resources,omitempty"`
	Scopes    []string       `json:"scopes,omitempty"`
}

// NewAppsPermissionsInfoResponseInfoMpim returns a validated AppsPermissionsInfoResponseInfoMpim built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAppsPermissionsInfoResponseInfoMpim(fields AppsPermissionsInfoResponseInfoMpim) (*AppsPermissionsInfoResponseInfoMpim, error) {
	return ConstructModel(fields)
}

type AppsPermissionsInfoResponseInfoTeam struct {
	Resources ObjsResources `json:"resources"`
	Scopes    []string      `json:"scopes"`
}

func (value *AppsPermissionsInfoResponseInfoTeam) UnmarshalJSON(data []byte) error {
	type AppsPermissionsInfoResponseInfoTeamAlias AppsPermissionsInfoResponseInfoTeam
	var decoded AppsPermissionsInfoResponseInfoTeamAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = AppsPermissionsInfoResponseInfoTeam(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"scopes", "resources"}); err != nil {
		return err
	}
	return nil
}

// NewAppsPermissionsInfoResponseInfoTeam returns a validated AppsPermissionsInfoResponseInfoTeam built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAppsPermissionsInfoResponseInfoTeam(fields AppsPermissionsInfoResponseInfoTeam) (*AppsPermissionsInfoResponseInfoTeam, error) {
	return ConstructModel(fields)
}

// AppsPermissionsRequestResponse Schema for successful response from apps.permissions.request method
type AppsPermissionsRequestResponse struct {
	Ok DefsOkTrue `json:"ok"`
}

func (value *AppsPermissionsRequestResponse) UnmarshalJSON(data []byte) error {
	type AppsPermissionsRequestResponseAlias AppsPermissionsRequestResponse
	var decoded AppsPermissionsRequestResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = AppsPermissionsRequestResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewAppsPermissionsRequestResponse returns a validated AppsPermissionsRequestResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAppsPermissionsRequestResponse(fields AppsPermissionsRequestResponse) (*AppsPermissionsRequestResponse, error) {
	return ConstructModel(fields)
}

// AppsPermissionsInfo retrieves the permissions that an app has for a workspace. The response organizes permission details for team, channel, group, direct-message, multi-party direct-message, and app-home resources. You can provide a token to identify the authenticated app or user context.
//
// Returns list of permissions this app has on a team.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `none`
func AppsPermissionsInfo(ctx context.Context, clientConfig ClientConfig, token *string) (*AppsPermissionsInfoResponse, error) {
	resp, err := DoCfg[AppsPermissionsInfoResponse](ctx, &clientConfig, "GET", "/apps.permissions.info", &RequestOpts{
		Query: map[string]any{
			"token": QueryValue{Value: token, Style: "form", Explode: true},
		},
		OperationID: "AppsPermissionsInfo",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// AppsPermissionsRequest requests additional permissions for an app using a permissions trigger. Supply the requested scopes and the trigger token to start the permission request flow. The authenticated user must provide a token and a valid `trigger_id` accepted by the permissions API.
//
// # Allows an app to request additional scopes
//
// Parameters:
//
//	token: Authentication token. Requires scope: `none`
//	scopes: A comma separated list of scopes to request for
//	triggerId: Token used to trigger the permissions API
func AppsPermissionsRequest(ctx context.Context, clientConfig ClientConfig, token string, scopes string, triggerId string) (*AppsPermissionsRequestResponse, error) {
	resp, err := DoCfg[AppsPermissionsRequestResponse](ctx, &clientConfig, "GET", "/apps.permissions.request", &RequestOpts{
		Query: map[string]any{
			"token":      QueryValue{Value: token, Style: "form", Explode: true},
			"scopes":     QueryValue{Value: scopes, Style: "form", Explode: true},
			"trigger_id": QueryValue{Value: triggerId, Style: "form", Explode: true},
		},
		OperationID: "AppsPermissionsRequest",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}
