// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

// AppsPermissionsResourcesList lists the resource grants that an app has on a team. Use `cursor` and `limit` to control pagination and the number of resources returned.
//
// Returns list of resource grants this app has on a team.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `none`
//	cursor: Paginate through collections of data by setting the `cursor`
//	parameter to a `next_cursor` attribute returned by a previous request's
//	`response_metadata`. Default value fetches the first "page" of the
//	collection. See pagination for more detail.
//	limit: The maximum number of items to return.
func AppsPermissionsResourcesList(ctx context.Context, clientConfig ClientConfig, token string, cursor *string, limit *int64) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "GET", "/apps.permissions.resources.list", &RequestOpts{
		Query: map[string]any{
			"token":  QueryValue{Value: token, Style: "form", Explode: true},
			"cursor": QueryValue{Value: cursor, Style: "form", Explode: true},
			"limit":  QueryValue{Value: limit, Style: "form", Explode: true},
		},
		OperationID: "AppsPermissionsResourcesList",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}
