// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"context"
	"encoding/json"
)

// AuthRevokeResponse Schema for successful response from auth.revoke method
type AuthRevokeResponse struct {
	Ok      DefsOkTrue `json:"ok"`
	Revoked bool       `json:"revoked"`
}

func (value *AuthRevokeResponse) UnmarshalJSON(data []byte) error {
	type AuthRevokeResponseAlias AuthRevokeResponse
	var decoded AuthRevokeResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = AuthRevokeResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok", "revoked"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewAuthRevokeResponse returns a validated AuthRevokeResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAuthRevokeResponse(fields AuthRevokeResponse) (*AuthRevokeResponse, error) {
	return ConstructModel(fields)
}

// AuthTestResponse Schema for successful response auth.test method
type AuthTestResponse struct {
	BotId               *string    `json:"bot_id,omitempty"`
	IsEnterpriseInstall *bool      `json:"is_enterprise_install,omitempty"`
	Ok                  DefsOkTrue `json:"ok"`
	Team                string     `json:"team"`
	TeamId              string     `json:"team_id"`
	Url                 string     `json:"url"`
	User                string     `json:"user"`
	UserId              string     `json:"user_id"`
}

func (value *AuthTestResponse) UnmarshalJSON(data []byte) error {
	type AuthTestResponseAlias AuthTestResponse
	var decoded AuthTestResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = AuthTestResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok", "url", "team", "user", "team_id", "user_id"}); err != nil {
		return err
	}
	if value.BotId != nil {
		if err := ValidatePattern("bot_id", *value.BotId, "^B[A-Z0-9]{8,}$"); err != nil {
			return err
		}
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	if err := ValidatePattern("team_id", value.TeamId, "^[T][A-Z0-9]{2,}$"); err != nil {
		return err
	}
	if err := ValidatePattern("user_id", value.UserId, "^[UW][A-Z0-9]{2,}$"); err != nil {
		return err
	}
	return nil
}

// NewAuthTestResponse returns a validated AuthTestResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAuthTestResponse(fields AuthTestResponse) (*AuthTestResponse, error) {
	return ConstructModel(fields)
}

// AuthRevoke revokes an authentication token. Use `test` to exercise the revocation flow without actually revoking the specified token.
//
// Revokes a token.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `none`
//	test: Setting this parameter to `1` triggers a _testing mode_ where the
//	specified token will not actually be revoked.
func AuthRevoke(ctx context.Context, clientConfig ClientConfig, token string, test *bool) (*AuthRevokeResponse, error) {
	resp, err := DoCfg[AuthRevokeResponse](ctx, &clientConfig, "GET", "/auth.revoke", &RequestOpts{
		Query: map[string]any{
			"token": QueryValue{Value: token, Style: "form", Explode: true},
			"test":  QueryValue{Value: test, Style: "form", Explode: true},
		},
		OperationID: "AuthRevoke",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// AuthTest verifies the authentication token and retrieves the identity and team associated with it. Use the returned team and user identifiers to confirm which team and user the authenticated user represents.
//
// Checks authentication & identity.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `none`
func AuthTest(ctx context.Context, clientConfig ClientConfig, token string) (*AuthTestResponse, error) {
	resp, err := DoCfg[AuthTestResponse](ctx, &clientConfig, "GET", "/auth.test", &RequestOpts{
		Headers: OperationHeaders(map[string]any{
					"token": token,
		}),
		OperationID: "AuthTest",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}
