// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"context"
	"encoding/json"
)

// BotsInfoResponse Schema for successful response from bots.info method
type BotsInfoResponse struct {
	Bot BotsInfoResponseBot `json:"bot"`
	Ok  DefsOkTrue          `json:"ok"`
}

func (value *BotsInfoResponse) UnmarshalJSON(data []byte) error {
	type BotsInfoResponseAlias BotsInfoResponse
	var decoded BotsInfoResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = BotsInfoResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok", "bot"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewBotsInfoResponse returns a validated BotsInfoResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewBotsInfoResponse(fields BotsInfoResponse) (*BotsInfoResponse, error) {
	return ConstructModel(fields)
}

type BotsInfoResponseBot struct {
	AppId   string                   `json:"app_id"`
	Deleted bool                     `json:"deleted"`
	Icons   BotsInfoResponseBotIcons `json:"icons"`
	Id      string                   `json:"id"`
	Name    string                   `json:"name"`
	Updated int64                    `json:"updated"`
	UserId  *string                  `json:"user_id,omitempty"`
}

func (value *BotsInfoResponseBot) UnmarshalJSON(data []byte) error {
	type BotsInfoResponseBotAlias BotsInfoResponseBot
	var decoded BotsInfoResponseBotAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = BotsInfoResponseBot(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"id", "deleted", "name", "updated", "app_id", "icons"}); err != nil {
		return err
	}
	if err := ValidatePattern("app_id", value.AppId, "^A[A-Z0-9]{1,}$"); err != nil {
		return err
	}
	if err := ValidatePattern("id", value.Id, "^B[A-Z0-9]{8,}$"); err != nil {
		return err
	}
	if value.UserId != nil {
		if err := ValidatePattern("user_id", *value.UserId, "^[UW][A-Z0-9]{2,}$"); err != nil {
			return err
		}
	}
	return nil
}

// NewBotsInfoResponseBot returns a validated BotsInfoResponseBot built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewBotsInfoResponseBot(fields BotsInfoResponseBot) (*BotsInfoResponseBot, error) {
	return ConstructModel(fields)
}

type BotsInfoResponseBotIcons struct {
	Image36 string `json:"image_36"`
	Image48 string `json:"image_48"`
	Image72 string `json:"image_72"`
}

func (value *BotsInfoResponseBotIcons) UnmarshalJSON(data []byte) error {
	type BotsInfoResponseBotIconsAlias BotsInfoResponseBotIcons
	var decoded BotsInfoResponseBotIconsAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = BotsInfoResponseBotIcons(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"image_36", "image_48", "image_72"}); err != nil {
		return err
	}
	if err := ValidateUri("image_36", value.Image36); err != nil {
		return err
	}
	if err := ValidateUri("image_48", value.Image48); err != nil {
		return err
	}
	if err := ValidateUri("image_72", value.Image72); err != nil {
		return err
	}
	return nil
}

// NewBotsInfoResponseBotIcons returns a validated BotsInfoResponseBotIcons built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewBotsInfoResponseBotIcons(fields BotsInfoResponseBotIcons) (*BotsInfoResponseBotIcons, error) {
	return ConstructModel(fields)
}

// BotsInfo retrieves information about a bot user. Omit `bot` to use the applicable default bot context, or provide a bot user identifier to retrieve a specific bot.
//
// Gets information about a bot user.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `users:read`
//	bot: Bot user to get info on
func BotsInfo(ctx context.Context, clientConfig ClientConfig, token string, bot *string) (*BotsInfoResponse, error) {
	resp, err := DoCfg[BotsInfoResponse](ctx, &clientConfig, "GET", "/bots.info", &RequestOpts{
		Query: map[string]any{
			"token": QueryValue{Value: token, Style: "form", Explode: true},
			"bot":   QueryValue{Value: bot, Style: "form", Explode: true},
		},
		OperationID: "BotsInfo",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}
