// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

// CallsAdd creates a registration for a third-party call. Supply a unique `external_unique_id` and a `join_url`, and optionally provide display, timing, creator, and participant details.
//
// Registers a new Call.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `calls:write`
//	externalUniqueId: An ID supplied by the 3rd-party Call provider. It must be
//	unique across all Calls from that service.
//	joinUrl: The URL required for a client to join the Call.
//	externalDisplayId: An optional, human-readable ID supplied by the 3rd-party
//	Call provider. If supplied, this ID will be displayed in the Call object.
//	desktopAppJoinUrl: When supplied, available Slack clients will attempt to
//	directly launch the 3rd-party Call with this URL.
//	dateStart: Call start time in UTC UNIX timestamp format
//	title: The name of the Call.
//	createdBy: The valid Slack user ID of the user who created this Call. When
//	this method is called with a user token, the `created_by` field is optional
//	and defaults to the authed user of the token. Otherwise, the field is
//	required.
//	users: The list of users to register as participants in the Call. Read more
//	on how to specify users here.
func CallsAdd(ctx context.Context, clientConfig ClientConfig, token string, externalUniqueId string, joinUrl string, externalDisplayId *string, desktopAppJoinUrl *string, dateStart *int64, title *string, createdBy *string, users *string) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "POST", "/calls.add", &RequestOpts{
		Body: map[string]any{
			"external_unique_id":   externalUniqueId,
			"join_url":             joinUrl,
			"external_display_id":  externalDisplayId,
			"desktop_app_join_url": desktopAppJoinUrl,
			"date_start":           dateStart,
			"title":                title,
			"created_by":           createdBy,
			"users":                users,
		},
		Headers: OperationHeaders(map[string]any{
					"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "CallsAdd",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}

// CallsEnd ends a registered call and records its final duration when supplied. Use the `id` returned by `calls.add` to identify the call being ended.
//
// Ends a Call.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `calls:write`
//	id: `id` returned when registering the call using the `calls.add` method.
//	duration: Call duration in seconds
func CallsEnd(ctx context.Context, clientConfig ClientConfig, token string, id string, duration *int64) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "POST", "/calls.end", &RequestOpts{
		Body: map[string]any{
			"id":       id,
			"duration": duration,
		},
		Headers: OperationHeaders(map[string]any{
					"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "CallsEnd",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}

// CallsInfo retrieves information about a Call identified by its call ID. Supply `token` with the required calls:read scope and use the `id` returned by calls.add. Use the returned call details to inspect the current Call configuration.
//
// Returns information about a Call.
//
// Parameters:
//
//	id: `id` of the Call returned by the `calls.add` method.
//	token: Authentication token. Requires scope: `calls:read`
func CallsInfo(ctx context.Context, clientConfig ClientConfig, id string, token string) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "GET", "/calls.info", &RequestOpts{
		Query: map[string]any{
			"id": QueryValue{Value: id, Style: "form", Explode: true},
		},
		Headers: OperationHeaders(map[string]any{
					"token": token,
		}),
		OperationID: "CallsInfo",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}

// CallsUpdate updates information about an existing Call. Supply the Call `id` returned by calls.add and provide any Call details you want to change, such as its title or join URLs. Use `join_url` to define the URL that clients use to join the Call.
//
// Updates information about a Call.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `calls:write`
//	id: `id` returned by the `calls.add` method.
//	title: The name of the Call.
//	joinUrl: The URL required for a client to join the Call.
//	desktopAppJoinUrl: When supplied, available Slack clients will attempt to
//	directly launch the 3rd-party Call with this URL.
func CallsUpdate(ctx context.Context, clientConfig ClientConfig, token string, id string, title *string, joinUrl *string, desktopAppJoinUrl *string) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "POST", "/calls.update", &RequestOpts{
		Body: map[string]any{
			"id":                   id,
			"title":                title,
			"join_url":             joinUrl,
			"desktop_app_join_url": desktopAppJoinUrl,
		},
		Headers: OperationHeaders(map[string]any{
					"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "CallsUpdate",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}
