// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

// ChatScheduleMessage schedules a message to be sent to a channel at a future time. Provide `channel` and `post_at`, then use `text`, `blocks`, or `attachments` to define the message content. A successful response includes the scheduled message identifier and scheduled timestamp.
//
// Schedules a message to be sent to a channel.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `chat:write`
//	channel: Channel, private group, or DM channel to send message to. Can be an
//	encoded ID, or a name. See below for more details.
//	text: How this field works and whether it is required depends on other
//	fields you use in your API call. See below for more detail.
//	postAt: Unix EPOCH timestamp of time in future to send the message.
//	parse: Change how messages are treated. Defaults to `none`. See
//	[chat.postMessage](chat.postMessage#formatting).
//	asUser: Pass true to post the message as the authed user, instead of as a
//	bot. Defaults to false. See [chat.postMessage](chat.postMessage#authorship).
//	linkNames: Find and link channel names and usernames.
//	attachments: A JSON-based array of structured attachments, presented as a
//	URL-encoded string.
//	blocks: A JSON-based array of structured blocks, presented as a URL-encoded
//	string.
//	unfurlLinks: Pass true to enable unfurling of primarily text-based content.
//	unfurlMedia: Pass false to disable unfurling of media content.
//	threadTs: Provide another message's `ts` value to make this message a reply.
//	Avoid using a reply's `ts` value; use its parent instead.
//	replyBroadcast: Used in conjunction with `thread_ts` and indicates whether
//	reply should be made visible to everyone in the channel or conversation.
//	Defaults to `false`.
func ChatScheduleMessage(ctx context.Context, clientConfig ClientConfig, token *string, channel *string, text *string, postAt *string, parse *string, asUser *bool, linkNames *bool, attachments *string, blocks *string, unfurlLinks *bool, unfurlMedia *bool, threadTs *float64, replyBroadcast *bool) (*ChatScheduleMessageResponse, error) {
	resp, err := DoCfg[ChatScheduleMessageResponse](ctx, &clientConfig, "POST", "/chat.scheduleMessage", &RequestOpts{
		Body: map[string]any{
			"channel":         channel,
			"text":            text,
			"post_at":         postAt,
			"parse":           parse,
			"as_user":         asUser,
			"link_names":      linkNames,
			"attachments":     attachments,
			"blocks":          blocks,
			"unfurl_links":    unfurlLinks,
			"unfurl_media":    unfurlMedia,
			"thread_ts":       threadTs,
			"reply_broadcast": replyBroadcast,
		},
		Headers: OperationHeaders(map[string]any{
					"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "ChatScheduleMessage",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// ChatUnfurl submits custom unfurl behavior for URLs in a user-posted message. Supply the target `channel` and message `ts`, then provide URL mappings through `unfurls` or authentication guidance through the user-authentication fields. The request requires an authentication token with the `links:write` scope.
//
// Provide custom unfurl behavior for user-posted URLs
//
// Parameters:
//
//	token: Authentication token. Requires scope: `links:write`
//	channel: Channel ID of the message
//	ts: Timestamp of the message to add unfurl behavior to.
//	unfurls: URL-encoded JSON map with keys set to URLs featured in the the
//	message, pointing to their unfurl blocks or message attachments.
//	userAuthMessage: Provide a simply-formatted string to send as an ephemeral
//	message to the user as invitation to authenticate further and enable full
//	unfurling behavior
//	userAuthRequired: Set to `true` or `1` to indicate the user must install
//	your Slack app to trigger unfurls for this domain
//	userAuthUrl: Send users to this custom URL where they will complete
//	authentication in your app to fully trigger unfurling. Value should be
//	properly URL-encoded.
func ChatUnfurl(ctx context.Context, clientConfig ClientConfig, token string, channel string, ts string, unfurls *string, userAuthMessage *string, userAuthRequired *bool, userAuthUrl *string) (*ChatUnfurlResponse, error) {
	resp, err := DoCfg[ChatUnfurlResponse](ctx, &clientConfig, "POST", "/chat.unfurl", &RequestOpts{
		Body: map[string]any{
			"channel":            channel,
			"ts":                 ts,
			"unfurls":            unfurls,
			"user_auth_message":  userAuthMessage,
			"user_auth_required": userAuthRequired,
			"user_auth_url":      userAuthUrl,
		},
		Headers: OperationHeaders(map[string]any{
					"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "ChatUnfurl",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// ChatUpdate updates an existing message in a channel. Supply `channel` and `ts`, then change the message text or provide new `blocks` or `attachments`; omitted content fields retain their existing values unless the request explicitly replaces them. Use `parse` and `link_names` to control message formatting and linking.
//
// Updates a message.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `chat:write`
//	channel: Channel containing the message to be updated.
//	ts: Timestamp of the message to be updated.
//	asUser: Pass true to update the message as the authed user. Bot users in
//	this context are considered authed users.
//	attachments: A JSON-based array of structured attachments, presented as a
//	URL-encoded string. This field is required when not presenting `text`. If
//	you don't include this field, the message's previous `attachments` will be
//	retained. To remove previous `attachments`, include an empty array for this
//	field.
//	blocks: A JSON-based array of structured blocks, presented as a URL-encoded
//	string. If you don't include this field, the message's previous `blocks`
//	will be retained. To remove previous `blocks`, include an empty array for
//	this field.
//	linkNames: Find and link channel names and usernames. Defaults to `none`. If
//	you do not specify a value for this field, the original value set for the
//	message will be overwritten with the default, `none`.
//	parse: Change how messages are treated. Defaults to `client`, unlike
//	`chat.postMessage`. Accepts either `none` or `full`. If you do not specify a
//	value for this field, the original value set for the message will be
//	overwritten with the default, `client`.
//	text: New text for the message, using the default formatting rules. It's not
//	required when presenting `blocks` or `attachments`.
func ChatUpdate(ctx context.Context, clientConfig ClientConfig, token string, channel string, ts string, asUser *string, attachments *string, blocks *string, linkNames *string, parse *string, text *string) (*ChatUpdateResponse, error) {
	resp, err := DoCfg[ChatUpdateResponse](ctx, &clientConfig, "POST", "/chat.update", &RequestOpts{
		Body: map[string]any{
			"channel":     channel,
			"ts":          ts,
			"as_user":     asUser,
			"attachments": attachments,
			"blocks":      blocks,
			"link_names":  linkNames,
			"parse":       parse,
			"text":        text,
		},
		Headers: OperationHeaders(map[string]any{
					"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "ChatUpdate",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}
