// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"context"
	"encoding/json"
)

func (value *ConversationsUnarchiveResponse) UnmarshalJSON(data []byte) error {
	type ConversationsUnarchiveResponseAlias ConversationsUnarchiveResponse
	var decoded ConversationsUnarchiveResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ConversationsUnarchiveResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewConversationsUnarchiveResponse returns a validated ConversationsUnarchiveResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewConversationsUnarchiveResponse(fields ConversationsUnarchiveResponse) (*ConversationsUnarchiveResponse, error) {
	return ConstructModel(fields)
}

// ConversationsArchive archives a conversation so it is no longer active. Provide the conversation `channel` identifier for the conversation you want to archive. The operation returns a success confirmation when the archive is applied.
//
// Archives a conversation.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:write`
//	channel: ID of conversation to archive
func ConversationsArchive(ctx context.Context, clientConfig ClientConfig, token *string, channel *string) (*ConversationsArchiveResponse, error) {
	resp, err := DoCfg[ConversationsArchiveResponse](ctx, &clientConfig, "POST", "/conversations.archive", &RequestOpts{
		Body: map[string]any{
			"channel": channel,
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "ConversationsArchive",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// ConversationsClose closes a direct message or multiperson direct message conversation. Provide the conversation `channel` identifier to close it. The response indicates whether the conversation was already closed or the operation was a no-op.
//
// Closes a direct message or multi-person direct message.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:write`
//	channel: Conversation to close.
func ConversationsClose(ctx context.Context, clientConfig ClientConfig, token *string, channel *string) (*ConversationsCloseResponse, error) {
	resp, err := DoCfg[ConversationsCloseResponse](ctx, &clientConfig, "POST", "/conversations.close", &RequestOpts{
		Body: map[string]any{
			"channel": channel,
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "ConversationsClose",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// ConversationsCreate creates a public or private channel-based conversation. Provide `name` for the channel name and set `is_private` to `true` when the conversation should be private. The response contains the created conversation object.
//
// # Initiates a public or private channel-based conversation
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:write`
//	name: Name of the public or private channel to create
//	isPrivate: Create a private channel instead of a public one
func ConversationsCreate(ctx context.Context, clientConfig ClientConfig, token *string, name *string, isPrivate *bool) (*ConversationsCreateResponse, error) {
	resp, err := DoCfg[ConversationsCreateResponse](ctx, &clientConfig, "POST", "/conversations.create", &RequestOpts{
		Body: map[string]any{
			"name":       name,
			"is_private": isPrivate,
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "ConversationsCreate",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// ConversationsHistory lists messages and events from a conversation's history. Use `latest` and `oldest` to define a time range, `inclusive` to include boundary timestamps, and `cursor` to paginate through results. The response includes messages, pagination state, and channel action metadata.
//
// Fetches a conversation's history of messages and events.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:history`
//	channel: Conversation ID to fetch history for.
//	latest: End of time range of messages to include in results.
//	oldest: Start of time range of messages to include in results.
//	inclusive: Include messages with latest or oldest timestamp in results only
//	when either timestamp is specified.
//	limit: The maximum number of items to return. Fewer than the requested
//	number of items may be returned, even if the end of the users list hasn't
//	been reached.
//	cursor: Paginate through collections of data by setting the `cursor`
//	parameter to a `next_cursor` attribute returned by a previous request's
//	`response_metadata`. Default value fetches the first "page" of the
//	collection. See pagination for more detail.
func ConversationsHistory(ctx context.Context, clientConfig ClientConfig, token *string, channel *string, latest *float64, oldest *float64, inclusive *bool, limit *int64, cursor *string) (*ConversationsHistoryResponse, error) {
	resp, err := DoCfg[ConversationsHistoryResponse](ctx, &clientConfig, "GET", "/conversations.history", &RequestOpts{
		Query: map[string]any{
			"token":     QueryValue{Value: token, Style: "form", Explode: true},
			"channel":   QueryValue{Value: channel, Style: "form", Explode: true},
			"latest":    QueryValue{Value: latest, Style: "form", Explode: true},
			"oldest":    QueryValue{Value: oldest, Style: "form", Explode: true},
			"inclusive": QueryValue{Value: inclusive, Style: "form", Explode: true},
			"limit":     QueryValue{Value: limit, Style: "form", Explode: true},
			"cursor":    QueryValue{Value: cursor, Style: "form", Explode: true},
		},
		OperationID: "ConversationsHistory",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// ConversationsInfo retrieves information about a conversation. Provide the conversation `channel` identifier and optionally request its locale or member count with `include_locale` and `include_num_members`. The response contains the conversation object.
//
// Retrieve information about a conversation.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:read`
//	channel: Conversation ID to learn more about
//	includeLocale: Set this to `true` to receive the locale for this
//	conversation. Defaults to `false`
//	includeNumMembers: Set to `true` to include the member count for the
//	specified conversation. Defaults to `false`
func ConversationsInfo(ctx context.Context, clientConfig ClientConfig, token *string, channel *string, includeLocale *bool, includeNumMembers *bool) (*ConversationsInfoResponse, error) {
	resp, err := DoCfg[ConversationsInfoResponse](ctx, &clientConfig, "GET", "/conversations.info", &RequestOpts{
		Query: map[string]any{
			"token":               QueryValue{Value: token, Style: "form", Explode: true},
			"channel":             QueryValue{Value: channel, Style: "form", Explode: true},
			"include_locale":      QueryValue{Value: includeLocale, Style: "form", Explode: true},
			"include_num_members": QueryValue{Value: includeNumMembers, Style: "form", Explode: true},
		},
		OperationID: "ConversationsInfo",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// ConversationsInvite invites one or more users to a public or private channel. Provide the destination `channel` and a comma-separated `users` list containing the users to invite. The response contains the updated conversation object after the invitation is processed.
//
// Invites users to a channel.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:write`
//	channel: The ID of the public or private channel to invite user(s) to.
//	users: A comma separated list of user IDs. Up to 1000 users may be listed.
func ConversationsInvite(ctx context.Context, clientConfig ClientConfig, token *string, channel *string, users *string) (*ConversationsInviteResponse, error) {
	resp, err := DoCfg[ConversationsInviteResponse](ctx, &clientConfig, "POST", "/conversations.invite", &RequestOpts{
		Body: map[string]any{
			"channel": channel,
			"users":   users,
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "ConversationsInvite",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// ConversationsJoin joins an existing conversation for the authenticated user. Supply the conversation identifier in `channel` and use an authentication token with the `channels:write` scope when authorization is required.
//
// Joins an existing conversation.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `channels:write`
//	channel: ID of conversation to join
func ConversationsJoin(ctx context.Context, clientConfig ClientConfig, token *string, channel *string) (*ConversationsJoinResponse, error) {
	resp, err := DoCfg[ConversationsJoinResponse](ctx, &clientConfig, "POST", "/conversations.join", &RequestOpts{
		Body: map[string]any{
			"channel": channel,
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "ConversationsJoin",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// ConversationsKick removes a user from an existing conversation. Provide the conversation in `channel` and the user to remove in `user`, using an authentication token with the `conversations:write` scope when authorization is required.
//
// Removes a user from a conversation.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:write`
//	channel: ID of conversation to remove user from.
//	user: User ID to be removed.
func ConversationsKick(ctx context.Context, clientConfig ClientConfig, token *string, channel *string, user *string) (*ConversationsKickResponse, error) {
	resp, err := DoCfg[ConversationsKickResponse](ctx, &clientConfig, "POST", "/conversations.kick", &RequestOpts{
		Body: map[string]any{
			"channel": channel,
			"user":    user,
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "ConversationsKick",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// ConversationsLeave leaves an existing conversation for the authenticated user. Supply the conversation identifier in `channel` to specify which conversation to leave, using an authentication token with the `conversations:write` scope when authorization is required.
//
// Leaves a conversation.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:write`
//	channel: Conversation to leave
func ConversationsLeave(ctx context.Context, clientConfig ClientConfig, token *string, channel *string) (*ConversationsLeaveResponse, error) {
	resp, err := DoCfg[ConversationsLeaveResponse](ctx, &clientConfig, "POST", "/conversations.leave", &RequestOpts{
		Body: map[string]any{
			"channel": channel,
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "ConversationsLeave",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// ConversationsList lists conversations in a Slack team, optionally filtering by archive state and conversation type. Use `types` to select public, private, multi-person direct, or direct conversations, and use `cursor` to retrieve subsequent pages.
//
// Lists all channels in a Slack team.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:read`
//	excludeArchived: Set to `true` to exclude archived channels from the list
//	types: Mix and match channel types by providing a comma-separated list of
//	any combination of `public_channel`, `private_channel`, `mpim`, `im`
//	limit: The maximum number of items to return. Fewer than the requested
//	number of items may be returned, even if the end of the list hasn't been
//	reached. Must be an integer no larger than 1000.
//	cursor: Paginate through collections of data by setting the `cursor`
//	parameter to a `next_cursor` attribute returned by a previous request's
//	`response_metadata`. Default value fetches the first "page" of the
//	collection. See pagination for more detail.
func ConversationsList(ctx context.Context, clientConfig ClientConfig, token *string, excludeArchived *bool, types *string, limit *int64, cursor *string) (*ConversationsListResponse, error) {
	resp, err := DoCfg[ConversationsListResponse](ctx, &clientConfig, "GET", "/conversations.list", &RequestOpts{
		Query: map[string]any{
			"token":            QueryValue{Value: token, Style: "form", Explode: true},
			"exclude_archived": QueryValue{Value: excludeArchived, Style: "form", Explode: true},
			"types":            QueryValue{Value: types, Style: "form", Explode: true},
			"limit":            QueryValue{Value: limit, Style: "form", Explode: true},
			"cursor":           QueryValue{Value: cursor, Style: "form", Explode: true},
		},
		OperationID: "ConversationsList",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// ConversationsMark sets the authenticated user's read cursor in a conversation. Provide the conversation in `channel` and the timestamp of the most recently seen message in `ts`, using an authentication token with the `conversations:write` scope when authorization is required.
//
// Sets the read cursor in a channel.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:write`
//	channel: Channel or conversation to set the read cursor for.
//	ts: Unique identifier of message you want marked as most recently seen in
//	this conversation.
func ConversationsMark(ctx context.Context, clientConfig ClientConfig, token *string, channel *string, ts *float64) (*ConversationsMarkResponse, error) {
	resp, err := DoCfg[ConversationsMarkResponse](ctx, &clientConfig, "POST", "/conversations.mark", &RequestOpts{
		Body: map[string]any{
			"channel": channel,
			"ts":      ts,
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "ConversationsMark",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// ConversationsMembers lists the members of an existing conversation. Use `limit` and `cursor` to page through the member list, and authenticate with a token that has the `conversations:read` scope when authorization is required.
//
// Retrieve members of a conversation.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:read`
//	channel: ID of the conversation to retrieve members for
//	limit: The maximum number of items to return. Fewer than the requested
//	number of items may be returned, even if the end of the users list hasn't
//	been reached.
//	cursor: Paginate through collections of data by setting the `cursor`
//	parameter to a `next_cursor` attribute returned by a previous request's
//	`response_metadata`. Default value fetches the first "page" of the
//	collection. See pagination for more detail.
func ConversationsMembers(ctx context.Context, clientConfig ClientConfig, token *string, channel *string, limit *int64, cursor *string) (*ConversationsMembersResponse, error) {
	resp, err := DoCfg[ConversationsMembersResponse](ctx, &clientConfig, "GET", "/conversations.members", &RequestOpts{
		Query: map[string]any{
			"token":   QueryValue{Value: token, Style: "form", Explode: true},
			"channel": QueryValue{Value: channel, Style: "form", Explode: true},
			"limit":   QueryValue{Value: limit, Style: "form", Explode: true},
			"cursor":  QueryValue{Value: cursor, Style: "form", Explode: true},
		},
		OperationID: "ConversationsMembers",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// ConversationsOpen opens or resumes a direct message or multi-person direct message. Supply an existing direct conversation in `channel`, or provide one or more user IDs in `users`; use `return_im` when the full direct-message channel definition is needed in the response.
//
// Opens or resumes a direct message or multi-person direct message.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:write`
//	channel: Resume a conversation by supplying an `im` or `mpim`'s ID. Or
//	provide the `users` field instead.
//	users: Comma separated lists of users. If only one user is included, this
//	creates a 1:1 DM. The ordering of the users is preserved whenever a
//	multi-person direct message is returned. Supply a `channel` when not
//	supplying `users`.
//	returnIm: Boolean, indicates you want the full IM channel definition in the
//	response.
func ConversationsOpen(ctx context.Context, clientConfig ClientConfig, token *string, channel *string, users *string, returnIm *bool) (*ConversationsOpenResponse, error) {
	resp, err := DoCfg[ConversationsOpenResponse](ctx, &clientConfig, "POST", "/conversations.open", &RequestOpts{
		Body: map[string]any{
			"channel":   channel,
			"users":     users,
			"return_im": returnIm,
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "ConversationsOpen",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// ConversationsRename renames an existing conversation. Provide the conversation identifier in `channel` and the new name in `name`, using an authentication token with the `conversations:write` scope when authorization is required.
//
// Renames a conversation.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:write`
//	channel: ID of conversation to rename
//	name: New name for conversation.
func ConversationsRename(ctx context.Context, clientConfig ClientConfig, token *string, channel *string, name *string) (*ConversationsRenameResponse, error) {
	resp, err := DoCfg[ConversationsRenameResponse](ctx, &clientConfig, "POST", "/conversations.rename", &RequestOpts{
		Body: map[string]any{
			"channel": channel,
			"name":    name,
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "ConversationsRename",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// ConversationsReplies retrieves the messages in a conversation thread. Use `channel` and the parent message timestamp in `ts` to identify the thread, and use time bounds, `limit`, or `cursor` to control the returned messages.
//
// # Retrieve a thread of messages posted to a conversation
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:history`
//	channel: Conversation ID to fetch thread from.
//	ts: Unique identifier of a thread's parent message. `ts` must be the
//	timestamp of an existing message with 0 or more replies. If there are no
//	replies then just the single message referenced by `ts` will return - it is
//	just an ordinary, unthreaded message.
//	latest: End of time range of messages to include in results.
//	oldest: Start of time range of messages to include in results.
//	inclusive: Include messages with latest or oldest timestamp in results only
//	when either timestamp is specified.
//	limit: The maximum number of items to return. Fewer than the requested
//	number of items may be returned, even if the end of the users list hasn't
//	been reached.
//	cursor: Paginate through collections of data by setting the `cursor`
//	parameter to a `next_cursor` attribute returned by a previous request's
//	`response_metadata`. Default value fetches the first "page" of the
//	collection. See pagination for more detail.
func ConversationsReplies(ctx context.Context, clientConfig ClientConfig, token *string, channel *string, ts *float64, latest *float64, oldest *float64, inclusive *bool, limit *int64, cursor *string) (*ConversationsRepliesResponse, error) {
	resp, err := DoCfg[ConversationsRepliesResponse](ctx, &clientConfig, "GET", "/conversations.replies", &RequestOpts{
		Query: map[string]any{
			"token":     QueryValue{Value: token, Style: "form", Explode: true},
			"channel":   QueryValue{Value: channel, Style: "form", Explode: true},
			"ts":        QueryValue{Value: ts, Style: "form", Explode: true},
			"latest":    QueryValue{Value: latest, Style: "form", Explode: true},
			"oldest":    QueryValue{Value: oldest, Style: "form", Explode: true},
			"inclusive": QueryValue{Value: inclusive, Style: "form", Explode: true},
			"limit":     QueryValue{Value: limit, Style: "form", Explode: true},
			"cursor":    QueryValue{Value: cursor, Style: "form", Explode: true},
		},
		OperationID: "ConversationsReplies",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// ConversationsSetPurpose sets the purpose of an existing conversation. Provide the conversation in `channel` and the new purpose in `purpose`, using an authentication token with the `conversations:write` scope when authorization is required.
//
// Sets the purpose for a conversation.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:write`
//	channel: Conversation to set the purpose of
//	purpose: A new, specialer purpose
func ConversationsSetPurpose(ctx context.Context, clientConfig ClientConfig, token *string, channel *string, purpose *string) (*ConversationsSetPurposeResponse, error) {
	resp, err := DoCfg[ConversationsSetPurposeResponse](ctx, &clientConfig, "POST", "/conversations.setPurpose", &RequestOpts{
		Body: map[string]any{
			"channel": channel,
			"purpose": purpose,
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "ConversationsSetPurpose",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// ConversationsSetTopic updates the topic for a conversation. Provide `channel` to identify the conversation and `topic` for the replacement text; the topic does not support formatting or linkification.
//
// Sets the topic for a conversation.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:write`
//	channel: Conversation to set the topic of
//	topic: The new topic string. Does not support formatting or linkification.
func ConversationsSetTopic(ctx context.Context, clientConfig ClientConfig, token *string, channel *string, topic *string) (*ConversationsSetTopicResponse, error) {
	resp, err := DoCfg[ConversationsSetTopicResponse](ctx, &clientConfig, "POST", "/conversations.setTopic", &RequestOpts{
		Body: map[string]any{
			"channel": channel,
			"topic":   topic,
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "ConversationsSetTopic",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// ConversationsUnarchive restores an archived conversation to an active state. Provide `channel` to identify the conversation you want to unarchive.
//
// Reverses conversation archival.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:write`
//	channel: ID of conversation to unarchive
func ConversationsUnarchive(ctx context.Context, clientConfig ClientConfig, token *string, channel *string) (*ConversationsUnarchiveResponse, error) {
	resp, err := DoCfg[ConversationsUnarchiveResponse](ctx, &clientConfig, "POST", "/conversations.unarchive", &RequestOpts{
		Body: map[string]any{
			"channel": channel,
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "ConversationsUnarchive",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}
