// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"context"
	"encoding/json"
)

// DialogOpenResponse Schema for successful response from dialog.open method
type DialogOpenResponse struct {
	Ok DefsOkTrue `json:"ok"`
}

func (value *DialogOpenResponse) UnmarshalJSON(data []byte) error {
	type DialogOpenResponseAlias DialogOpenResponse
	var decoded DialogOpenResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = DialogOpenResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewDialogOpenResponse returns a validated DialogOpenResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewDialogOpenResponse(fields DialogOpenResponse) (*DialogOpenResponse, error) {
	return ConstructModel(fields)
}

// DialogOpen opens a dialog for a user by exchanging a trigger for a dialog submission. Provide the JSON-encoded `dialog` definition and the `trigger_id` issued for the interaction.
//
// Open a dialog with a user
//
// Parameters:
//
//	dialog: The dialog definition. This must be a JSON-encoded string.
//	triggerId: Exchange a trigger to post to the user.
//	token: Authentication token. Requires scope: `none`
func DialogOpen(ctx context.Context, clientConfig ClientConfig, dialog string, triggerId string, token string) (*DialogOpenResponse, error) {
	resp, err := DoCfg[DialogOpenResponse](ctx, &clientConfig, "GET", "/dialog.open", &RequestOpts{
		Query: map[string]any{
			"dialog":     QueryValue{Value: dialog, Style: "form", Explode: true},
			"trigger_id": QueryValue{Value: triggerId, Style: "form", Explode: true},
		},
		Headers: OperationHeaders(map[string]any{
					"token": token,
		}),
		OperationID: "DialogOpen",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}
