// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"context"
	"encoding/json"
)

// DndEndDndResponse Schema for successful response from dnd.endDnd method
type DndEndDndResponse struct {
	Ok DefsOkTrue `json:"ok"`
}

func (value *DndEndDndResponse) UnmarshalJSON(data []byte) error {
	type DndEndDndResponseAlias DndEndDndResponse
	var decoded DndEndDndResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = DndEndDndResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewDndEndDndResponse returns a validated DndEndDndResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewDndEndDndResponse(fields DndEndDndResponse) (*DndEndDndResponse, error) {
	return ConstructModel(fields)
}

// DndEndSnoozeResponse Schema for successful response from dnd.endSnooze method
type DndEndSnoozeResponse struct {
	DndEnabled     bool       `json:"dnd_enabled"`
	NextDndEndTs   int64      `json:"next_dnd_end_ts"`
	NextDndStartTs int64      `json:"next_dnd_start_ts"`
	Ok             DefsOkTrue `json:"ok"`
	SnoozeEnabled  bool       `json:"snooze_enabled"`
}

func (value *DndEndSnoozeResponse) UnmarshalJSON(data []byte) error {
	type DndEndSnoozeResponseAlias DndEndSnoozeResponse
	var decoded DndEndSnoozeResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = DndEndSnoozeResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok", "dnd_enabled", "next_dnd_start_ts", "next_dnd_end_ts", "snooze_enabled"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewDndEndSnoozeResponse returns a validated DndEndSnoozeResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewDndEndSnoozeResponse(fields DndEndSnoozeResponse) (*DndEndSnoozeResponse, error) {
	return ConstructModel(fields)
}

// DndInfoResponse Schema for successful response from dnd.info method
type DndInfoResponse struct {
	DndEnabled      bool       `json:"dnd_enabled"`
	NextDndEndTs    int64      `json:"next_dnd_end_ts"`
	NextDndStartTs  int64      `json:"next_dnd_start_ts"`
	Ok              DefsOkTrue `json:"ok"`
	SnoozeEnabled   *bool      `json:"snooze_enabled,omitempty"`
	SnoozeEndtime   *int64     `json:"snooze_endtime,omitempty"`
	SnoozeRemaining *int64     `json:"snooze_remaining,omitempty"`
}

func (value *DndInfoResponse) UnmarshalJSON(data []byte) error {
	type DndInfoResponseAlias DndInfoResponse
	var decoded DndInfoResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = DndInfoResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok", "dnd_enabled", "next_dnd_start_ts", "next_dnd_end_ts"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewDndInfoResponse returns a validated DndInfoResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewDndInfoResponse(fields DndInfoResponse) (*DndInfoResponse, error) {
	return ConstructModel(fields)
}

// DndSetSnoozeResponse Schema for successful response from dnd.setSnooze method
type DndSetSnoozeResponse struct {
	Ok              DefsOkTrue `json:"ok"`
	SnoozeEnabled   bool       `json:"snooze_enabled"`
	SnoozeEndtime   int64      `json:"snooze_endtime"`
	SnoozeRemaining int64      `json:"snooze_remaining"`
}

func (value *DndSetSnoozeResponse) UnmarshalJSON(data []byte) error {
	type DndSetSnoozeResponseAlias DndSetSnoozeResponse
	var decoded DndSetSnoozeResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = DndSetSnoozeResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok", "snooze_enabled", "snooze_endtime", "snooze_remaining"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewDndSetSnoozeResponse returns a validated DndSetSnoozeResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewDndSetSnoozeResponse(fields DndSetSnoozeResponse) (*DndSetSnoozeResponse, error) {
	return ConstructModel(fields)
}

// DndEndDnd ends the authenticated user's active Do Not Disturb session immediately. Use this operation when the authenticated user wants to stop the current Do Not Disturb period rather than wait for its scheduled end.
//
// Ends the current user's Do Not Disturb session immediately.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `dnd:write`
func DndEndDnd(ctx context.Context, clientConfig ClientConfig, token string) (*DndEndDndResponse, error) {
	resp, err := DoCfg[DndEndDndResponse](ctx, &clientConfig, "POST", "/dnd.endDnd", &RequestOpts{
		Headers: OperationHeaders(map[string]any{
					"token": token,
		}),
		OperationID: "DndEndDnd",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// DndEndSnooze ends the authenticated user's active snooze mode immediately. Use this operation to resume the normal Do Not Disturb schedule before the snooze period reaches its end time.
//
// Ends the current user's snooze mode immediately.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `dnd:write`
func DndEndSnooze(ctx context.Context, clientConfig ClientConfig, token string) (*DndEndSnoozeResponse, error) {
	resp, err := DoCfg[DndEndSnoozeResponse](ctx, &clientConfig, "POST", "/dnd.endSnooze", &RequestOpts{
		Headers: OperationHeaders(map[string]any{
					"token": token,
		}),
		OperationID: "DndEndSnooze",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// DndInfo retrieves the current Do Not Disturb status for a user. Omit `user` to retrieve the authenticated user's status, or provide a user identifier to inspect another user's status when permitted.
//
// Retrieves a user's current Do Not Disturb status.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `dnd:read`
//	user: User to fetch status for (defaults to current user)
func DndInfo(ctx context.Context, clientConfig ClientConfig, token *string, user *string) (*DndInfoResponse, error) {
	resp, err := DoCfg[DndInfoResponse](ctx, &clientConfig, "GET", "/dnd.info", &RequestOpts{
		Query: map[string]any{
			"token": QueryValue{Value: token, Style: "form", Explode: true},
			"user":  QueryValue{Value: user, Style: "form", Explode: true},
		},
		OperationID: "DndInfo",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// DndSetSnooze enables Do Not Disturb snooze mode for the authenticated user or changes its duration. Supply `token` and `num_minutes` to define how long the snooze should remain active.
//
// Turns on Do Not Disturb mode for the current user, or changes its duration.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `dnd:write`
//	numMinutes: Number of minutes, from now, to snooze until.
func DndSetSnooze(ctx context.Context, clientConfig ClientConfig, token string, numMinutes string) (*DndSetSnoozeResponse, error) {
	resp, err := DoCfg[DndSetSnoozeResponse](ctx, &clientConfig, "POST", "/dnd.setSnooze", &RequestOpts{
		Body: map[string]any{
			"token":       token,
			"num_minutes": numMinutes,
		},
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "DndSetSnooze",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// DndTeamInfo lists the Do Not Disturb status for up to 50 users on a team. Provide `users` as a comma-separated set of user identifiers, or omit it to use the method's default team scope.
//
// Retrieves the Do Not Disturb status for up to 50 users on a team.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `dnd:read`
//	users: Comma-separated list of users to fetch Do Not Disturb status for
func DndTeamInfo(ctx context.Context, clientConfig ClientConfig, token *string, users *string) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "GET", "/dnd.teamInfo", &RequestOpts{
		Query: map[string]any{
			"token": QueryValue{Value: token, Style: "form", Explode: true},
			"users": QueryValue{Value: users, Style: "form", Explode: true},
		},
		OperationID: "DndTeamInfo",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}
