// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

// EmojiList lists the custom emoji available for a team. Use this operation to retrieve the team's custom emoji collection with an authentication token that has emoji read access.
//
// Lists custom emoji for a team.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `emoji:read`
func EmojiList(ctx context.Context, clientConfig ClientConfig, token string) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "GET", "/emoji.list", &RequestOpts{
		Query: map[string]any{
			"token": QueryValue{Value: token, Style: "form", Explode: true},
		},
		OperationID: "EmojiList",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}
