// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"context"
	"encoding/json"
)

// FilesDeleteResponse Schema for successful response files.delete method
type FilesDeleteResponse struct {
	Ok DefsOkTrue `json:"ok"`
}

func (value *FilesDeleteResponse) UnmarshalJSON(data []byte) error {
	type FilesDeleteResponseAlias FilesDeleteResponse
	var decoded FilesDeleteResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = FilesDeleteResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewFilesDeleteResponse returns a validated FilesDeleteResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewFilesDeleteResponse(fields FilesDeleteResponse) (*FilesDeleteResponse, error) {
	return ConstructModel(fields)
}

// FilesInfoResponse Schema for successful response from files.info method
type FilesInfoResponse struct {
	Comments         []interface{}         `json:"comments"`
	ContentHtml      interface{}           `json:"content_html,omitempty"`
	Editor           *string               `json:"editor,omitempty"`
	File             ObjsFile              `json:"file"`
	Ok               DefsOkTrue            `json:"ok"`
	Paging           *ObjsPaging           `json:"paging,omitempty"`
	ResponseMetadata *ObjsResponseMetadata `json:"response_metadata,omitempty"`
}

func (value *FilesInfoResponse) UnmarshalJSON(data []byte) error {
	type FilesInfoResponseAlias FilesInfoResponse
	var decoded FilesInfoResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = FilesInfoResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok", "file", "comments"}); err != nil {
		return err
	}
	if value.Editor != nil {
		if err := ValidatePattern("editor", *value.Editor, "^[UW][A-Z0-9]{2,}$"); err != nil {
			return err
		}
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewFilesInfoResponse returns a validated FilesInfoResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewFilesInfoResponse(fields FilesInfoResponse) (*FilesInfoResponse, error) {
	return ConstructModel(fields)
}

// FilesListResponse Schema for successful response from files.list method
type FilesListResponse struct {
	Files  []ObjsFile `json:"files"`
	Ok     DefsOkTrue `json:"ok"`
	Paging ObjsPaging `json:"paging"`
}

func (value *FilesListResponse) UnmarshalJSON(data []byte) error {
	type FilesListResponseAlias FilesListResponse
	var decoded FilesListResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = FilesListResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok", "files", "paging"}); err != nil {
		return err
	}
	if err := ValidateItems("files", value.Files, LengthOpts{Min: Ptr[int](0)}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewFilesListResponse returns a validated FilesListResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewFilesListResponse(fields FilesListResponse) (*FilesListResponse, error) {
	return ConstructModel(fields)
}

// FilesRevokePublicURLResponse Schema for successful response from files.revokePublicURL method
type FilesRevokePublicURLResponse struct {
	File ObjsFile   `json:"file"`
	Ok   DefsOkTrue `json:"ok"`
}

func (value *FilesRevokePublicURLResponse) UnmarshalJSON(data []byte) error {
	type FilesRevokePublicURLResponseAlias FilesRevokePublicURLResponse
	var decoded FilesRevokePublicURLResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = FilesRevokePublicURLResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok", "file"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewFilesRevokePublicURLResponse returns a validated FilesRevokePublicURLResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewFilesRevokePublicURLResponse(fields FilesRevokePublicURLResponse) (*FilesRevokePublicURLResponse, error) {
	return ConstructModel(fields)
}

// FilesSharedPublicURLResponse Schema for successful response from files.sharedPublicURL method
type FilesSharedPublicURLResponse struct {
	File ObjsFile   `json:"file"`
	Ok   DefsOkTrue `json:"ok"`
}

func (value *FilesSharedPublicURLResponse) UnmarshalJSON(data []byte) error {
	type FilesSharedPublicURLResponseAlias FilesSharedPublicURLResponse
	var decoded FilesSharedPublicURLResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = FilesSharedPublicURLResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok", "file"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewFilesSharedPublicURLResponse returns a validated FilesSharedPublicURLResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewFilesSharedPublicURLResponse(fields FilesSharedPublicURLResponse) (*FilesSharedPublicURLResponse, error) {
	return ConstructModel(fields)
}

// FilesUploadResponse Schema for successful response files.upload method
type FilesUploadResponse struct {
	File ObjsFile   `json:"file"`
	Ok   DefsOkTrue `json:"ok"`
}

func (value *FilesUploadResponse) UnmarshalJSON(data []byte) error {
	type FilesUploadResponseAlias FilesUploadResponse
	var decoded FilesUploadResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = FilesUploadResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok", "file"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewFilesUploadResponse returns a validated FilesUploadResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewFilesUploadResponse(fields FilesUploadResponse) (*FilesUploadResponse, error) {
	return ConstructModel(fields)
}

// FilesDelete deletes a file identified by its file ID. Use the `file` field to select the file and provide a token with the required file-writing scope. The operation returns a success indicator when the file is deleted.
//
// Deletes a file.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `files:write:user`
//	file: ID of file to delete.
func FilesDelete(ctx context.Context, clientConfig ClientConfig, token *string, file *string) (*FilesDeleteResponse, error) {
	resp, err := DoCfg[FilesDeleteResponse](ctx, &clientConfig, "POST", "/files.delete", &RequestOpts{
		Body: map[string]any{
			"file": file,
		},
		Headers: OperationHeaders(map[string]any{
					"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "FilesDelete",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// FilesInfo retrieves information about a file and its comments. Use `file` to select the file and the pagination parameters to control the comments returned for that file. The response includes the file, comments, and paging metadata.
//
// Gets information about a file.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `files:read`
//	file: Specify a file by providing its ID.
//	limit: The maximum number of items to return. Fewer than the requested
//	number of items may be returned, even if the end of the list hasn't been
//	reached.
//	cursor: Parameter for pagination. File comments are paginated for a single
//	file. Set `cursor` equal to the `next_cursor` attribute returned by the
//	previous request's `response_metadata`. This parameter is optional, but
//	pagination is mandatory: the default value simply fetches the first "page"
//	of the collection of comments. See pagination for more details.
func FilesInfo(ctx context.Context, clientConfig ClientConfig, token *string, file *string, count *string, page *string, limit *int64, cursor *string) (*FilesInfoResponse, error) {
	resp, err := DoCfg[FilesInfoResponse](ctx, &clientConfig, "GET", "/files.info", &RequestOpts{
		Query: map[string]any{
			"token":  QueryValue{Value: token, Style: "form", Explode: true},
			"file":   QueryValue{Value: file, Style: "form", Explode: true},
			"count":  QueryValue{Value: count, Style: "form", Explode: true},
			"page":   QueryValue{Value: page, Style: "form", Explode: true},
			"limit":  QueryValue{Value: limit, Style: "form", Explode: true},
			"cursor": QueryValue{Value: cursor, Style: "form", Explode: true},
		},
		OperationID: "FilesInfo",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// FilesList lists files for a team, channel, or user with optional filters. Use `user`, `channel`, `ts_from`, `ts_to`, and `types` to narrow the results, and use the paging parameters to control the returned page. The response includes matching files and paging metadata.
//
// List for a team, in a channel, or from a user with applied filters.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `files:read`
//	user: Filter files created by a single user.
//	channel: Filter files appearing in a specific channel, indicated by its ID.
//	tsFrom: Filter files created after this timestamp (inclusive).
//	tsTo: Filter files created before this timestamp (inclusive).
//	types: Filter files by type (see below). You can pass multiple values in the
//	types argument, like `types=spaces,snippets`.The default value is `all`,
//	which does not filter the list.
//	showFilesHiddenByLimit: Show truncated file info for files hidden due to
//	being too old, and the team who owns the file being over the file limit.
func FilesList(ctx context.Context, clientConfig ClientConfig, token *string, user *string, channel *string, tsFrom *float64, tsTo *float64, types *string, count *string, page *string, showFilesHiddenByLimit *bool) (*FilesListResponse, error) {
	resp, err := DoCfg[FilesListResponse](ctx, &clientConfig, "GET", "/files.list", &RequestOpts{
		Query: map[string]any{
			"token":                      QueryValue{Value: token, Style: "form", Explode: true},
			"user":                       QueryValue{Value: user, Style: "form", Explode: true},
			"channel":                    QueryValue{Value: channel, Style: "form", Explode: true},
			"ts_from":                    QueryValue{Value: tsFrom, Style: "form", Explode: true},
			"ts_to":                      QueryValue{Value: tsTo, Style: "form", Explode: true},
			"types":                      QueryValue{Value: types, Style: "form", Explode: true},
			"count":                      QueryValue{Value: count, Style: "form", Explode: true},
			"page":                       QueryValue{Value: page, Style: "form", Explode: true},
			"show_files_hidden_by_limit": QueryValue{Value: showFilesHiddenByLimit, Style: "form", Explode: true},
		},
		OperationID: "FilesList",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// FilesRevokePublicURL revokes public or external sharing access for a file. Supply the file ID in `file` to identify the file whose public access you want to remove. The response includes the updated file object after access is revoked.
//
// Revokes public/external sharing access for a file
//
// Parameters:
//
//	token: Authentication token. Requires scope: `files:write:user`
//	file: File to revoke
func FilesRevokePublicURL(ctx context.Context, clientConfig ClientConfig, token *string, file *string) (*FilesRevokePublicURLResponse, error) {
	resp, err := DoCfg[FilesRevokePublicURLResponse](ctx, &clientConfig, "POST", "/files.revokePublicURL", &RequestOpts{
		Body: map[string]any{
			"file": file,
		},
		Headers: OperationHeaders(map[string]any{
					"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "FilesRevokePublicURL",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// FilesSharedPublicURL enables a file for public or external sharing. Supply the file identifier in `file` and an authentication token with the required file-writing scope. The response includes the updated file object after sharing is enabled.
//
// Enables a file for public/external sharing.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `files:write:user`
//	file: File to share
func FilesSharedPublicURL(ctx context.Context, clientConfig ClientConfig, token *string, file *string) (*FilesSharedPublicURLResponse, error) {
	resp, err := DoCfg[FilesSharedPublicURLResponse](ctx, &clientConfig, "POST", "/files.sharedPublicURL", &RequestOpts{
		Body: map[string]any{
			"file": file,
		},
		Headers: OperationHeaders(map[string]any{
					"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "FilesSharedPublicURL",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// FilesUpload uploads or creates a file and can share it with channels or attach it to a message thread. Provide either `file` or `content`, then use `filename`, `title`, `channels`, or `thread_ts` to control how the file is presented and shared. Include an initial message with `initial_comment` when introducing the file in specified channels.
//
// Uploads or creates a file.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `files:write:user`
//	file: File contents via `multipart/form-data`. If omitting this parameter,
//	you must submit `content`.
//	content: File contents via a POST variable. If omitting this parameter, you
//	must provide a `file`.
//	filetype: A file type identifier.
//	filename: Filename of file.
//	title: Title of file.
//	initialComment: The message text introducing the file in specified
//	`channels`.
//	channels: Comma-separated list of channel names or IDs where the file will
//	be shared.
//	threadTs: Provide another message's `ts` value to upload this file as a
//	reply. Never use a reply's `ts` value; use its parent instead.
func FilesUpload(ctx context.Context, clientConfig ClientConfig, token *string, file *string, content *string, filetype *string, filename *string, title *string, initialComment *string, channels *string, threadTs *float64) (*FilesUploadResponse, error) {
	resp, err := DoCfg[FilesUploadResponse](ctx, &clientConfig, "POST", "/files.upload", &RequestOpts{
		Body: map[string]any{
			"token":           token,
			"file":            file,
			"content":         content,
			"filetype":        filetype,
			"filename":        filename,
			"title":           title,
			"initial_comment": initialComment,
			"channels":        channels,
			"thread_ts":       threadTs,
		},
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "FilesUpload",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}
