// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"context"
	"encoding/json"
)

// FilesCommentsDeleteResponse Schema for successful response files.comments.delete method
type FilesCommentsDeleteResponse struct {
	Ok DefsOkTrue `json:"ok"`
}

func (value *FilesCommentsDeleteResponse) UnmarshalJSON(data []byte) error {
	type FilesCommentsDeleteResponseAlias FilesCommentsDeleteResponse
	var decoded FilesCommentsDeleteResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = FilesCommentsDeleteResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewFilesCommentsDeleteResponse returns a validated FilesCommentsDeleteResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewFilesCommentsDeleteResponse(fields FilesCommentsDeleteResponse) (*FilesCommentsDeleteResponse, error) {
	return ConstructModel(fields)
}

// FilesCommentsDelete deletes an existing comment from a file. Provide `file` to identify the file and `id` to identify the comment you want to remove.
//
// Deletes an existing comment on a file.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `files:write:user`
//	file: File to delete a comment from.
//	id: The comment to delete.
func FilesCommentsDelete(ctx context.Context, clientConfig ClientConfig, token *string, file *string, id *string) (*FilesCommentsDeleteResponse, error) {
	resp, err := DoCfg[FilesCommentsDeleteResponse](ctx, &clientConfig, "POST", "/files.comments.delete", &RequestOpts{
		Body: map[string]any{
			"file": file,
			"id":   id,
		},
		Headers: OperationHeaders(map[string]any{
					"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "FilesCommentsDelete",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}
