// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

// MigrationExchange maps workspace-specific user IDs to global user IDs for an Enterprise Grid workspace. Supply up to 400 comma-separated user IDs in `users`, and use `to_old` to request conversion from global IDs back to workspace-specific IDs. Include `team_id` when using an organization token to identify the workspace.
//
// # For Enterprise Grid workspaces, map local user IDs to global user IDs
//
// Parameters:
//
//	token: Authentication token. Requires scope: `tokens.basic`
//	users: A comma-separated list of user ids, up to 400 per request
//	teamId: Specify team_id starts with `T` in case of Org Token
//	toOld: Specify `true` to convert `W` global user IDs to workspace-specific
//	`U` IDs. Defaults to `false`.
func MigrationExchange(ctx context.Context, clientConfig ClientConfig, token string, users string, teamId *string, toOld *bool) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "GET", "/migration.exchange", &RequestOpts{
		Query: map[string]any{
			"token":   QueryValue{Value: token, Style: "form", Explode: true},
			"users":   QueryValue{Value: users, Style: "form", Explode: true},
			"team_id": QueryValue{Value: teamId, Style: "form", Explode: true},
			"to_old":  QueryValue{Value: toOld, Style: "form", Explode: true},
		},
		OperationID: "MigrationExchange",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}
