// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "encoding/json"

// ObjsResources Typed representation of the `ObjsResources` API schema.
type ObjsResources struct {
	// ExcludedIds Optional array value serialized in the `excluded_ids` wire field.
	ExcludedIds [][]interface{} `json:"excluded_ids,omitempty"`
	// Ids Required array value serialized in the `ids` wire field.
	Ids [][]interface{} `json:"ids"`
	// Wildcard Optional `boolean` value serialized in the `wildcard` wire field.
	Wildcard *bool `json:"wildcard,omitempty"`
}

func (value *ObjsResources) UnmarshalJSON(data []byte) error {
	type ObjsResourcesAlias ObjsResources
	var decoded ObjsResourcesAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ObjsResources(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ids"}); err != nil {
		return err
	}
	return nil
}

// NewObjsResources returns a validated ObjsResources built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewObjsResources(fields ObjsResources) (*ObjsResources, error) {
	return ConstructModel(fields)
}
