// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"bytes"
	"encoding/json"
)

func (value *ObjsMessage) UnmarshalJSON(data []byte) error {
	type ObjsMessageAlias ObjsMessage
	var decoded ObjsMessageAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ObjsMessage(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"text", "type", "ts"}); err != nil {
		return err
	}
	if func() bool { _, ok := rawFields["attachments"]; return ok }() {
		if err := ValidateItems("attachments", value.Attachments, LengthOpts{Min: Ptr[int](1)}); err != nil {
			return err
		}
	}
	if func() bool { _, ok := rawFields["files"]; return ok }() {
		if err := ValidateItems("files", value.Files, LengthOpts{Min: Ptr[int](1)}); err != nil {
			return err
		}
	}
	if value.Inviter != nil {
		if err := ValidatePattern("inviter", *value.Inviter, "^[UW][A-Z0-9]{2,}$"); err != nil {
			return err
		}
	}
	if value.LastRead != nil {
		if err := ValidatePattern("last_read", *value.LastRead, "^\\d{10}\\.\\d{6}$"); err != nil {
			return err
		}
	}
	if value.LatestReply != nil {
		if err := ValidatePattern("latest_reply", *value.LatestReply, "^\\d{10}\\.\\d{6}$"); err != nil {
			return err
		}
	}
	if value.ParentUserId != nil {
		if err := ValidatePattern("parent_user_id", *value.ParentUserId, "^[UW][A-Z0-9]{2,}$"); err != nil {
			return err
		}
	}
	if value.Permalink != nil {
		if err := ValidateUri("permalink", *value.Permalink); err != nil {
			return err
		}
	}
	if func() bool { _, ok := rawFields["reply_users"]; return ok }() {
		if err := ValidateItems("reply_users", value.ReplyUsers, LengthOpts{Min: Ptr[int](1)}); err != nil {
			return err
		}
	}
	if value.SourceTeam != nil {
		if err := ValidatePattern("source_team", *value.SourceTeam, "^[TE][A-Z0-9]{8,}$"); err != nil {
			return err
		}
	}
	if value.Team != nil {
		if err := ValidatePattern("team", *value.Team, "^[TE][A-Z0-9]{8,}$"); err != nil {
			return err
		}
	}
	if value.ThreadTs != nil {
		if err := ValidatePattern("thread_ts", *value.ThreadTs, "^\\d{10}\\.\\d{6}$"); err != nil {
			return err
		}
	}
	if err := ValidatePattern("ts", value.Ts, "^\\d{10}\\.\\d{6}$"); err != nil {
		return err
	}
	if value.User != nil {
		if err := ValidatePattern("user", *value.User, "^[UW][A-Z0-9]{2,}$"); err != nil {
			return err
		}
	}
	if value.UserTeam != nil {
		if err := ValidatePattern("user_team", *value.UserTeam, "^[TE][A-Z0-9]{8,}$"); err != nil {
			return err
		}
	}
	return nil
}

// NewObjsMessage returns a validated ObjsMessage built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewObjsMessage(fields ObjsMessage) (*ObjsMessage, error) {
	return ConstructModel(fields)
}

// ObjsMessageAttachments Required object value serialized in the `attachments[]` wire field.
type ObjsMessageAttachments struct {
	// Fallback Optional `string` value serialized in the `fallback` wire field.
	Fallback *string `json:"fallback,omitempty"`
	// Id Required `integer` value serialized in the `id` wire field.
	Id int64 `json:"id"`
	// ImageBytes Optional `integer` value serialized in the `image_bytes` wire field.
	ImageBytes *int64 `json:"image_bytes,omitempty"`
	// ImageHeight Optional `integer` value serialized in the `image_height` wire field.
	ImageHeight *int64 `json:"image_height,omitempty"`
	// ImageUrl Optional `string` value serialized in the `image_url` wire field.
	ImageUrl *string `json:"image_url,omitempty"`
	// ImageWidth Optional `integer` value serialized in the `image_width` wire field.
	ImageWidth *int64 `json:"image_width,omitempty"`
}

func (value *ObjsMessageAttachments) UnmarshalJSON(data []byte) error {
	type ObjsMessageAttachmentsAlias ObjsMessageAttachments
	var decoded ObjsMessageAttachmentsAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ObjsMessageAttachments(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"id"}); err != nil {
		return err
	}
	return nil
}

// NewObjsMessageAttachments returns a validated ObjsMessageAttachments built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewObjsMessageAttachments(fields ObjsMessageAttachments) (*ObjsMessageAttachments, error) {
	return ConstructModel(fields)
}

// ObjsMessageIcons Optional object value serialized in the `icons` wire field.
type ObjsMessageIcons struct {
	// Emoji Optional `string` value serialized in the `emoji` wire field.
	Emoji *string `json:"emoji,omitempty"`
	// Image64 Optional `uri`-formatted value serialized in the `image_64` wire field.
	Image64 *string `json:"image_64,omitempty"`
}

func (value *ObjsMessageIcons) UnmarshalJSON(data []byte) error {
	type ObjsMessageIconsAlias ObjsMessageIcons
	var decoded ObjsMessageIconsAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ObjsMessageIcons(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if value.Image64 != nil {
		if err := ValidateUri("image_64", *value.Image64); err != nil {
			return err
		}
	}
	return nil
}

// NewObjsMessageIcons returns a validated ObjsMessageIcons built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewObjsMessageIcons(fields ObjsMessageIcons) (*ObjsMessageIcons, error) {
	return ConstructModel(fields)
}

// ObjsPaging Typed representation of the `ObjsPaging` API schema.
type ObjsPaging struct {
	// Count Optional `integer` value serialized in the `count` wire field.
	Count *int64 `json:"count,omitempty"`
	// Page Required `integer` value serialized in the `page` wire field.
	Page int64 `json:"page"`
	// Pages Optional `integer` value serialized in the `pages` wire field.
	Pages *int64 `json:"pages,omitempty"`
	// PerPage Optional `integer` value serialized in the `per_page` wire field.
	PerPage *int64 `json:"per_page,omitempty"`
	// Spill Optional `integer` value serialized in the `spill` wire field.
	Spill *int64 `json:"spill,omitempty"`
	// Total Required `integer` value serialized in the `total` wire field.
	Total int64 `json:"total"`
}

func (value *ObjsPaging) UnmarshalJSON(data []byte) error {
	type ObjsPagingAlias ObjsPaging
	var decoded ObjsPagingAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ObjsPaging(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"page", "total"}); err != nil {
		return err
	}
	return nil
}

// NewObjsPaging returns a validated ObjsPaging built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewObjsPaging(fields ObjsPaging) (*ObjsPaging, error) {
	return ConstructModel(fields)
}

// ObjsPrimaryOwner Typed representation of the `ObjsPrimaryOwner` API schema.
type ObjsPrimaryOwner struct {
	// Email Required `string` value serialized in the `email` wire field.
	Email string `json:"email"`
	// Id Required `string` value serialized in the `id` wire field.
	Id string `json:"id"`
}

func (value *ObjsPrimaryOwner) UnmarshalJSON(data []byte) error {
	type ObjsPrimaryOwnerAlias ObjsPrimaryOwner
	var decoded ObjsPrimaryOwnerAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ObjsPrimaryOwner(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"id", "email"}); err != nil {
		return err
	}
	return nil
}

// NewObjsPrimaryOwner returns a validated ObjsPrimaryOwner built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewObjsPrimaryOwner(fields ObjsPrimaryOwner) (*ObjsPrimaryOwner, error) {
	return ConstructModel(fields)
}

// ObjsReaction Typed representation of the `ObjsReaction` API schema.
type ObjsReaction struct {
	// Count Required `integer` value serialized in the `count` wire field.
	Count int64 `json:"count"`
	// Name Required `string` value serialized in the `name` wire field.
	Name string `json:"name"`
	// Users Required array value serialized in the `users` wire field.
	Users []string `json:"users"`
}

func (value *ObjsReaction) UnmarshalJSON(data []byte) error {
	type ObjsReactionAlias ObjsReaction
	var decoded ObjsReactionAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ObjsReaction(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"name", "users", "count"}); err != nil {
		return err
	}
	return nil
}

// NewObjsReaction returns a validated ObjsReaction built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewObjsReaction(fields ObjsReaction) (*ObjsReaction, error) {
	return ConstructModel(fields)
}

// ObjsResponseMetadata Typed representation of the `ObjsResponseMetadata` API schema.
type ObjsResponseMetadata struct {
}

// ObjsScopes is an array alias.
type ObjsScopes = []string

// ObjsSubteam Typed representation of the `ObjsSubteam` API schema.
type ObjsSubteam struct {
	// AutoProvision Required `boolean` value serialized in the `auto_provision` wire field.
	AutoProvision bool `json:"auto_provision"`
	// AutoType Required array value serialized in the `auto_type` wire field.
	AutoType []interface{} `json:"auto_type"`
	// ChannelCount Optional `integer` value serialized in the `channel_count` wire field.
	ChannelCount *int64 `json:"channel_count,omitempty"`
	// CreatedBy Required `string` value serialized in the `created_by` wire field.
	CreatedBy string `json:"created_by"`
	// DateCreate Required `integer` value serialized in the `date_create` wire field.
	DateCreate int64 `json:"date_create"`
	// DateDelete Required `integer` value serialized in the `date_delete` wire field.
	DateDelete int64 `json:"date_delete"`
	// DateUpdate Required `integer` value serialized in the `date_update` wire field.
	DateUpdate int64 `json:"date_update"`
	// DeletedBy Required array value serialized in the `deleted_by` wire field.
	DeletedBy []interface{} `json:"deleted_by"`
	// Description Required `string` value serialized in the `description` wire field.
	Description string `json:"description"`
	// EnterpriseSubteamId Required `string` value serialized in the `enterprise_subteam_id` wire field.
	EnterpriseSubteamId string `json:"enterprise_subteam_id"`
	// Handle Required `string` value serialized in the `handle` wire field.
	Handle string `json:"handle"`
	// Id Required `string` value serialized in the `id` wire field.
	Id string `json:"id"`
	// IsExternal Required `boolean` value serialized in the `is_external` wire field.
	IsExternal bool `json:"is_external"`
	// IsSubteam Required `boolean` value serialized in the `is_subteam` wire field.
	IsSubteam bool `json:"is_subteam"`
	// IsUsergroup Required `boolean` value serialized in the `is_usergroup` wire field.
	IsUsergroup bool `json:"is_usergroup"`
	// Name Required `string` value serialized in the `name` wire field.
	Name string `json:"name"`
	// Prefs Required object value serialized in the `prefs` wire field.
	Prefs ObjsSubteamPrefs `json:"prefs"`
	// TeamId Required `string` value serialized in the `team_id` wire field.
	TeamId string `json:"team_id"`
	// UpdatedBy Required `string` value serialized in the `updated_by` wire field.
	UpdatedBy string `json:"updated_by"`
	// UserCount Optional `integer` value serialized in the `user_count` wire field.
	UserCount *int64 `json:"user_count,omitempty"`
	// Users Optional array value serialized in the `users` wire field.
	Users []string `json:"users,omitempty"`
}

func (value *ObjsSubteam) UnmarshalJSON(data []byte) error {
	type ObjsSubteamAlias ObjsSubteam
	var decoded ObjsSubteamAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ObjsSubteam(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"id", "team_id", "is_usergroup", "is_subteam", "name", "description", "handle", "is_external", "date_create", "date_update", "date_delete", "auto_type", "auto_provision", "enterprise_subteam_id", "created_by", "updated_by", "deleted_by", "prefs"}); err != nil {
		return err
	}
	if err := ValidatePattern("created_by", value.CreatedBy, "^[UW][A-Z0-9]{2,}$"); err != nil {
		return err
	}
	if err := ValidatePattern("id", value.Id, "^S[A-Z0-9]{2,}$"); err != nil {
		return err
	}
	if err := ValidatePattern("team_id", value.TeamId, "^[T][A-Z0-9]{2,}$"); err != nil {
		return err
	}
	if err := ValidatePattern("updated_by", value.UpdatedBy, "^[UW][A-Z0-9]{2,}$"); err != nil {
		return err
	}
	return nil
}

// NewObjsSubteam returns a validated ObjsSubteam built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewObjsSubteam(fields ObjsSubteam) (*ObjsSubteam, error) {
	return ConstructModel(fields)
}

// ObjsSubteamPrefs Required object value serialized in the `prefs` wire field.
type ObjsSubteamPrefs struct {
	// Channels Required array value serialized in the `channels` wire field.
	Channels []string `json:"channels"`
	// Groups Required array value serialized in the `groups` wire field.
	Groups []string `json:"groups"`
}

func (value *ObjsSubteamPrefs) UnmarshalJSON(data []byte) error {
	type ObjsSubteamPrefsAlias ObjsSubteamPrefs
	var decoded ObjsSubteamPrefsAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ObjsSubteamPrefs(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"channels", "groups"}); err != nil {
		return err
	}
	return nil
}

// NewObjsSubteamPrefs returns a validated ObjsSubteamPrefs built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewObjsSubteamPrefs(fields ObjsSubteamPrefs) (*ObjsSubteamPrefs, error) {
	return ConstructModel(fields)
}

// ObjsTeam Typed representation of the `ObjsTeam` API schema.
type ObjsTeam struct {
	// Archived Optional `boolean` value serialized in the `archived` wire field.
	Archived *bool `json:"archived,omitempty"`
	// AvatarBaseUrl Optional `uri`-formatted value serialized in the `avatar_base_url` wire field.
	AvatarBaseUrl *string `json:"avatar_base_url,omitempty"`
	// Created Optional `integer` value serialized in the `created` wire field.
	Created *int64 `json:"created,omitempty"`
	// DateCreate Optional `integer` value serialized in the `date_create` wire field.
	DateCreate *int64 `json:"date_create,omitempty"`
	// Deleted Optional `boolean` value serialized in the `deleted` wire field.
	Deleted *bool `json:"deleted,omitempty"`
	// Description Optional `string` value serialized in the `description` wire field.
	Description *NullableValue[string] `json:"description,omitempty"`
	// Discoverable Optional array value serialized in the `discoverable` wire field.
	Discoverable []interface{} `json:"discoverable,omitempty"`
	// Domain Required `string` value serialized in the `domain` wire field.
	Domain string `json:"domain"`
	// EmailDomain Required `string` value serialized in the `email_domain` wire field.
	EmailDomain string `json:"email_domain"`
	// EnterpriseId Optional `string` value serialized in the `enterprise_id` wire field.
	EnterpriseId *string `json:"enterprise_id,omitempty"`
	// EnterpriseName Optional `string` value serialized in the `enterprise_name` wire field.
	EnterpriseName *string `json:"enterprise_name,omitempty"`
	// ExternalOrgMigrations Optional object value serialized in the `external_org_migrations` wire field.
	ExternalOrgMigrations *ObjsExternalOrgMigrations `json:"external_org_migrations,omitempty"`
	// HasComplianceExport Optional `boolean` value serialized in the `has_compliance_export` wire field.
	HasComplianceExport *bool `json:"has_compliance_export,omitempty"`
	// Icon Required object value serialized in the `icon` wire field.
	Icon ObjsIcon `json:"icon"`
	// Id Required `string` value serialized in the `id` wire field.
	Id string `json:"id"`
	// IsAssigned Optional `boolean` value serialized in the `is_assigned` wire field.
	IsAssigned *bool `json:"is_assigned,omitempty"`
	// IsEnterprise Optional `integer` value serialized in the `is_enterprise` wire field.
	IsEnterprise *int64 `json:"is_enterprise,omitempty"`
	// IsOverStorageLimit Optional `boolean` value serialized in the `is_over_storage_limit` wire field.
	IsOverStorageLimit *bool `json:"is_over_storage_limit,omitempty"`
	// LimitTs Optional `integer` value serialized in the `limit_ts` wire field.
	LimitTs *int64 `json:"limit_ts,omitempty"`
	// Locale Optional `string` value serialized in the `locale` wire field.
	Locale *string `json:"locale,omitempty"`
	// MessagesCount Optional `integer` value serialized in the `messages_count` wire field.
	MessagesCount *int64 `json:"messages_count,omitempty"`
	// MsgEditWindowMins Optional `integer` value serialized in the `msg_edit_window_mins` wire field.
	MsgEditWindowMins *int64 `json:"msg_edit_window_mins,omitempty"`
	// Name Required `string` value serialized in the `name` wire field.
	Name string `json:"name"`
	// OverIntegrationsLimit Optional `boolean` value serialized in the `over_integrations_limit` wire field.
	OverIntegrationsLimit *bool `json:"over_integrations_limit,omitempty"`
	// OverStorageLimit Optional `boolean` value serialized in the `over_storage_limit` wire field.
	OverStorageLimit *bool `json:"over_storage_limit,omitempty"`
	// PayProdCur Optional `string` value serialized in the `pay_prod_cur` wire field.
	PayProdCur *string `json:"pay_prod_cur,omitempty"`
	// Plan Optional enumerated value serialized in the `plan` wire field.
	Plan *ObjsTeamPlanEnum `json:"plan,omitempty"`
	// PrimaryOwner Optional object value serialized in the `primary_owner` wire field.
	PrimaryOwner *ObjsPrimaryOwner `json:"primary_owner,omitempty"`
	// SsoProvider Optional object value serialized in the `sso_provider` wire field.
	SsoProvider *ObjsTeamSsoProvider `json:"sso_provider,omitempty"`
}

func (value *ObjsTeam) UnmarshalJSON(data []byte) error {
	type ObjsTeamAlias ObjsTeam
	var decoded ObjsTeamAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ObjsTeam(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"id", "name", "domain", "email_domain", "icon"}); err != nil {
		return err
	}
	if value.AvatarBaseUrl != nil {
		if err := ValidateUri("avatar_base_url", *value.AvatarBaseUrl); err != nil {
			return err
		}
	}
	if value.EnterpriseId != nil {
		if err := ValidatePattern("enterprise_id", *value.EnterpriseId, "^[E][A-Z0-9]{8,}$"); err != nil {
			return err
		}
	}
	if err := ValidatePattern("id", value.Id, "^[TE][A-Z0-9]{8,}$"); err != nil {
		return err
	}
	if value.Plan != nil {
		if err := ValidateEnum("plan", *value.Plan, []ObjsTeamPlanEnum{"", "std", "plus", "compliance", "enterprise"}); err != nil {
			return err
		}
	}
	if raw, ok := rawFields["description"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		value.Description = &NullableValue[string]{}
	}
	return nil
}

// NewObjsTeam returns a validated ObjsTeam built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewObjsTeam(fields ObjsTeam) (*ObjsTeam, error) {
	return ConstructModel(fields)
}

// ObjsTeamPlanEnum Optional enumerated value serialized in the `plan` wire field.
type ObjsTeamPlanEnum string

const (
	ObjsTeamPlanEnumUnknown    ObjsTeamPlanEnum = ""
	ObjsTeamPlanEnumStd        ObjsTeamPlanEnum = "std"
	ObjsTeamPlanEnumPlus       ObjsTeamPlanEnum = "plus"
	ObjsTeamPlanEnumCompliance ObjsTeamPlanEnum = "compliance"
	ObjsTeamPlanEnumEnterprise ObjsTeamPlanEnum = "enterprise"
)

// ObjsTeamSsoProvider Optional object value serialized in the `sso_provider` wire field.
type ObjsTeamSsoProvider struct {
	// Label Optional `string` value serialized in the `label` wire field.
	Label *string `json:"label,omitempty"`
	// Name Optional `string` value serialized in the `name` wire field.
	Name *string `json:"name,omitempty"`
	// Type Optional `string` value serialized in the `type` wire field.
	Type *string `json:"type,omitempty"`
}

// NewObjsTeamSsoProvider returns a validated ObjsTeamSsoProvider built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewObjsTeamSsoProvider(fields ObjsTeamSsoProvider) (*ObjsTeamSsoProvider, error) {
	return ConstructModel(fields)
}

// ObjsTeamProfileField Typed representation of the `ObjsTeamProfileField` API schema.
type ObjsTeamProfileField struct {
	// FieldName Optional `string` value serialized in the `field_name` wire field.
	FieldName *NullableValue[string] `json:"field_name,omitempty"`
	// Hint Required `string` value serialized in the `hint` wire field.
	Hint string `json:"hint"`
	// Id Required `string` value serialized in the `id` wire field.
	Id string `json:"id"`
	// IsHidden Optional `boolean` value serialized in the `is_hidden` wire field.
	IsHidden *bool `json:"is_hidden,omitempty"`
	// Label Required `string` value serialized in the `label` wire field.
	Label string `json:"label"`
	// Options Optional array value serialized in the `options` wire field.
	Options []interface{} `json:"options,omitempty"`
	// Ordering Required `number` value serialized in the `ordering` wire field.
	Ordering float64 `json:"ordering"`
	// PossibleValues Optional array value serialized in the `possible_values` wire field.
	PossibleValues *NullableValue[[]string] `json:"possible_values,omitempty"`
	// Type Required enumerated value serialized in the `type` wire field.
	Type ObjsTeamProfileFieldTypeEnum `json:"type"`
}

func (value *ObjsTeamProfileField) UnmarshalJSON(data []byte) error {
	type ObjsTeamProfileFieldAlias ObjsTeamProfileField
	var decoded ObjsTeamProfileFieldAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ObjsTeamProfileField(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"id", "ordering", "label", "hint", "type"}); err != nil {
		return err
	}
	if err := ValidatePattern("id", value.Id, "^X[a-zA-Z0-9]{9,}$"); err != nil {
		return err
	}
	if err := ValidateEnum("type", value.Type, []ObjsTeamProfileFieldTypeEnum{"text", "date", "link", "mailto", "options_list", "user"}); err != nil {
		return err
	}
	if raw, ok := rawFields["field_name"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		value.FieldName = &NullableValue[string]{}
	}
	if raw, ok := rawFields["possible_values"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		value.PossibleValues = &NullableValue[[]string]{}
	}
	return nil
}

// NewObjsTeamProfileField returns a validated ObjsTeamProfileField built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewObjsTeamProfileField(fields ObjsTeamProfileField) (*ObjsTeamProfileField, error) {
	return ConstructModel(fields)
}

// ObjsTeamProfileFieldTypeEnum Required enumerated value serialized in the `type` wire field.
type ObjsTeamProfileFieldTypeEnum string

const (
	ObjsTeamProfileFieldTypeEnumText        ObjsTeamProfileFieldTypeEnum = "text"
	ObjsTeamProfileFieldTypeEnumDate        ObjsTeamProfileFieldTypeEnum = "date"
	ObjsTeamProfileFieldTypeEnumLink        ObjsTeamProfileFieldTypeEnum = "link"
	ObjsTeamProfileFieldTypeEnumMailto      ObjsTeamProfileFieldTypeEnum = "mailto"
	ObjsTeamProfileFieldTypeEnumOptionsList ObjsTeamProfileFieldTypeEnum = "options_list"
	ObjsTeamProfileFieldTypeEnumUser        ObjsTeamProfileFieldTypeEnum = "user"
)

// ObjsTeamProfileFieldOption Typed representation of the `ObjsTeamProfileFieldOption` API schema.
type ObjsTeamProfileFieldOption struct {
	// IsCustom Optional `boolean` value serialized in the `is_custom` wire field.
	IsCustom *NullableValue[bool] `json:"is_custom,omitempty"`
	// IsMultipleEntry Optional `boolean` value serialized in the `is_multiple_entry` wire field.
	IsMultipleEntry *NullableValue[bool] `json:"is_multiple_entry,omitempty"`
	// IsProtected Optional `boolean` value serialized in the `is_protected` wire field.
	IsProtected *NullableValue[bool] `json:"is_protected,omitempty"`
	// IsScim Optional `boolean` value serialized in the `is_scim` wire field.
	IsScim *NullableValue[bool] `json:"is_scim,omitempty"`
}

func (value *ObjsTeamProfileFieldOption) UnmarshalJSON(data []byte) error {
	type ObjsTeamProfileFieldOptionAlias ObjsTeamProfileFieldOption
	var decoded ObjsTeamProfileFieldOptionAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ObjsTeamProfileFieldOption(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if raw, ok := rawFields["is_custom"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		value.IsCustom = &NullableValue[bool]{}
	}
	if raw, ok := rawFields["is_multiple_entry"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		value.IsMultipleEntry = &NullableValue[bool]{}
	}
	if raw, ok := rawFields["is_protected"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		value.IsProtected = &NullableValue[bool]{}
	}
	if raw, ok := rawFields["is_scim"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		value.IsScim = &NullableValue[bool]{}
	}
	return nil
}

// NewObjsTeamProfileFieldOption returns a validated ObjsTeamProfileFieldOption built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewObjsTeamProfileFieldOption(fields ObjsTeamProfileFieldOption) (*ObjsTeamProfileFieldOption, error) {
	return ConstructModel(fields)
}
