// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"bytes"
	"encoding/json"
)

// ObjsUserProfile Typed representation of the `ObjsUserProfile` API schema.
type ObjsUserProfile struct {
	// AlwaysActive Optional `boolean` value serialized in the `always_active` wire field.
	AlwaysActive *bool `json:"always_active,omitempty"`
	// ApiAppId Optional `string` value serialized in the `api_app_id` wire field.
	ApiAppId *string `json:"api_app_id,omitempty"`
	// AvatarHash Required `string` value serialized in the `avatar_hash` wire field.
	AvatarHash string `json:"avatar_hash"`
	// BotId Optional `string` value serialized in the `bot_id` wire field.
	BotId *string `json:"bot_id,omitempty"`
	// DisplayName Required `string` value serialized in the `display_name` wire field.
	DisplayName string `json:"display_name"`
	// DisplayNameNormalized Required `string` value serialized in the `display_name_normalized` wire field.
	DisplayNameNormalized string `json:"display_name_normalized"`
	// Email Optional `email`-formatted value serialized in the `email` wire field.
	Email *NullableValue[string] `json:"email,omitempty"`
	// Fields Required array value serialized in the `fields` wire field.
	Fields NullableValue[interface{}] `json:"fields"`
	// FirstName Optional `string` value serialized in the `first_name` wire field.
	FirstName *NullableValue[string] `json:"first_name,omitempty"`
	// GuestExpirationTs Optional `integer` value serialized in the `guest_expiration_ts` wire field.
	GuestExpirationTs *NullableValue[int64] `json:"guest_expiration_ts,omitempty"`
	// GuestInvitedBy Optional `string` value serialized in the `guest_invited_by` wire field.
	GuestInvitedBy *NullableValue[string] `json:"guest_invited_by,omitempty"`
	// Image1024 Optional `uri`-formatted value serialized in the `image_1024` wire field.
	Image1024 *NullableValue[string] `json:"image_1024,omitempty"`
	// Image192 Optional `uri`-formatted value serialized in the `image_192` wire field.
	Image192 *NullableValue[string] `json:"image_192,omitempty"`
	// Image24 Optional `uri`-formatted value serialized in the `image_24` wire field.
	Image24 *NullableValue[string] `json:"image_24,omitempty"`
	// Image32 Optional `uri`-formatted value serialized in the `image_32` wire field.
	Image32 *NullableValue[string] `json:"image_32,omitempty"`
	// Image48 Optional `uri`-formatted value serialized in the `image_48` wire field.
	Image48 *NullableValue[string] `json:"image_48,omitempty"`
	// Image512 Optional `uri`-formatted value serialized in the `image_512` wire field.
	Image512 *NullableValue[string] `json:"image_512,omitempty"`
	// Image72 Optional `uri`-formatted value serialized in the `image_72` wire field.
	Image72 *NullableValue[string] `json:"image_72,omitempty"`
	// ImageOriginal Optional `uri`-formatted value serialized in the `image_original` wire field.
	ImageOriginal *NullableValue[string] `json:"image_original,omitempty"`
	// IsAppUser Optional `boolean` value serialized in the `is_app_user` wire field.
	IsAppUser *bool `json:"is_app_user,omitempty"`
	// IsCustomImage Optional `boolean` value serialized in the `is_custom_image` wire field.
	IsCustomImage *bool `json:"is_custom_image,omitempty"`
	// IsRestricted Optional `boolean` value serialized in the `is_restricted` wire field.
	IsRestricted *NullableValue[bool] `json:"is_restricted,omitempty"`
	// IsUltraRestricted Optional `boolean` value serialized in the `is_ultra_restricted` wire field.
	IsUltraRestricted *NullableValue[bool] `json:"is_ultra_restricted,omitempty"`
	// LastAvatarImageHash Optional `string` value serialized in the `last_avatar_image_hash` wire field.
	LastAvatarImageHash *string `json:"last_avatar_image_hash,omitempty"`
	// LastName Optional `string` value serialized in the `last_name` wire field.
	LastName *NullableValue[string] `json:"last_name,omitempty"`
	// MembershipsCount Optional `integer` value serialized in the `memberships_count` wire field.
	MembershipsCount *int64 `json:"memberships_count,omitempty"`
	// Name Optional `string` value serialized in the `name` wire field.
	Name *NullableValue[string] `json:"name,omitempty"`
	// Phone Required `string` value serialized in the `phone` wire field.
	Phone string `json:"phone"`
	// Pronouns Optional `string` value serialized in the `pronouns` wire field.
	Pronouns *string `json:"pronouns,omitempty"`
	// RealName Required `string` value serialized in the `real_name` wire field.
	RealName string `json:"real_name"`
	// RealNameNormalized Required `string` value serialized in the `real_name_normalized` wire field.
	RealNameNormalized string `json:"real_name_normalized"`
	// Skype Required `string` value serialized in the `skype` wire field.
	Skype string `json:"skype"`
	// StatusDefaultEmoji Optional `string` value serialized in the `status_default_emoji` wire field.
	StatusDefaultEmoji *string `json:"status_default_emoji,omitempty"`
	// StatusDefaultText Optional `string` value serialized in the `status_default_text` wire field.
	StatusDefaultText *string `json:"status_default_text,omitempty"`
	// StatusDefaultTextCanonical Optional `string` value serialized in the `status_default_text_canonical` wire field.
	StatusDefaultTextCanonical *NullableValue[string] `json:"status_default_text_canonical,omitempty"`
	// StatusEmoji Required `string` value serialized in the `status_emoji` wire field.
	StatusEmoji string `json:"status_emoji"`
	// StatusExpiration Optional `integer` value serialized in the `status_expiration` wire field.
	StatusExpiration *int64 `json:"status_expiration,omitempty"`
	// StatusText Required `string` value serialized in the `status_text` wire field.
	StatusText string `json:"status_text"`
	// StatusTextCanonical Optional `string` value serialized in the `status_text_canonical` wire field.
	StatusTextCanonical *NullableValue[string] `json:"status_text_canonical,omitempty"`
	// Team Optional `string` value serialized in the `team` wire field.
	Team *string `json:"team,omitempty"`
	// Title Required `string` value serialized in the `title` wire field.
	Title string `json:"title"`
	// Updated Optional `integer` value serialized in the `updated` wire field.
	Updated *int64 `json:"updated,omitempty"`
	// UserId Optional `string` value serialized in the `user_id` wire field.
	UserId *string `json:"user_id,omitempty"`
	// Username Optional `string` value serialized in the `username` wire field.
	Username *NullableValue[string] `json:"username,omitempty"`
}

func (value *ObjsUserProfile) UnmarshalJSON(data []byte) error {
	type ObjsUserProfileAlias ObjsUserProfile
	var decoded ObjsUserProfileAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ObjsUserProfile(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"real_name", "display_name", "avatar_hash", "real_name_normalized", "display_name_normalized", "title", "phone", "skype", "status_text", "status_emoji", "fields"}); err != nil {
		return err
	}
	if value.ApiAppId != nil {
		if err := ValidatePattern("api_app_id", *value.ApiAppId, "^(A[A-Z0-9]{1,})?$"); err != nil {
			return err
		}
	}
	if value.BotId != nil {
		if err := ValidatePattern("bot_id", *value.BotId, "^B[A-Z0-9]{8,}$"); err != nil {
			return err
		}
	}
	if value.Team != nil {
		if err := ValidatePattern("team", *value.Team, "^[TE][A-Z0-9]{8,}$"); err != nil {
			return err
		}
	}
	if raw, ok := rawFields["email"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		value.Email = &NullableValue[string]{}
	}
	if raw, ok := rawFields["first_name"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		value.FirstName = &NullableValue[string]{}
	}
	if raw, ok := rawFields["guest_expiration_ts"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		value.GuestExpirationTs = &NullableValue[int64]{}
	}
	if raw, ok := rawFields["guest_invited_by"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		value.GuestInvitedBy = &NullableValue[string]{}
	}
	if raw, ok := rawFields["image_1024"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		value.Image1024 = &NullableValue[string]{}
	}
	if raw, ok := rawFields["image_192"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		value.Image192 = &NullableValue[string]{}
	}
	if raw, ok := rawFields["image_24"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		value.Image24 = &NullableValue[string]{}
	}
	if raw, ok := rawFields["image_32"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		value.Image32 = &NullableValue[string]{}
	}
	if raw, ok := rawFields["image_48"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		value.Image48 = &NullableValue[string]{}
	}
	if raw, ok := rawFields["image_512"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		value.Image512 = &NullableValue[string]{}
	}
	if raw, ok := rawFields["image_72"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		value.Image72 = &NullableValue[string]{}
	}
	if raw, ok := rawFields["image_original"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		value.ImageOriginal = &NullableValue[string]{}
	}
	if raw, ok := rawFields["is_restricted"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		value.IsRestricted = &NullableValue[bool]{}
	}
	if raw, ok := rawFields["is_ultra_restricted"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		value.IsUltraRestricted = &NullableValue[bool]{}
	}
	if raw, ok := rawFields["last_name"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		value.LastName = &NullableValue[string]{}
	}
	if raw, ok := rawFields["name"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		value.Name = &NullableValue[string]{}
	}
	if raw, ok := rawFields["status_default_text_canonical"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		value.StatusDefaultTextCanonical = &NullableValue[string]{}
	}
	if raw, ok := rawFields["status_text_canonical"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		value.StatusTextCanonical = &NullableValue[string]{}
	}
	if raw, ok := rawFields["username"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		value.Username = &NullableValue[string]{}
	}
	return nil
}

// NewObjsUserProfile returns a validated ObjsUserProfile built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewObjsUserProfile(fields ObjsUserProfile) (*ObjsUserProfile, error) {
	return ConstructModel(fields)
}

// ObjsUserProfileShort Typed representation of the `ObjsUserProfileShort` API schema.
type ObjsUserProfileShort struct {
	// AvatarHash Required `string` value serialized in the `avatar_hash` wire field.
	AvatarHash string `json:"avatar_hash"`
	// DisplayName Required `string` value serialized in the `display_name` wire field.
	DisplayName string `json:"display_name"`
	// DisplayNameNormalized Optional `string` value serialized in the `display_name_normalized` wire field.
	DisplayNameNormalized *string `json:"display_name_normalized,omitempty"`
	// FirstName Required `string` value serialized in the `first_name` wire field.
	FirstName NullableValue[string] `json:"first_name"`
	// Image72 Required `uri`-formatted value serialized in the `image_72` wire field.
	Image72 string `json:"image_72"`
	// IsRestricted Required `boolean` value serialized in the `is_restricted` wire field.
	IsRestricted bool `json:"is_restricted"`
	// IsUltraRestricted Required `boolean` value serialized in the `is_ultra_restricted` wire field.
	IsUltraRestricted bool `json:"is_ultra_restricted"`
	// Name Required `string` value serialized in the `name` wire field.
	Name string `json:"name"`
	// RealName Required `string` value serialized in the `real_name` wire field.
	RealName string `json:"real_name"`
	// RealNameNormalized Optional `string` value serialized in the `real_name_normalized` wire field.
	RealNameNormalized *string `json:"real_name_normalized,omitempty"`
	// Team Required `string` value serialized in the `team` wire field.
	Team string `json:"team"`
}

func (value *ObjsUserProfileShort) UnmarshalJSON(data []byte) error {
	type ObjsUserProfileShortAlias ObjsUserProfileShort
	var decoded ObjsUserProfileShortAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ObjsUserProfileShort(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"avatar_hash", "image_72", "first_name", "real_name", "display_name", "team", "name", "is_restricted", "is_ultra_restricted"}); err != nil {
		return err
	}
	if err := ValidateUri("image_72", value.Image72); err != nil {
		return err
	}
	if err := ValidatePattern("team", value.Team, "^[TE][A-Z0-9]{8,}$"); err != nil {
		return err
	}
	return nil
}

// NewObjsUserProfileShort returns a validated ObjsUserProfileShort built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewObjsUserProfileShort(fields ObjsUserProfileShort) (*ObjsUserProfileShort, error) {
	return ConstructModel(fields)
}
