// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "encoding/json"

// DefsReminderId is an alias for string.
type DefsReminderId = string

// ObjsReminder Typed representation of the `ObjsReminder` API schema.
type ObjsReminder struct {
	// CompleteTs Optional `integer` value serialized in the `complete_ts` wire field.
	CompleteTs *int64 `json:"complete_ts,omitempty"`
	// Creator Required `string` value serialized in the `creator` wire field.
	Creator string `json:"creator"`
	// Id Required `string` value serialized in the `id` wire field.
	Id string `json:"id"`
	// Recurring Required `boolean` value serialized in the `recurring` wire field.
	Recurring bool `json:"recurring"`
	// Text Required `string` value serialized in the `text` wire field.
	Text string `json:"text"`
	// Time Optional `integer` value serialized in the `time` wire field.
	Time *int64 `json:"time,omitempty"`
	// User Required `string` value serialized in the `user` wire field.
	User string `json:"user"`
}

func (value *ObjsReminder) UnmarshalJSON(data []byte) error {
	type ObjsReminderAlias ObjsReminder
	var decoded ObjsReminderAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ObjsReminder(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"id", "creator", "user", "text", "recurring"}); err != nil {
		return err
	}
	if err := ValidatePattern("creator", value.Creator, "^[UW][A-Z0-9]{2,}$"); err != nil {
		return err
	}
	if err := ValidatePattern("id", value.Id, "^Rm[A-Z0-9]{8,}$"); err != nil {
		return err
	}
	if err := ValidatePattern("user", value.User, "^[UW][A-Z0-9]{2,}$"); err != nil {
		return err
	}
	return nil
}

// NewObjsReminder returns a validated ObjsReminder built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewObjsReminder(fields ObjsReminder) (*ObjsReminder, error) {
	return ConstructModel(fields)
}
