// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "encoding/json"

// Blocks is an array alias.
type Blocks = []map[string]interface{}

// DefsAppId is an alias for string.
type DefsAppId = string

// DefsBotId is an alias for string.
type DefsBotId = string

// DefsChannel is an alias for string.
type DefsChannel = string

// DefsChannelId is an alias for string.
type DefsChannelId = string

// DefsChannelName is an alias for string.
type DefsChannelName = string

// DefsCommentId is an alias for string.
type DefsCommentId = string

// DefsDmId is an alias for string.
type DefsDmId = string

// DefsEnterpriseId is an alias for string.
type DefsEnterpriseId = string

// DefsEnterpriseName is an alias for string.
type DefsEnterpriseName = string

// DefsFileId is an alias for string.
type DefsFileId = string

// DefsGroupId is an alias for string.
type DefsGroupId = string

// DefsOkFalse Typed representation of the `DefsOkFalse` API schema.
type DefsOkFalse bool

const (
	DefsOkFalseFalse DefsOkFalse = false
)

// DefsOkTrue Typed representation of the `DefsOkTrue` API schema.
type DefsOkTrue bool

const (
	DefsOkTrueTrue DefsOkTrue = true
)

// DefsOptionalAppId is an alias for string.
type DefsOptionalAppId = string

// DefsPinnedInfo Typed representation of the `DefsPinnedInfo` API schema.
type DefsPinnedInfo struct {
}

// DefsSubteamId is an alias for string.
type DefsSubteamId = string

// DefsTeam is an alias for string.
type DefsTeam = string

// DefsTopicPurposeCreator is an alias for string.
type DefsTopicPurposeCreator = string

// DefsTs is an alias for string.
type DefsTs = string

// DefsUserId is an alias for string.
type DefsUserId = string

// DefsWorkspaceId is an alias for string.
type DefsWorkspaceId = string

// ObjsBotProfile Typed representation of the `ObjsBotProfile` API schema.
type ObjsBotProfile struct {
	// AppId Required `string` value serialized in the `app_id` wire field.
	AppId string `json:"app_id"`
	// Deleted Required `boolean` value serialized in the `deleted` wire field.
	Deleted bool `json:"deleted"`
	// Icons Required object value serialized in the `icons` wire field.
	Icons ObjsBotProfileIcons `json:"icons"`
	// Id Required `string` value serialized in the `id` wire field.
	Id string `json:"id"`
	// Name Required `string` value serialized in the `name` wire field.
	Name string `json:"name"`
	// TeamId Required `string` value serialized in the `team_id` wire field.
	TeamId string `json:"team_id"`
	// Updated Required `integer` value serialized in the `updated` wire field.
	Updated int64 `json:"updated"`
}

func (value *ObjsBotProfile) UnmarshalJSON(data []byte) error {
	type ObjsBotProfileAlias ObjsBotProfile
	var decoded ObjsBotProfileAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ObjsBotProfile(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"id", "deleted", "name", "updated", "app_id", "icons", "team_id"}); err != nil {
		return err
	}
	if err := ValidatePattern("app_id", value.AppId, "^A[A-Z0-9]{1,}$"); err != nil {
		return err
	}
	if err := ValidatePattern("id", value.Id, "^B[A-Z0-9]{8,}$"); err != nil {
		return err
	}
	if err := ValidatePattern("team_id", value.TeamId, "^[T][A-Z0-9]{2,}$"); err != nil {
		return err
	}
	return nil
}

// NewObjsBotProfile returns a validated ObjsBotProfile built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewObjsBotProfile(fields ObjsBotProfile) (*ObjsBotProfile, error) {
	return ConstructModel(fields)
}

// ObjsBotProfileIcons Required object value serialized in the `icons` wire field.
type ObjsBotProfileIcons struct {
	// Image36 Required `uri`-formatted value serialized in the `image_36` wire field.
	Image36 string `json:"image_36"`
	// Image48 Required `uri`-formatted value serialized in the `image_48` wire field.
	Image48 string `json:"image_48"`
	// Image72 Required `uri`-formatted value serialized in the `image_72` wire field.
	Image72 string `json:"image_72"`
}

func (value *ObjsBotProfileIcons) UnmarshalJSON(data []byte) error {
	type ObjsBotProfileIconsAlias ObjsBotProfileIcons
	var decoded ObjsBotProfileIconsAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ObjsBotProfileIcons(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"image_36", "image_48", "image_72"}); err != nil {
		return err
	}
	if err := ValidateUri("image_36", value.Image36); err != nil {
		return err
	}
	if err := ValidateUri("image_48", value.Image48); err != nil {
		return err
	}
	if err := ValidateUri("image_72", value.Image72); err != nil {
		return err
	}
	return nil
}

// NewObjsBotProfileIcons returns a validated ObjsBotProfileIcons built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewObjsBotProfileIcons(fields ObjsBotProfileIcons) (*ObjsBotProfileIcons, error) {
	return ConstructModel(fields)
}

// ObjsComment Typed representation of the `ObjsComment` API schema.
type ObjsComment struct {
	// Comment Required `string` value serialized in the `comment` wire field.
	Comment string `json:"comment"`
	// Created Required `integer` value serialized in the `created` wire field.
	Created int64 `json:"created"`
	// Id Required `string` value serialized in the `id` wire field.
	Id string `json:"id"`
	// IsIntro Required `boolean` value serialized in the `is_intro` wire field.
	IsIntro bool `json:"is_intro"`
	// IsStarred Optional `boolean` value serialized in the `is_starred` wire field.
	IsStarred *bool `json:"is_starred,omitempty"`
	// NumStars Optional `integer` value serialized in the `num_stars` wire field.
	NumStars *int64 `json:"num_stars,omitempty"`
	// PinnedInfo Optional object value serialized in the `pinned_info` wire field.
	PinnedInfo *DefsPinnedInfo `json:"pinned_info,omitempty"`
	// PinnedTo Optional array value serialized in the `pinned_to` wire field.
	PinnedTo []string `json:"pinned_to,omitempty"`
	// Reactions Optional array value serialized in the `reactions` wire field.
	Reactions []ObjsReaction `json:"reactions,omitempty"`
	// Timestamp Required `integer` value serialized in the `timestamp` wire field.
	Timestamp int64 `json:"timestamp"`
	// User Required `string` value serialized in the `user` wire field.
	User string `json:"user"`
}

func (value *ObjsComment) UnmarshalJSON(data []byte) error {
	type ObjsCommentAlias ObjsComment
	var decoded ObjsCommentAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ObjsComment(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"id", "created", "timestamp", "user", "is_intro", "comment"}); err != nil {
		return err
	}
	if err := ValidatePattern("id", value.Id, "^Fc[A-Z0-9]{8,}$"); err != nil {
		return err
	}
	if err := ValidatePattern("user", value.User, "^[UW][A-Z0-9]{2,}$"); err != nil {
		return err
	}
	return nil
}

// NewObjsComment returns a validated ObjsComment built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewObjsComment(fields ObjsComment) (*ObjsComment, error) {
	return ConstructModel(fields)
}

// ObjsConversation Typed representation of the `ObjsConversation` API schema.
type ObjsConversation struct {
}

// ObjsExternalOrgMigrations Typed representation of the `ObjsExternalOrgMigrations` API schema.
type ObjsExternalOrgMigrations struct {
	// Current Required array value serialized in the `current` wire field.
	Current []ObjsExternalOrgMigrationsCurrent `json:"current"`
	// DateUpdated Required `integer` value serialized in the `date_updated` wire field.
	DateUpdated int64 `json:"date_updated"`
}

func (value *ObjsExternalOrgMigrations) UnmarshalJSON(data []byte) error {
	type ObjsExternalOrgMigrationsAlias ObjsExternalOrgMigrations
	var decoded ObjsExternalOrgMigrationsAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ObjsExternalOrgMigrations(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"date_updated", "current"}); err != nil {
		return err
	}
	return nil
}

// NewObjsExternalOrgMigrations returns a validated ObjsExternalOrgMigrations built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewObjsExternalOrgMigrations(fields ObjsExternalOrgMigrations) (*ObjsExternalOrgMigrations, error) {
	return ConstructModel(fields)
}

// ObjsExternalOrgMigrationsCurrent Required object value serialized in the `current[]` wire field.
type ObjsExternalOrgMigrationsCurrent struct {
	// DateStarted Required `integer` value serialized in the `date_started` wire field.
	DateStarted int64 `json:"date_started"`
	// TeamId Required `string` value serialized in the `team_id` wire field.
	TeamId string `json:"team_id"`
}

func (value *ObjsExternalOrgMigrationsCurrent) UnmarshalJSON(data []byte) error {
	type ObjsExternalOrgMigrationsCurrentAlias ObjsExternalOrgMigrationsCurrent
	var decoded ObjsExternalOrgMigrationsCurrentAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ObjsExternalOrgMigrationsCurrent(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"team_id", "date_started"}); err != nil {
		return err
	}
	return nil
}

// NewObjsExternalOrgMigrationsCurrent returns a validated ObjsExternalOrgMigrationsCurrent built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewObjsExternalOrgMigrationsCurrent(fields ObjsExternalOrgMigrationsCurrent) (*ObjsExternalOrgMigrationsCurrent, error) {
	return ConstructModel(fields)
}

// ObjsFile Typed representation of the `ObjsFile` API schema.
type ObjsFile struct {
	// Channels Optional array value serialized in the `channels` wire field.
	Channels []string `json:"channels,omitempty"`
	// CommentsCount Optional `integer` value serialized in the `comments_count` wire field.
	CommentsCount *int64 `json:"comments_count,omitempty"`
	// Created Optional `integer` value serialized in the `created` wire field.
	Created *int64 `json:"created,omitempty"`
	// DateDelete Optional `integer` value serialized in the `date_delete` wire field.
	DateDelete *int64 `json:"date_delete,omitempty"`
	// DisplayAsBot Optional `boolean` value serialized in the `display_as_bot` wire field.
	DisplayAsBot *bool `json:"display_as_bot,omitempty"`
	// Editable Optional `boolean` value serialized in the `editable` wire field.
	Editable *bool `json:"editable,omitempty"`
	// Editor Optional `string` value serialized in the `editor` wire field.
	Editor *string `json:"editor,omitempty"`
	// ExternalId Optional `string` value serialized in the `external_id` wire field.
	ExternalId *string `json:"external_id,omitempty"`
	// ExternalType Optional `string` value serialized in the `external_type` wire field.
	ExternalType *string `json:"external_type,omitempty"`
	// ExternalUrl Optional `uri`-formatted value serialized in the `external_url` wire field.
	ExternalUrl *string `json:"external_url,omitempty"`
	// Filetype Optional `string` value serialized in the `filetype` wire field.
	Filetype *string `json:"filetype,omitempty"`
	// Groups Optional array value serialized in the `groups` wire field.
	Groups []string `json:"groups,omitempty"`
	// HasRichPreview Optional `boolean` value serialized in the `has_rich_preview` wire field.
	HasRichPreview *bool `json:"has_rich_preview,omitempty"`
	// Id Optional `string` value serialized in the `id` wire field.
	Id *string `json:"id,omitempty"`
	// ImageExifRotation Optional `integer` value serialized in the `image_exif_rotation` wire field.
	ImageExifRotation *int64 `json:"image_exif_rotation,omitempty"`
	// Ims Optional array value serialized in the `ims` wire field.
	Ims []string `json:"ims,omitempty"`
	// IsExternal Optional `boolean` value serialized in the `is_external` wire field.
	IsExternal *bool `json:"is_external,omitempty"`
	// IsPublic Optional `boolean` value serialized in the `is_public` wire field.
	IsPublic *bool `json:"is_public,omitempty"`
	// IsStarred Optional `boolean` value serialized in the `is_starred` wire field.
	IsStarred *bool `json:"is_starred,omitempty"`
	// IsTombstoned Optional `boolean` value serialized in the `is_tombstoned` wire field.
	IsTombstoned *bool `json:"is_tombstoned,omitempty"`
	// LastEditor Optional `string` value serialized in the `last_editor` wire field.
	LastEditor *string `json:"last_editor,omitempty"`
	// Mimetype Optional `string` value serialized in the `mimetype` wire field.
	Mimetype *string `json:"mimetype,omitempty"`
	// Mode Optional `string` value serialized in the `mode` wire field.
	Mode *string `json:"mode,omitempty"`
	// Name Optional `string` value serialized in the `name` wire field.
	Name *string `json:"name,omitempty"`
	// NonOwnerEditable Optional `boolean` value serialized in the `non_owner_editable` wire field.
	NonOwnerEditable *bool `json:"non_owner_editable,omitempty"`
	// NumStars Optional `integer` value serialized in the `num_stars` wire field.
	NumStars *int64 `json:"num_stars,omitempty"`
	// OriginalH Optional `integer` value serialized in the `original_h` wire field.
	OriginalH *int64 `json:"original_h,omitempty"`
	// OriginalW Optional `integer` value serialized in the `original_w` wire field.
	OriginalW *int64 `json:"original_w,omitempty"`
	// Permalink Optional `uri`-formatted value serialized in the `permalink` wire field.
	Permalink *string `json:"permalink,omitempty"`
	// PermalinkPublic Optional `uri`-formatted value serialized in the `permalink_public` wire field.
	PermalinkPublic *string `json:"permalink_public,omitempty"`
	// PinnedInfo Optional object value serialized in the `pinned_info` wire field.
	PinnedInfo *DefsPinnedInfo `json:"pinned_info,omitempty"`
	// PinnedTo Optional array value serialized in the `pinned_to` wire field.
	PinnedTo []string `json:"pinned_to,omitempty"`
	// PrettyType Optional `string` value serialized in the `pretty_type` wire field.
	PrettyType *string `json:"pretty_type,omitempty"`
	// Preview Optional `string` value serialized in the `preview` wire field.
	Preview *string `json:"preview,omitempty"`
	// PublicUrlShared Optional `boolean` value serialized in the `public_url_shared` wire field.
	PublicUrlShared *bool `json:"public_url_shared,omitempty"`
	// Reactions Optional array value serialized in the `reactions` wire field.
	Reactions []ObjsReaction `json:"reactions,omitempty"`
	// Shares Optional object value serialized in the `shares` wire field.
	Shares *ObjsFileShares `json:"shares,omitempty"`
	// Size Optional `integer` value serialized in the `size` wire field.
	Size *int64 `json:"size,omitempty"`
	// SourceTeam Optional `string` value serialized in the `source_team` wire field.
	SourceTeam *string `json:"source_team,omitempty"`
	// State Optional `string` value serialized in the `state` wire field.
	State *string `json:"state,omitempty"`
	// Thumb1024 Optional `uri`-formatted value serialized in the `thumb_1024` wire field.
	Thumb1024 *string `json:"thumb_1024,omitempty"`
	// Thumb1024H Optional `integer` value serialized in the `thumb_1024_h` wire field.
	Thumb1024H *int64 `json:"thumb_1024_h,omitempty"`
	// Thumb1024W Optional `integer` value serialized in the `thumb_1024_w` wire field.
	Thumb1024W *int64 `json:"thumb_1024_w,omitempty"`
	// Thumb160 Optional `uri`-formatted value serialized in the `thumb_160` wire field.
	Thumb160 *string `json:"thumb_160,omitempty"`
	// Thumb360 Optional `uri`-formatted value serialized in the `thumb_360` wire field.
	Thumb360 *string `json:"thumb_360,omitempty"`
	// Thumb360H Optional `integer` value serialized in the `thumb_360_h` wire field.
	Thumb360H *int64 `json:"thumb_360_h,omitempty"`
	// Thumb360W Optional `integer` value serialized in the `thumb_360_w` wire field.
	Thumb360W *int64 `json:"thumb_360_w,omitempty"`
	// Thumb480 Optional `uri`-formatted value serialized in the `thumb_480` wire field.
	Thumb480 *string `json:"thumb_480,omitempty"`
	// Thumb480H Optional `integer` value serialized in the `thumb_480_h` wire field.
	Thumb480H *int64 `json:"thumb_480_h,omitempty"`
	// Thumb480W Optional `integer` value serialized in the `thumb_480_w` wire field.
	Thumb480W *int64 `json:"thumb_480_w,omitempty"`
	// Thumb64 Optional `uri`-formatted value serialized in the `thumb_64` wire field.
	Thumb64 *string `json:"thumb_64,omitempty"`
	// Thumb720 Optional `uri`-formatted value serialized in the `thumb_720` wire field.
	Thumb720 *string `json:"thumb_720,omitempty"`
	// Thumb720H Optional `integer` value serialized in the `thumb_720_h` wire field.
	Thumb720H *int64 `json:"thumb_720_h,omitempty"`
	// Thumb720W Optional `integer` value serialized in the `thumb_720_w` wire field.
	Thumb720W *int64 `json:"thumb_720_w,omitempty"`
	// Thumb80 Optional `uri`-formatted value serialized in the `thumb_80` wire field.
	Thumb80 *string `json:"thumb_80,omitempty"`
	// Thumb800 Optional `uri`-formatted value serialized in the `thumb_800` wire field.
	Thumb800 *string `json:"thumb_800,omitempty"`
	// Thumb800H Optional `integer` value serialized in the `thumb_800_h` wire field.
	Thumb800H *int64 `json:"thumb_800_h,omitempty"`
	// Thumb800W Optional `integer` value serialized in the `thumb_800_w` wire field.
	Thumb800W *int64 `json:"thumb_800_w,omitempty"`
	// Thumb960 Optional `uri`-formatted value serialized in the `thumb_960` wire field.
	Thumb960 *string `json:"thumb_960,omitempty"`
	// Thumb960H Optional `integer` value serialized in the `thumb_960_h` wire field.
	Thumb960H *int64 `json:"thumb_960_h,omitempty"`
	// Thumb960W Optional `integer` value serialized in the `thumb_960_w` wire field.
	Thumb960W *int64 `json:"thumb_960_w,omitempty"`
	// ThumbTiny Optional `string` value serialized in the `thumb_tiny` wire field.
	ThumbTiny *string `json:"thumb_tiny,omitempty"`
	// Timestamp Optional `integer` value serialized in the `timestamp` wire field.
	Timestamp *int64 `json:"timestamp,omitempty"`
	// Title Optional `string` value serialized in the `title` wire field.
	Title *string `json:"title,omitempty"`
	// Updated Optional `integer` value serialized in the `updated` wire field.
	Updated *int64 `json:"updated,omitempty"`
	// UrlPrivate Optional `uri`-formatted value serialized in the `url_private` wire field.
	UrlPrivate *string `json:"url_private,omitempty"`
	// UrlPrivateDownload Optional `uri`-formatted value serialized in the `url_private_download` wire field.
	UrlPrivateDownload *string `json:"url_private_download,omitempty"`
	// User Optional `string` value serialized in the `user` wire field.
	User *string `json:"user,omitempty"`
	// UserTeam Optional `string` value serialized in the `user_team` wire field.
	UserTeam *string `json:"user_team,omitempty"`
	// Username Optional `string` value serialized in the `username` wire field.
	Username *string `json:"username,omitempty"`
}

func (value *ObjsFile) UnmarshalJSON(data []byte) error {
	type ObjsFileAlias ObjsFile
	var decoded ObjsFileAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ObjsFile(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if value.Editor != nil {
		if err := ValidatePattern("editor", *value.Editor, "^[UW][A-Z0-9]{2,}$"); err != nil {
			return err
		}
	}
	if value.ExternalUrl != nil {
		if err := ValidateUri("external_url", *value.ExternalUrl); err != nil {
			return err
		}
	}
	if value.Id != nil {
		if err := ValidatePattern("id", *value.Id, "^[F][A-Z0-9]{8,}$"); err != nil {
			return err
		}
	}
	if value.LastEditor != nil {
		if err := ValidatePattern("last_editor", *value.LastEditor, "^[UW][A-Z0-9]{2,}$"); err != nil {
			return err
		}
	}
	if value.Permalink != nil {
		if err := ValidateUri("permalink", *value.Permalink); err != nil {
			return err
		}
	}
	if value.PermalinkPublic != nil {
		if err := ValidateUri("permalink_public", *value.PermalinkPublic); err != nil {
			return err
		}
	}
	if value.SourceTeam != nil {
		if err := ValidatePattern("source_team", *value.SourceTeam, "^[T][A-Z0-9]{2,}$"); err != nil {
			return err
		}
	}
	if value.Thumb1024 != nil {
		if err := ValidateUri("thumb_1024", *value.Thumb1024); err != nil {
			return err
		}
	}
	if value.Thumb160 != nil {
		if err := ValidateUri("thumb_160", *value.Thumb160); err != nil {
			return err
		}
	}
	if value.Thumb360 != nil {
		if err := ValidateUri("thumb_360", *value.Thumb360); err != nil {
			return err
		}
	}
	if value.Thumb480 != nil {
		if err := ValidateUri("thumb_480", *value.Thumb480); err != nil {
			return err
		}
	}
	if value.Thumb64 != nil {
		if err := ValidateUri("thumb_64", *value.Thumb64); err != nil {
			return err
		}
	}
	if value.Thumb720 != nil {
		if err := ValidateUri("thumb_720", *value.Thumb720); err != nil {
			return err
		}
	}
	if value.Thumb80 != nil {
		if err := ValidateUri("thumb_80", *value.Thumb80); err != nil {
			return err
		}
	}
	if value.Thumb800 != nil {
		if err := ValidateUri("thumb_800", *value.Thumb800); err != nil {
			return err
		}
	}
	if value.Thumb960 != nil {
		if err := ValidateUri("thumb_960", *value.Thumb960); err != nil {
			return err
		}
	}
	if value.UrlPrivate != nil {
		if err := ValidateUri("url_private", *value.UrlPrivate); err != nil {
			return err
		}
	}
	if value.UrlPrivateDownload != nil {
		if err := ValidateUri("url_private_download", *value.UrlPrivateDownload); err != nil {
			return err
		}
	}
	if value.UserTeam != nil {
		if err := ValidatePattern("user_team", *value.UserTeam, "^[T][A-Z0-9]{2,}$"); err != nil {
			return err
		}
	}
	return nil
}

// NewObjsFile returns a validated ObjsFile built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewObjsFile(fields ObjsFile) (*ObjsFile, error) {
	return ConstructModel(fields)
}

// ObjsFileShares Optional object value serialized in the `shares` wire field.
type ObjsFileShares struct {
	// Private Optional API value serialized in the `private` wire field.
	Private interface{} `json:"private,omitempty"`
	// Public Optional API value serialized in the `public` wire field.
	Public interface{} `json:"public,omitempty"`
}

// NewObjsFileShares returns a validated ObjsFileShares built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewObjsFileShares(fields ObjsFileShares) (*ObjsFileShares, error) {
	return ConstructModel(fields)
}

// ObjsIcon Typed representation of the `ObjsIcon` API schema.
type ObjsIcon struct {
	// Image102 Optional `string` value serialized in the `image_102` wire field.
	Image102 *string `json:"image_102,omitempty"`
	// Image132 Optional `string` value serialized in the `image_132` wire field.
	Image132 *string `json:"image_132,omitempty"`
	// Image230 Optional `string` value serialized in the `image_230` wire field.
	Image230 *string `json:"image_230,omitempty"`
	// Image34 Optional `string` value serialized in the `image_34` wire field.
	Image34 *string `json:"image_34,omitempty"`
	// Image44 Optional `string` value serialized in the `image_44` wire field.
	Image44 *string `json:"image_44,omitempty"`
	// Image68 Optional `string` value serialized in the `image_68` wire field.
	Image68 *string `json:"image_68,omitempty"`
	// Image88 Optional `string` value serialized in the `image_88` wire field.
	Image88 *string `json:"image_88,omitempty"`
	// ImageDefault Optional `boolean` value serialized in the `image_default` wire field.
	ImageDefault *bool `json:"image_default,omitempty"`
}

// NewObjsIcon returns a validated ObjsIcon built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewObjsIcon(fields ObjsIcon) (*ObjsIcon, error) {
	return ConstructModel(fields)
}

// ObjsMessage Typed representation of the `ObjsMessage` API schema.
type ObjsMessage struct {
	// Attachments Optional array value serialized in the `attachments` wire field.
	Attachments []ObjsMessageAttachments `json:"attachments,omitempty"`
	// Blocks This is a very loose definition, in the future, we'll populate this with deeper schema in this definition namespace.
	Blocks []map[string]interface{} `json:"blocks,omitempty"`
	// BotId Optional array value serialized in the `bot_id` wire field.
	BotId []interface{} `json:"bot_id,omitempty"`
	// BotProfile Optional object value serialized in the `bot_profile` wire field.
	BotProfile *ObjsBotProfile `json:"bot_profile,omitempty"`
	// ClientMsgId Optional `string` value serialized in the `client_msg_id` wire field.
	ClientMsgId *string `json:"client_msg_id,omitempty"`
	// Comment Optional object value serialized in the `comment` wire field.
	Comment *ObjsComment `json:"comment,omitempty"`
	// DisplayAsBot Optional `boolean` value serialized in the `display_as_bot` wire field.
	DisplayAsBot *bool `json:"display_as_bot,omitempty"`
	// File Optional object value serialized in the `file` wire field.
	File *ObjsFile `json:"file,omitempty"`
	// Files Optional array value serialized in the `files` wire field.
	Files []ObjsFile `json:"files,omitempty"`
	// Icons Optional object value serialized in the `icons` wire field.
	Icons *ObjsMessageIcons `json:"icons,omitempty"`
	// Inviter Optional `string` value serialized in the `inviter` wire field.
	Inviter *string `json:"inviter,omitempty"`
	// IsDelayedMessage Optional `boolean` value serialized in the `is_delayed_message` wire field.
	IsDelayedMessage *bool `json:"is_delayed_message,omitempty"`
	// IsIntro Optional `boolean` value serialized in the `is_intro` wire field.
	IsIntro *bool `json:"is_intro,omitempty"`
	// IsStarred Optional `boolean` value serialized in the `is_starred` wire field.
	IsStarred *bool `json:"is_starred,omitempty"`
	// LastRead Optional `string` value serialized in the `last_read` wire field.
	LastRead *string `json:"last_read,omitempty"`
	// LatestReply Optional `string` value serialized in the `latest_reply` wire field.
	LatestReply *string `json:"latest_reply,omitempty"`
	// Name Optional `string` value serialized in the `name` wire field.
	Name *string `json:"name,omitempty"`
	// OldName Optional `string` value serialized in the `old_name` wire field.
	OldName *string `json:"old_name,omitempty"`
	// ParentUserId Optional `string` value serialized in the `parent_user_id` wire field.
	ParentUserId *string `json:"parent_user_id,omitempty"`
	// Permalink Optional `uri`-formatted value serialized in the `permalink` wire field.
	Permalink *string `json:"permalink,omitempty"`
	// PinnedTo Optional array value serialized in the `pinned_to` wire field.
	PinnedTo []string `json:"pinned_to,omitempty"`
	// Purpose Optional `string` value serialized in the `purpose` wire field.
	Purpose *string `json:"purpose,omitempty"`
	// Reactions Optional array value serialized in the `reactions` wire field.
	Reactions []ObjsReaction `json:"reactions,omitempty"`
	// ReplyCount Optional `integer` value serialized in the `reply_count` wire field.
	ReplyCount *int64 `json:"reply_count,omitempty"`
	// ReplyUsers Optional array value serialized in the `reply_users` wire field.
	ReplyUsers []string `json:"reply_users,omitempty"`
	// ReplyUsersCount Optional `integer` value serialized in the `reply_users_count` wire field.
	ReplyUsersCount *int64 `json:"reply_users_count,omitempty"`
	// SourceTeam Optional `string` value serialized in the `source_team` wire field.
	SourceTeam *string `json:"source_team,omitempty"`
	// Subscribed Optional `boolean` value serialized in the `subscribed` wire field.
	Subscribed *bool `json:"subscribed,omitempty"`
	// Subtype Optional `string` value serialized in the `subtype` wire field.
	Subtype *string `json:"subtype,omitempty"`
	// Team Optional `string` value serialized in the `team` wire field.
	Team *string `json:"team,omitempty"`
	// Text Required `string` value serialized in the `text` wire field.
	Text string `json:"text"`
	// ThreadTs Optional `string` value serialized in the `thread_ts` wire field.
	ThreadTs *string `json:"thread_ts,omitempty"`
	// Topic Optional `string` value serialized in the `topic` wire field.
	Topic *string `json:"topic,omitempty"`
	// Ts Required `string` value serialized in the `ts` wire field.
	Ts string `json:"ts"`
	// Type Required `string` value serialized in the `type` wire field.
	Type string `json:"type"`
	// UnreadCount Optional `integer` value serialized in the `unread_count` wire field.
	UnreadCount *int64 `json:"unread_count,omitempty"`
	// Upload Optional `boolean` value serialized in the `upload` wire field.
	Upload *bool `json:"upload,omitempty"`
	// User Optional `string` value serialized in the `user` wire field.
	User *string `json:"user,omitempty"`
	// UserProfile Optional object value serialized in the `user_profile` wire field.
	UserProfile *ObjsUserProfileShort `json:"user_profile,omitempty"`
	// UserTeam Optional `string` value serialized in the `user_team` wire field.
	UserTeam *string `json:"user_team,omitempty"`
	// Username Optional `string` value serialized in the `username` wire field.
	Username *string `json:"username,omitempty"`
}
