// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "encoding/json"

// DefsEnterpriseUserId is an alias for string.
type DefsEnterpriseUserId = string

// ObjsEnterpriseUser Typed representation of the `ObjsEnterpriseUser` API schema.
type ObjsEnterpriseUser struct {
	// EnterpriseId Required `string` value serialized in the `enterprise_id` wire field.
	EnterpriseId string `json:"enterprise_id"`
	// EnterpriseName Required `string` value serialized in the `enterprise_name` wire field.
	EnterpriseName string `json:"enterprise_name"`
	// Id Required `string` value serialized in the `id` wire field.
	Id string `json:"id"`
	// IsAdmin Required `boolean` value serialized in the `is_admin` wire field.
	IsAdmin bool `json:"is_admin"`
	// IsOwner Required `boolean` value serialized in the `is_owner` wire field.
	IsOwner bool `json:"is_owner"`
	// Teams Required array value serialized in the `teams` wire field.
	Teams []string `json:"teams"`
}

func (value *ObjsEnterpriseUser) UnmarshalJSON(data []byte) error {
	type ObjsEnterpriseUserAlias ObjsEnterpriseUser
	var decoded ObjsEnterpriseUserAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ObjsEnterpriseUser(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"id", "enterprise_id", "enterprise_name", "is_admin", "is_owner", "teams"}); err != nil {
		return err
	}
	if err := ValidatePattern("enterprise_id", value.EnterpriseId, "^[E][A-Z0-9]{8,}$"); err != nil {
		return err
	}
	if err := ValidatePattern("id", value.Id, "^[WU][A-Z0-9]{8,}$"); err != nil {
		return err
	}
	return nil
}

// NewObjsEnterpriseUser returns a validated ObjsEnterpriseUser built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewObjsEnterpriseUser(fields ObjsEnterpriseUser) (*ObjsEnterpriseUser, error) {
	return ConstructModel(fields)
}

// ObjsUser Typed representation of the `ObjsUser` API schema.
type ObjsUser struct {
}
