// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

// OauthAccess exchanges a temporary OAuth verifier code for an access token for a single-scope authorization flow. Supply the `code` returned through the OAuth callback and the application credentials, and ensure `redirect_uri` matches the URI originally submitted when one was used. Set `single_channel` only when requesting installation to a single channel for a legacy workspace app.
//
// Exchanges a temporary OAuth verifier code for an access token.
//
// Parameters:
//
//	clientId: Issued when you created your application.
//	clientSecret: Issued when you created your application.
//	code: The `code` param returned via the OAuth callback.
//	redirectUri: This must match the originally submitted URI (if one was sent).
//	singleChannel: Request the user to add your app only to a single channel.
//	Only valid with a [legacy workspace
//	app](https://api.slack.com/legacy-workspace-apps).
func OauthAccess(ctx context.Context, clientConfig ClientConfig, clientId *string, clientSecret *string, code *string, redirectUri *string, singleChannel *bool) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "GET", "/oauth.access", &RequestOpts{
		Query: map[string]any{
			"client_id":      QueryValue{Value: clientId, Style: "form", Explode: true},
			"client_secret":  QueryValue{Value: clientSecret, Style: "form", Explode: true},
			"code":           QueryValue{Value: code, Style: "form", Explode: true},
			"redirect_uri":   QueryValue{Value: redirectUri, Style: "form", Explode: true},
			"single_channel": QueryValue{Value: singleChannel, Style: "form", Explode: true},
		},
		OperationID: "OauthAccess",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}

// OauthToken exchanges a temporary OAuth verifier code for a workspace token. Supply the `code` returned through the OAuth callback and the application credentials, and ensure `redirect_uri` matches the URI originally submitted when one was used. Use `single_channel` to request installation to a single channel when supported by the workspace app.
//
// Exchanges a temporary OAuth verifier code for a workspace token.
//
// Parameters:
//
//	clientId: Issued when you created your application.
//	clientSecret: Issued when you created your application.
//	code: The `code` param returned via the OAuth callback.
//	redirectUri: This must match the originally submitted URI (if one was sent).
//	singleChannel: Request the user to add your app only to a single channel.
func OauthToken(ctx context.Context, clientConfig ClientConfig, clientId *string, clientSecret *string, code *string, redirectUri *string, singleChannel *bool) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "GET", "/oauth.token", &RequestOpts{
		Query: map[string]any{
			"client_id":      QueryValue{Value: clientId, Style: "form", Explode: true},
			"client_secret":  QueryValue{Value: clientSecret, Style: "form", Explode: true},
			"code":           QueryValue{Value: code, Style: "form", Explode: true},
			"redirect_uri":   QueryValue{Value: redirectUri, Style: "form", Explode: true},
			"single_channel": QueryValue{Value: singleChannel, Style: "form", Explode: true},
		},
		OperationID: "OauthToken",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}
