// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

// OauthV2Access exchanges a temporary OAuth verifier code for access tokens with scopes for a bot user and a user token. Supply the required `code` from the OAuth callback and the application credentials, and provide `redirect_uri` when it was part of the original authorization request. The response confirms whether the token exchange succeeded.
//
// Exchanges a temporary OAuth verifier code for an access token.
//
// Parameters:
//
//	code: The `code` param returned via the OAuth callback.
//	clientId: Issued when you created your application.
//	clientSecret: Issued when you created your application.
//	redirectUri: This must match the originally submitted URI (if one was sent).
func OauthV2Access(ctx context.Context, clientConfig ClientConfig, code string, clientId *string, clientSecret *string, redirectUri *string) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "GET", "/oauth.v2.access", &RequestOpts{
		Query: map[string]any{
			"code":          QueryValue{Value: code, Style: "form", Explode: true},
			"client_id":     QueryValue{Value: clientId, Style: "form", Explode: true},
			"client_secret": QueryValue{Value: clientSecret, Style: "form", Explode: true},
			"redirect_uri":  QueryValue{Value: redirectUri, Style: "form", Explode: true},
		},
		OperationID: "OauthV2Access",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}
