// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"context"
	"encoding/json"
)

// PinsAddResponse Schema for successful response from pins.add method
type PinsAddResponse struct {
	Ok DefsOkTrue `json:"ok"`
}

func (value *PinsAddResponse) UnmarshalJSON(data []byte) error {
	type PinsAddResponseAlias PinsAddResponse
	var decoded PinsAddResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = PinsAddResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewPinsAddResponse returns a validated PinsAddResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewPinsAddResponse(fields PinsAddResponse) (*PinsAddResponse, error) {
	return ConstructModel(fields)
}

// PinsRemoveResponse Schema for successful response from pins.remove method
type PinsRemoveResponse struct {
	Ok DefsOkTrue `json:"ok"`
}

func (value *PinsRemoveResponse) UnmarshalJSON(data []byte) error {
	type PinsRemoveResponseAlias PinsRemoveResponse
	var decoded PinsRemoveResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = PinsRemoveResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewPinsRemoveResponse returns a validated PinsRemoveResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewPinsRemoveResponse(fields PinsRemoveResponse) (*PinsRemoveResponse, error) {
	return ConstructModel(fields)
}

// PinsAdd pins an item to a channel. Supply the target `channel` and, when pinning a message, provide its `timestamp` to identify the item. Use an authentication token with the `pins:write` scope to perform the operation.
//
// Pins an item to a channel.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `pins:write`
//	channel: Channel to pin the item in.
//	timestamp: Timestamp of the message to pin.
func PinsAdd(ctx context.Context, clientConfig ClientConfig, token string, channel string, timestamp *string) (*PinsAddResponse, error) {
	resp, err := DoCfg[PinsAddResponse](ctx, &clientConfig, "POST", "/pins.add", &RequestOpts{
		Body: map[string]any{
			"channel":   channel,
			"timestamp": timestamp,
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "PinsAdd",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// PinsList lists the items pinned to a channel. Supply the channel identifier together with an authentication token that has permission to read pins. The response can contain either the pinned item collection or a count, depending on the returned result shape.
//
// Lists items pinned to a channel.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `pins:read`
//	channel: Channel to get pinned items for.
func PinsList(ctx context.Context, clientConfig ClientConfig, token string, channel string) ([]interface{}, error) {
	resp, err := DoCfg[[]interface{}](ctx, &clientConfig, "GET", "/pins.list", &RequestOpts{
		Query: map[string]any{
			"token":   QueryValue{Value: token, Style: "form", Explode: true},
			"channel": QueryValue{Value: channel, Style: "form", Explode: true},
		},
		OperationID: "PinsList",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}

// PinsRemove removes a pinned item from a channel. Supply the target `channel` and, when removing a pinned message, provide its `timestamp` to identify the item. Use an authentication token with the `pins:write` scope to perform the operation.
//
// Un-pins an item from a channel.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `pins:write`
//	channel: Channel where the item is pinned to.
//	timestamp: Timestamp of the message to un-pin.
func PinsRemove(ctx context.Context, clientConfig ClientConfig, token string, channel string, timestamp *string) (*PinsRemoveResponse, error) {
	resp, err := DoCfg[PinsRemoveResponse](ctx, &clientConfig, "POST", "/pins.remove", &RequestOpts{
		Body: map[string]any{
			"channel":   channel,
			"timestamp": timestamp,
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "PinsRemove",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}
