// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"context"
	"encoding/json"
)

// ReactionsAddResponse Schema for successful response from reactions.add method
type ReactionsAddResponse struct {
	Ok DefsOkTrue `json:"ok"`
}

func (value *ReactionsAddResponse) UnmarshalJSON(data []byte) error {
	type ReactionsAddResponseAlias ReactionsAddResponse
	var decoded ReactionsAddResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ReactionsAddResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewReactionsAddResponse returns a validated ReactionsAddResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewReactionsAddResponse(fields ReactionsAddResponse) (*ReactionsAddResponse, error) {
	return ConstructModel(fields)
}

// ReactionsListResponse Schema for successful response from reactions.list method
type ReactionsListResponse struct {
	Items            [][]interface{}       `json:"items"`
	Ok               DefsOkTrue            `json:"ok"`
	Paging           *ObjsPaging           `json:"paging,omitempty"`
	ResponseMetadata *ObjsResponseMetadata `json:"response_metadata,omitempty"`
}

func (value *ReactionsListResponse) UnmarshalJSON(data []byte) error {
	type ReactionsListResponseAlias ReactionsListResponse
	var decoded ReactionsListResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ReactionsListResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok", "items"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewReactionsListResponse returns a validated ReactionsListResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewReactionsListResponse(fields ReactionsListResponse) (*ReactionsListResponse, error) {
	return ConstructModel(fields)
}

// ReactionsRemoveResponse Schema for successful response from reactions.remove method
type ReactionsRemoveResponse struct {
	Ok DefsOkTrue `json:"ok"`
}

func (value *ReactionsRemoveResponse) UnmarshalJSON(data []byte) error {
	type ReactionsRemoveResponseAlias ReactionsRemoveResponse
	var decoded ReactionsRemoveResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ReactionsRemoveResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewReactionsRemoveResponse returns a validated ReactionsRemoveResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewReactionsRemoveResponse(fields ReactionsRemoveResponse) (*ReactionsRemoveResponse, error) {
	return ConstructModel(fields)
}

// ReactionsAdd adds an emoji reaction to a message or other supported item. Supply the channel, reaction name, and message timestamp to identify both the reaction and its target. Use an authentication token with the `reactions:write` scope to perform the operation.
//
// Adds a reaction to an item.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `reactions:write`
//	channel: Channel where the message to add reaction to was posted.
//	name: Reaction (emoji) name.
//	timestamp: Timestamp of the message to add reaction to.
func ReactionsAdd(ctx context.Context, clientConfig ClientConfig, token string, channel string, name string, timestamp string) (*ReactionsAddResponse, error) {
	resp, err := DoCfg[ReactionsAddResponse](ctx, &clientConfig, "POST", "/reactions.add", &RequestOpts{
		Body: map[string]any{
			"channel":   channel,
			"name":      name,
			"timestamp": timestamp,
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "ReactionsAdd",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// ReactionsGet retrieves reactions for a message, file, or file comment. Supply the authentication `token` and identify the item with the applicable target parameters; set `full` to request the complete reaction list. The response identifies the item and includes its reactions.
//
// Gets reactions for an item.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `reactions:read`
//	channel: Channel where the message to get reactions for was posted.
//	file: File to get reactions for.
//	fileComment: File comment to get reactions for.
//	full: If true always return the complete reaction list.
//	timestamp: Timestamp of the message to get reactions for.
func ReactionsGet(ctx context.Context, clientConfig ClientConfig, token string, channel *string, file *string, fileComment *string, full *bool, timestamp *string) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "GET", "/reactions.get", &RequestOpts{
		Query: map[string]any{
			"token":        QueryValue{Value: token, Style: "form", Explode: true},
			"channel":      QueryValue{Value: channel, Style: "form", Explode: true},
			"file":         QueryValue{Value: file, Style: "form", Explode: true},
			"file_comment": QueryValue{Value: fileComment, Style: "form", Explode: true},
			"full":         QueryValue{Value: full, Style: "form", Explode: true},
			"timestamp":    QueryValue{Value: timestamp, Style: "form", Explode: true},
		},
		OperationID: "ReactionsGet",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}

// ReactionsList lists reactions made by a specified user or by the authenticated user when `user` is omitted. Use `full` to request complete reaction details and use `cursor`, `page`, or `count` to control pagination and page size. The response includes reaction items, paging information, and continuation metadata.
//
// Lists reactions made by a user.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `reactions:read`
//	user: Show reactions made by this user. Defaults to the authed user.
//	full: If true always return the complete reaction list.
//	cursor: Parameter for pagination. Set `cursor` equal to the `next_cursor`
//	attribute returned by the previous request's `response_metadata`. This
//	parameter is optional, but pagination is mandatory: the default value simply
//	fetches the first "page" of the collection. See pagination for more details.
//	limit: The maximum number of items to return. Fewer than the requested
//	number of items may be returned, even if the end of the list hasn't been
//	reached.
func ReactionsList(ctx context.Context, clientConfig ClientConfig, token string, user *string, full *bool, count *int64, page *int64, cursor *string, limit *int64) (*ReactionsListResponse, error) {
	resp, err := DoCfg[ReactionsListResponse](ctx, &clientConfig, "GET", "/reactions.list", &RequestOpts{
		Query: map[string]any{
			"token":  QueryValue{Value: token, Style: "form", Explode: true},
			"user":   QueryValue{Value: user, Style: "form", Explode: true},
			"full":   QueryValue{Value: full, Style: "form", Explode: true},
			"count":  QueryValue{Value: count, Style: "form", Explode: true},
			"page":   QueryValue{Value: page, Style: "form", Explode: true},
			"cursor": QueryValue{Value: cursor, Style: "form", Explode: true},
			"limit":  QueryValue{Value: limit, Style: "form", Explode: true},
		},
		OperationID: "ReactionsList",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// ReactionsRemove removes a reaction from a message, file, or file comment. Supply the reaction `name` and identify the target with the applicable body fields. The response confirms that the reaction was removed.
//
// Removes a reaction from an item.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `reactions:write`
//	name: Reaction (emoji) name.
//	file: File to remove reaction from.
//	fileComment: File comment to remove reaction from.
//	channel: Channel where the message to remove reaction from was posted.
//	timestamp: Timestamp of the message to remove reaction from.
func ReactionsRemove(ctx context.Context, clientConfig ClientConfig, token string, name string, file *string, fileComment *string, channel *string, timestamp *string) (*ReactionsRemoveResponse, error) {
	resp, err := DoCfg[ReactionsRemoveResponse](ctx, &clientConfig, "POST", "/reactions.remove", &RequestOpts{
		Body: map[string]any{
			"name":         name,
			"file":         file,
			"file_comment": fileComment,
			"channel":      channel,
			"timestamp":    timestamp,
		},
		Headers: OperationHeaders(map[string]any{
			"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "ReactionsRemove",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}
