// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"context"
)

// ClientAuthConfig holds explicit request headers and optional credentials.
type ClientAuthConfig struct {
	Bearer  string
	Headers map[string]string
}



const defaultBaseURL = "https://slack.com/api"





// applyAuth attaches credentials to the outgoing request. Selection-aware
// modes validate the current operation before applying any scheme.
func applyAuth(ctx context.Context, cfg *ClientConfig, headers map[string]string, query map[string]any, operationID string) error {




	if cfg == nil || cfg.Auth == nil {
		return nil
	}
	if cfg.Auth.Bearer != "" {
		headers["Authorization"] = "Bearer " + cfg.Auth.Bearer
	}

	return nil

}
