// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

// SearchMessages searches messages matching the required `query` string. Use `count` and `page` to control result pages, `sort` and `sort_dir` to order matches, and `highlight` to include query highlight markers. The response confirms whether the search request completed successfully.
//
// Searches for messages matching a query.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `search:read`
//	query: Search query.
//	count: Pass the number of results you want per "page". Maximum of `100`.
//	highlight: Pass a value of `true` to enable query highlight markers (see
//	below).
//	sort: Return matches sorted by either `score` or `timestamp`.
//	sortDir: Change sort direction to ascending (`asc`) or descending (`desc`).
func SearchMessages(ctx context.Context, clientConfig ClientConfig, token string, query string, count *int64, highlight *bool, page *int64, sort *string, sortDir *string) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "GET", "/search.messages", &RequestOpts{
		Query: map[string]any{
			"token":     QueryValue{Value: token, Style: "form", Explode: true},
			"query":     QueryValue{Value: query, Style: "form", Explode: true},
			"count":     QueryValue{Value: count, Style: "form", Explode: true},
			"highlight": QueryValue{Value: highlight, Style: "form", Explode: true},
			"page":      QueryValue{Value: page, Style: "form", Explode: true},
			"sort":      QueryValue{Value: sort, Style: "form", Explode: true},
			"sort_dir":  QueryValue{Value: sortDir, Style: "form", Explode: true},
		},
		OperationID: "SearchMessages",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}
