// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

func NewAdminTeamsOwnersNamespace(config ClientConfig) *AdminTeamsOwnersNamespace {
	return &AdminTeamsOwnersNamespace{
		config: config,
	}
}

// List lists owners for a specified workspace. Provide `team_id` to select the workspace, and use `cursor` and `limit` to control pagination and page size. Authenticate with a token that has the `admin.teams:read` scope.
//
// List all of the owners on a given workspace.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.teams:read`
//	limit: The maximum number of items to return. Must be between 1 - 1000 both
//	inclusive.
//	cursor: Set `cursor` to `next_cursor` returned by the previous call to list
//	items in the next page.
func (sdk *AdminTeamsOwnersNamespace) List(ctx context.Context, token string, teamId string, limit *int64, cursor *string) (map[string]interface{}, error) {
	return AdminTeamsOwnersList(ctx, sdk.config, token, teamId, limit, cursor)
}

type AdminTeamsSettingsNamespace struct {
	config ClientConfig
}

func NewAdminTeamsSettingsNamespace(config ClientConfig) *AdminTeamsSettingsNamespace {
	return &AdminTeamsSettingsNamespace{
		config: config,
	}
}

// Info retrieves settings information for a specified workspace. Provide `team_id` to identify the workspace whose settings you want to inspect. Authenticate with a token that has the `admin.teams:read` scope.
//
// # Fetch information about settings in a workspace
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.teams:read`
func (sdk *AdminTeamsSettingsNamespace) Info(ctx context.Context, teamId string, token string) (map[string]interface{}, error) {
	return AdminTeamsSettingsInfo(ctx, sdk.config, teamId, token)
}

// SetDefaultChannels sets the default channels for a workspace. Supply `team_id` and `channel_ids` together with an authentication token that has the `admin.teams:write` scope. The `channel_ids` value identifies the channels that should be configured as defaults.
//
// Set the default channels of a workspace.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.teams:write`
//	teamId: ID for the workspace to set the default channel for.
//	channelIds: An array of channel IDs.
func (sdk *AdminTeamsSettingsNamespace) SetDefaultChannels(ctx context.Context, token string, teamId string, channelIds string) (map[string]interface{}, error) {
	return AdminTeamsSettingsSetDefaultChannels(ctx, sdk.config, token, teamId, channelIds)
}

// SetDescription sets the description of a specified workspace. Provide `team_id` to select the workspace and `description` for its new description. Authenticate with a token that has the `admin.teams:write` scope.
//
// Set the description of a given workspace.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.teams:write`
//	teamId: ID for the workspace to set the description for.
//	description: The new description for the workspace.
func (sdk *AdminTeamsSettingsNamespace) SetDescription(ctx context.Context, token string, teamId string, description string) (map[string]interface{}, error) {
	return AdminTeamsSettingsSetDescription(ctx, sdk.config, token, teamId, description)
}

// SetDiscoverability sets the discoverability setting for a specified workspace. Supply `team_id` and choose the workspace's new `discoverability` value. The value must be `open`, `invite_only`, `closed`, or `unlisted`.
//
// # An API method that allows admins to set the discoverability of a given workspace
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.teams:write`
//	teamId: The ID of the workspace to set discoverability on.
//	discoverability: This workspace's discovery setting. It must be set to one
//	of `open`, `invite_only`, `closed`, or `unlisted`.
func (sdk *AdminTeamsSettingsNamespace) SetDiscoverability(ctx context.Context, token string, teamId string, discoverability string) (map[string]interface{}, error) {
	return AdminTeamsSettingsSetDiscoverability(ctx, sdk.config, token, teamId, discoverability)
}

// SetIcon sets the icon for a workspace. Provide the workspace identifier in `team_id` and the icon image location in `image_url`. Authenticate the request with a token that has the `admin.teams:write` scope.
//
// Sets the icon of a workspace.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.teams:write`
//	imageUrl: Image URL for the icon
//	teamId: ID for the workspace to set the icon for.
func (sdk *AdminTeamsSettingsNamespace) SetIcon(ctx context.Context, token string, imageUrl string, teamId string) (map[string]interface{}, error) {
	return AdminTeamsSettingsSetIcon(ctx, sdk.config, token, imageUrl, teamId)
}

// SetName sets the name of a workspace. Provide `team_id` and the new value in `name`, and authenticate with a token that has permission to modify workspace settings. The operation returns a brief success response when the name is updated.
//
// Set the name of a given workspace.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.teams:write`
//	teamId: ID for the workspace to set the name for.
//	name: The new name of the workspace.
func (sdk *AdminTeamsSettingsNamespace) SetName(ctx context.Context, token string, teamId string, name string) (map[string]interface{}, error) {
	return AdminTeamsSettingsSetName(ctx, sdk.config, token, teamId, name)
}

type AdminUsergroupsNamespace struct {
	config ClientConfig
}

func NewAdminUsergroupsNamespace(config ClientConfig) *AdminUsergroupsNamespace {
	return &AdminUsergroupsNamespace{
		config: config,
	}
}

// AddChannels adds one or more default channels to an IDP group. Provide the group identifier and a comma-separated list of channel identifiers, and optionally scope the change to a workspace with `team_id`. Authenticate with a token that has the `admin.usergroups:write` scope.
//
// Add one or more default channels to an IDP group.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.usergroups:write`
//	usergroupId: ID of the IDP group to add default channels for.
//	channelIds: Comma separated string of channel IDs.
//	teamId: The workspace to add default channels in.
func (sdk *AdminUsergroupsNamespace) AddChannels(ctx context.Context, token string, usergroupId string, channelIds string, teamId *string) (map[string]interface{}, error) {
	return AdminUsergroupsAddChannels(ctx, sdk.config, token, usergroupId, channelIds, teamId)
}

// AddTeams associates one or more default workspaces with an organization-wide IDP group. Provide the group identifier and a comma-separated list of workspace identifiers in `team_ids`; each workspace must belong to the organization associated with the token. Set `auto_provision` to true to create workspace accounts automatically for IDP group members.
//
// Associate one or more default workspaces with an organization-wide IDP group.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.teams:write`
//	usergroupId: An encoded usergroup (IDP Group) ID.
//	teamIds: A comma separated list of encoded team (workspace) IDs. Each
//	workspace *MUST* belong to the organization associated with the token.
//	autoProvision: When `true`, this method automatically creates new workspace
//	accounts for the IDP group members.
func (sdk *AdminUsergroupsNamespace) AddTeams(ctx context.Context, token string, usergroupId string, teamIds string, autoProvision *bool) (map[string]interface{}, error) {
	return AdminUsergroupsAddTeams(ctx, sdk.config, token, usergroupId, teamIds, autoProvision)
}

// ListChannels lists the default channels linked to an organization-level IDP group. Provide `usergroup_id` and optionally use `team_id` to scope the results to a workspace. Set `include_num_members` to include or exclude member counts for each channel.
//
// List the channels linked to an org-level IDP group (user group).
//
// Parameters:
//
//	usergroupId: ID of the IDP group to list default channels for.
//	token: Authentication token. Requires scope: `admin.usergroups:read`
//	teamId: ID of the the workspace.
//	includeNumMembers: Flag to include or exclude the count of members per
//	channel.
func (sdk *AdminUsergroupsNamespace) ListChannels(ctx context.Context, usergroupId string, token string, teamId *string, includeNumMembers *bool) (map[string]interface{}, error) {
	return AdminUsergroupsListChannels(ctx, sdk.config, usergroupId, token, teamId, includeNumMembers)
}

// RemoveChannels removes one or more default channels from an organization-level IDP group. Provide the IDP group identifier and a comma-separated list of channel identifiers in `channel_ids`. Authenticate with a token that has the `admin.usergroups:write` scope.
//
// Remove one or more default channels from an org-level IDP group (user group).
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.usergroups:write`
//	usergroupId: ID of the IDP Group
//	channelIds: Comma-separated string of channel IDs
func (sdk *AdminUsergroupsNamespace) RemoveChannels(ctx context.Context, token string, usergroupId string, channelIds string) (map[string]interface{}, error) {
	return AdminUsergroupsRemoveChannels(ctx, sdk.config, token, usergroupId, channelIds)
}

type AdminUsersNamespace struct {
	config ClientConfig
}

func NewAdminUsersNamespace(config ClientConfig) *AdminUsersNamespace {
	return &AdminUsersNamespace{
		config: config,
	}
}

// Assign adds an Enterprise user to a workspace. Provide `team_id` and `user_id`, and optionally configure guest access with `is_restricted`, `is_ultra_restricted`, and `channel_ids`. Use a token with the `admin.users:write` scope to authorize the assignment.
//
// Add an Enterprise user to a workspace.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.users:write`
//	teamId: The ID (`T1234`) of the workspace.
//	userId: The ID of the user to add to the workspace.
//	isRestricted: True if user should be added to the workspace as a guest.
//	isUltraRestricted: True if user should be added to the workspace as a
//	single-channel guest.
//	channelIds: Comma separated values of channel IDs to add user in the new
//	workspace.
func (sdk *AdminUsersNamespace) Assign(ctx context.Context, token string, teamId string, userId string, isRestricted *bool, isUltraRestricted *bool, channelIds *string) (map[string]interface{}, error) {
	return AdminUsersAssign(ctx, sdk.config, token, teamId, userId, isRestricted, isUltraRestricted, channelIds)
}

// Invite invites a user to a workspace. Supply `team_id`, `email`, and at least one channel in `channel_ids`, then optionally configure the invite message, guest status, resend behavior, and account expiration. Use a token with the `admin.users:write` scope to authorize the invitation.
//
// Invite a user to a workspace.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.users:write`
//	teamId: The ID (`T1234`) of the workspace.
//	email: The email address of the person to invite.
//	channelIds: A comma-separated list of `channel_id`s for this user to join.
//	At least one channel is required.
//	customMessage: An optional message to send to the user in the invite email.
//	realName: Full name of the user.
//	resend: Allow this invite to be resent in the future if a user has not
//	signed up yet. (default: false)
//	isRestricted: Is this user a multi-channel guest user? (default: false)
//	isUltraRestricted: Is this user a single channel guest user? (default:
//	false)
//	guestExpirationTs: Timestamp when guest account should be disabled. Only
//	include this timestamp if you are inviting a guest user and you want their
//	account to expire on a certain date.
func (sdk *AdminUsersNamespace) Invite(ctx context.Context, token string, teamId string, email string, channelIds string, customMessage *string, realName *string, resend *bool, isRestricted *bool, isUltraRestricted *bool, guestExpirationTs *string) (map[string]interface{}, error) {
	return AdminUsersInvite(ctx, sdk.config, token, teamId, email, channelIds, customMessage, realName, resend, isRestricted, isUltraRestricted, guestExpirationTs)
}

// List lists users on a workspace. Provide `team_id` to select the workspace, and use `cursor` and `limit` to control cursor-based pagination. Pass the returned `next_cursor` as `cursor` to retrieve the next page.
//
// # List users on a workspace
//
// Parameters:
//
//	teamId: The ID (`T1234`) of the workspace.
//	token: Authentication token. Requires scope: `admin.users:read`
//	cursor: Set `cursor` to `next_cursor` returned by the previous call to list
//	items in the next page.
//	limit: Limit for how many users to be retrieved per page
func (sdk *AdminUsersNamespace) List(ctx context.Context, teamId string, token string, cursor *string, limit *int64) (map[string]interface{}, error) {
	return AdminUsersList(ctx, sdk.config, teamId, token, cursor, limit)
}

// Remove removes a user from a workspace. Provide the workspace identifier in `team_id` and the user identifier in `user_id` to identify the membership to remove. Authenticate with a token that has the `admin.users:write` scope.
//
// Remove a user from a workspace.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.users:write`
//	teamId: The ID (`T1234`) of the workspace.
//	userId: The ID of the user to remove.
func (sdk *AdminUsersNamespace) Remove(ctx context.Context, token string, teamId string, userId string) (map[string]interface{}, error) {
	return AdminUsersRemove(ctx, sdk.config, token, teamId, userId)
}

// SetAdmin promotes an existing guest, regular user, or owner to an admin user in a workspace. Supply `team_id` and `user_id` to identify the workspace and user whose role you want to change. The authenticated user must provide an administrative token with the required write scope.
//
// Set an existing guest, regular user, or owner to be an admin user.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.users:write`
//	teamId: The ID (`T1234`) of the workspace.
//	userId: The ID of the user to designate as an admin.
func (sdk *AdminUsersNamespace) SetAdmin(ctx context.Context, token string, teamId string, userId string) (map[string]interface{}, error) {
	return AdminUsersSetAdmin(ctx, sdk.config, token, teamId, userId)
}

// SetExpiration sets an expiration timestamp for a guest user in a workspace. Supply `team_id`, `user_id`, and `expiration_ts` to identify the guest account and the time when it should be disabled. The authenticated user must provide an administrative token with the required write scope.
//
// # Set an expiration for a guest user
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.users:write`
//	teamId: The ID (`T1234`) of the workspace.
//	userId: The ID of the user to set an expiration for.
//	expirationTs: Timestamp when guest account should be disabled.
func (sdk *AdminUsersNamespace) SetExpiration(ctx context.Context, token string, teamId string, userId string, expirationTs int64) (map[string]interface{}, error) {
	return AdminUsersSetExpiration(ctx, sdk.config, token, teamId, userId, expirationTs)
}

// SetOwner promotes an existing guest, regular user, or admin user to workspace owner. Supply `team_id` and `user_id` to identify the workspace and user whose role you want to change. The authenticated user must provide an administrative token with the required write scope.
//
// Set an existing guest, regular user, or admin user to be a workspace owner.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.users:write`
//	teamId: The ID (`T1234`) of the workspace.
//	userId: Id of the user to promote to owner.
func (sdk *AdminUsersNamespace) SetOwner(ctx context.Context, token string, teamId string, userId string) (map[string]interface{}, error) {
	return AdminUsersSetOwner(ctx, sdk.config, token, teamId, userId)
}

// SetRegular changes an existing guest, admin, or owner to a regular user in a workspace. Supply `team_id` and `user_id` to identify the workspace and user whose role you want to change. The authenticated user must provide an administrative token with the required write scope.
//
// Set an existing guest user, admin user, or owner to be a regular user.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.users:write`
//	teamId: The ID (`T1234`) of the workspace.
//	userId: The ID of the user to designate as a regular user.
func (sdk *AdminUsersNamespace) SetRegular(ctx context.Context, token string, teamId string, userId string) (map[string]interface{}, error) {
	return AdminUsersSetRegular(ctx, sdk.config, token, teamId, userId)
}

type AdminUsersSessionNamespace struct {
	config ClientConfig
}

func NewAdminUsersSessionNamespace(config ClientConfig) *AdminUsersSessionNamespace {
	return &AdminUsersSessionNamespace{
		config: config,
	}
}

// Invalidate invalidates one session belonging to a specified user. Supply `team_id` and `session_id` to identify the workspace session you want to invalidate. The authenticated user must provide an administrative token with the required write scope.
//
// Invalidate a single session for a user by session_id
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.users:write`
//	teamId: ID of the team that the session belongs to
func (sdk *AdminUsersSessionNamespace) Invalidate(ctx context.Context, token string, teamId string, sessionId int64) (map[string]interface{}, error) {
	return AdminUsersSessionInvalidate(ctx, sdk.config, token, teamId, sessionId)
}

// Reset invalidates all valid sessions for a specified user across all devices. Supply `user_id` and optionally limit invalidation to mobile or web sessions with `mobile_only` or `web_only`. The authenticated user must provide an administrative token with the required write scope.
//
// # Wipes all valid sessions on all devices for a given user
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin.users:write`
//	userId: The ID of the user to wipe sessions for
//	mobileOnly: Only expire mobile sessions (default: false)
//	webOnly: Only expire web sessions (default: false)
func (sdk *AdminUsersSessionNamespace) Reset(ctx context.Context, token string, userId string, mobileOnly *bool, webOnly *bool) (map[string]interface{}, error) {
	return AdminUsersSessionReset(ctx, sdk.config, token, userId, mobileOnly, webOnly)
}

type ApiNamespace struct {
	config ClientConfig
}

func NewApiNamespace(config ClientConfig) *ApiNamespace {
	return &ApiNamespace{
		config: config,
	}
}

// Test checks whether the API calling code can make a request and optionally returns a supplied test value. Use `error` to request an artificial error response and `foo` to include an example property in the response. This method is useful for validating request handling and response parsing.
//
// Checks API calling code.
//
// Parameters:
//
//	error_: Error response to return
//	foo: example property to return
func (sdk *ApiNamespace) Test(ctx context.Context, error_ *string, foo *string) (map[string]map[string]interface{}, error) {
	return ApiTest(ctx, sdk.config, error_, foo)
}

type AppsEventAuthorizationsNamespace struct {
	config ClientConfig
}

func NewAppsEventAuthorizationsNamespace(config ClientConfig) *AppsEventAuthorizationsNamespace {
	return &AppsEventAuthorizationsNamespace{
		config: config,
	}
}

// List lists the app installations authorized to receive events for a specified event context. Supply `event_context` to identify the event and use `cursor` and `limit` to page through the available authorizations. The authenticated user must provide a token with the `authorizations:read` scope.
//
// Get a list of authorizations for the given event context. Each authorization represents an app installation that the event is visible to.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `authorizations:read`
func (sdk *AppsEventAuthorizationsNamespace) List(ctx context.Context, eventContext string, token string, cursor *string, limit *int64) (map[string]interface{}, error) {
	return AppsEventAuthorizationsList(ctx, sdk.config, eventContext, token, cursor, limit)
}

type AppsPermissionsNamespace struct {
	config ClientConfig
}

func NewAppsPermissionsNamespace(config ClientConfig) *AppsPermissionsNamespace {
	return &AppsPermissionsNamespace{
		config: config,
	}
}

// Info retrieves the permissions that an app has for a workspace. The response organizes permission details for team, channel, group, direct-message, multi-party direct-message, and app-home resources. You can provide a token to identify the authenticated app or user context.
//
// Returns list of permissions this app has on a team.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `none`
func (sdk *AppsPermissionsNamespace) Info(ctx context.Context, token *string) (*AppsPermissionsInfoResponse, error) {
	return AppsPermissionsInfo(ctx, sdk.config, token)
}

// Request requests additional permissions for an app using a permissions trigger. Supply the requested scopes and the trigger token to start the permission request flow. The authenticated user must provide a token and a valid `trigger_id` accepted by the permissions API.
//
// # Allows an app to request additional scopes
//
// Parameters:
//
//	token: Authentication token. Requires scope: `none`
//	scopes: A comma separated list of scopes to request for
//	triggerId: Token used to trigger the permissions API
func (sdk *AppsPermissionsNamespace) Request(ctx context.Context, token string, scopes string, triggerId string) (*AppsPermissionsRequestResponse, error) {
	return AppsPermissionsRequest(ctx, sdk.config, token, scopes, triggerId)
}

type AppsPermissionsResourcesNamespace struct {
	config ClientConfig
}

func NewAppsPermissionsResourcesNamespace(config ClientConfig) *AppsPermissionsResourcesNamespace {
	return &AppsPermissionsResourcesNamespace{
		config: config,
	}
}

// List lists the resource grants that an app has on a team. Use `cursor` and `limit` to control pagination and the number of resources returned.
//
// Returns list of resource grants this app has on a team.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `none`
//	cursor: Paginate through collections of data by setting the `cursor`
//	parameter to a `next_cursor` attribute returned by a previous request's
//	`response_metadata`. Default value fetches the first "page" of the
//	collection. See pagination for more detail.
//	limit: The maximum number of items to return.
func (sdk *AppsPermissionsResourcesNamespace) List(ctx context.Context, token string, cursor *string, limit *int64) (map[string]interface{}, error) {
	return AppsPermissionsResourcesList(ctx, sdk.config, token, cursor, limit)
}

type AppsPermissionsScopesNamespace struct {
	config ClientConfig
}

func NewAppsPermissionsScopesNamespace(config ClientConfig) *AppsPermissionsScopesNamespace {
	return &AppsPermissionsScopesNamespace{
		config: config,
	}
}

// List lists the scopes that an app has on a team. The response groups granted scopes by resource type, including channels, groups, direct messages, multi-party direct messages, teams, users, and the app home.
//
// Returns list of scopes this app has on a team.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `none`
func (sdk *AppsPermissionsScopesNamespace) List(ctx context.Context, token string) (map[string]interface{}, error) {
	return AppsPermissionsScopesList(ctx, sdk.config, token)
}

type AppsPermissionsUsersNamespace struct {
	config ClientConfig
}

func NewAppsPermissionsUsersNamespace(config ClientConfig) *AppsPermissionsUsersNamespace {
	return &AppsPermissionsUsersNamespace{
		config: config,
	}
}

// List lists the user grants and corresponding scopes that an app has on a team. Use `cursor` and `limit` to paginate through the collection of user grants.
//
// Returns list of user grants and corresponding scopes this app has on a team.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `none`
//	cursor: Paginate through collections of data by setting the `cursor`
//	parameter to a `next_cursor` attribute returned by a previous request's
//	`response_metadata`. Default value fetches the first "page" of the
//	collection. See pagination for more detail.
//	limit: The maximum number of items to return.
func (sdk *AppsPermissionsUsersNamespace) List(ctx context.Context, token string, cursor *string, limit *int64) (map[string]interface{}, error) {
	return AppsPermissionsUsersList(ctx, sdk.config, token, cursor, limit)
}

// Request triggers a permissions modal to request user scopes for an app. Supply `scopes`, `trigger_id`, and `user` to identify the requested permissions, the interaction that initiated the request, and the user receiving the request.
//
// Enables an app to trigger a permissions modal to grant an app access to a user access scope.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `none`
//	scopes: A comma separated list of user scopes to request for
//	triggerId: Token used to trigger the request
//	user: The user this scope is being requested for
func (sdk *AppsPermissionsUsersNamespace) Request(ctx context.Context, token string, scopes string, triggerId string, user string) (map[string]interface{}, error) {
	return AppsPermissionsUsersRequest(ctx, sdk.config, token, scopes, triggerId, user)
}

type AppsNamespace struct {
	config ClientConfig
}

func NewAppsNamespace(config ClientConfig) *AppsNamespace {
	return &AppsNamespace{
		config: config,
	}
}

// Uninstall triggers uninstallation of an app from a workspace. Provide the authentication and application credentials accepted by the app installation flow to identify the app and authorize its removal.
//
// Uninstalls your app from a workspace.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `none`
//	clientId: Issued when you created your application.
//	clientSecret: Issued when you created your application.
func (sdk *AppsNamespace) Uninstall(ctx context.Context, token *string, clientId *string, clientSecret *string) (*AppsUninstallResponse, error) {
	return AppsUninstall(ctx, sdk.config, token, clientId, clientSecret)
}

type AuthNamespace struct {
	config ClientConfig
}

func NewAuthNamespace(config ClientConfig) *AuthNamespace {
	return &AuthNamespace{
		config: config,
	}
}

// Revoke revokes an authentication token. Use `test` to exercise the revocation flow without actually revoking the specified token.
//
// Revokes a token.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `none`
//	test: Setting this parameter to `1` triggers a _testing mode_ where the
//	specified token will not actually be revoked.
func (sdk *AuthNamespace) Revoke(ctx context.Context, token string, test *bool) (*AuthRevokeResponse, error) {
	return AuthRevoke(ctx, sdk.config, token, test)
}

// Test verifies the authentication token and retrieves the identity and team associated with it. Use the returned team and user identifiers to confirm which team and user the authenticated user represents.
//
// Checks authentication & identity.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `none`
func (sdk *AuthNamespace) Test(ctx context.Context, token string) (*AuthTestResponse, error) {
	return AuthTest(ctx, sdk.config, token)
}

type BotsNamespace struct {
	config ClientConfig
}

func NewBotsNamespace(config ClientConfig) *BotsNamespace {
	return &BotsNamespace{
		config: config,
	}
}

// Info retrieves information about a bot user. Omit `bot` to use the applicable default bot context, or provide a bot user identifier to retrieve a specific bot.
//
// Gets information about a bot user.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `users:read`
//	bot: Bot user to get info on
func (sdk *BotsNamespace) Info(ctx context.Context, token string, bot *string) (*BotsInfoResponse, error) {
	return BotsInfo(ctx, sdk.config, token, bot)
}

type CallsNamespace struct {
	config ClientConfig
}

func NewCallsNamespace(config ClientConfig) *CallsNamespace {
	return &CallsNamespace{
		config: config,
	}
}

// Add creates a registration for a third-party call. Supply a unique `external_unique_id` and a `join_url`, and optionally provide display, timing, creator, and participant details.
//
// Registers a new Call.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `calls:write`
//	externalUniqueId: An ID supplied by the 3rd-party Call provider. It must be
//	unique across all Calls from that service.
//	joinUrl: The URL required for a client to join the Call.
//	externalDisplayId: An optional, human-readable ID supplied by the 3rd-party
//	Call provider. If supplied, this ID will be displayed in the Call object.
//	desktopAppJoinUrl: When supplied, available Slack clients will attempt to
//	directly launch the 3rd-party Call with this URL.
//	dateStart: Call start time in UTC UNIX timestamp format
//	title: The name of the Call.
//	createdBy: The valid Slack user ID of the user who created this Call. When
//	this method is called with a user token, the `created_by` field is optional
//	and defaults to the authed user of the token. Otherwise, the field is
//	required.
//	users: The list of users to register as participants in the Call. Read more
//	on how to specify users here.
func (sdk *CallsNamespace) Add(ctx context.Context, token string, externalUniqueId string, joinUrl string, externalDisplayId *string, desktopAppJoinUrl *string, dateStart *int64, title *string, createdBy *string, users *string) (map[string]interface{}, error) {
	return CallsAdd(ctx, sdk.config, token, externalUniqueId, joinUrl, externalDisplayId, desktopAppJoinUrl, dateStart, title, createdBy, users)
}

// End ends a registered call and records its final duration when supplied. Use the `id` returned by `calls.add` to identify the call being ended.
//
// Ends a Call.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `calls:write`
//	id: `id` returned when registering the call using the `calls.add` method.
//	duration: Call duration in seconds
func (sdk *CallsNamespace) End(ctx context.Context, token string, id string, duration *int64) (map[string]interface{}, error) {
	return CallsEnd(ctx, sdk.config, token, id, duration)
}

// Info retrieves information about a Call identified by its call ID. Supply `token` with the required calls:read scope and use the `id` returned by calls.add. Use the returned call details to inspect the current Call configuration.
//
// Returns information about a Call.
//
// Parameters:
//
//	id: `id` of the Call returned by the `calls.add` method.
//	token: Authentication token. Requires scope: `calls:read`
func (sdk *CallsNamespace) Info(ctx context.Context, id string, token string) (map[string]interface{}, error) {
	return CallsInfo(ctx, sdk.config, id, token)
}

// Update updates information about an existing Call. Supply the Call `id` returned by calls.add and provide any Call details you want to change, such as its title or join URLs. Use `join_url` to define the URL that clients use to join the Call.
//
// Updates information about a Call.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `calls:write`
//	id: `id` returned by the `calls.add` method.
//	title: The name of the Call.
//	joinUrl: The URL required for a client to join the Call.
//	desktopAppJoinUrl: When supplied, available Slack clients will attempt to
//	directly launch the 3rd-party Call with this URL.
func (sdk *CallsNamespace) Update(ctx context.Context, token string, id string, title *string, joinUrl *string, desktopAppJoinUrl *string) (map[string]interface{}, error) {
	return CallsUpdate(ctx, sdk.config, token, id, title, joinUrl, desktopAppJoinUrl)
}

type CallsParticipantsNamespace struct {
	config ClientConfig
}

func NewCallsParticipantsNamespace(config ClientConfig) *CallsParticipantsNamespace {
	return &CallsParticipantsNamespace{
		config: config,
	}
}
