// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

// IntegrationLogs lists integration logs for the current team. Use the filter parameters to restrict results by app, change type, service, or user, and use `count` and `page` for pagination. The response contains matching log records and paging metadata.
//
// Gets the integration logs for the current team.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin`
//	appId: Filter logs to this Slack app. Defaults to all logs.
//	changeType: Filter logs with this change type. Defaults to all logs.
//	serviceId: Filter logs to this service. Defaults to all logs.
//	user: Filter logs generated by this user’s actions. Defaults to all logs.
func (sdk *TeamNamespace) IntegrationLogs(ctx context.Context, token string, appId *string, changeType *string, count *string, page *string, serviceId *string, user *string) (*TeamIntegrationLogsResponse, error) {
	return TeamIntegrationLogs(ctx, sdk.config, token, appId, changeType, count, page, serviceId, user)
}

type TeamProfileNamespace struct {
	config ClientConfig
}

func NewTeamProfileNamespace(config ClientConfig) *TeamProfileNamespace {
	return &TeamProfileNamespace{
		config: config,
	}
}

// Get retrieves the team's profile and its configured custom fields. Use `visibility` to filter which profile fields are returned. The response contains the profile's `fields` collection.
//
// Retrieve a team's profile.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `users.profile:read`
//	visibility: Filter by visibility.
func (sdk *TeamProfileNamespace) Get(ctx context.Context, token string, visibility *string) (*TeamProfileGetResponse, error) {
	return TeamProfileGet(ctx, sdk.config, token, visibility)
}

type UsergroupsNamespace struct {
	config ClientConfig
}

func NewUsergroupsNamespace(config ClientConfig) *UsergroupsNamespace {
	return &UsergroupsNamespace{
		config: config,
	}
}

// Create creates a User Group for the current team. Supply a unique `name`, and optionally configure its mention `handle`, description, default channels, and user count behavior. The response returns the created User Group with its generated identity and configuration.
//
// # Create a User Group
//
// Parameters:
//
//	token: Authentication token. Requires scope: `usergroups:write`
//	name: A name for the User Group. Must be unique among User Groups.
//	channels: A comma separated string of encoded channel IDs for which the User
//	Group uses as a default.
//	description: A short description of the User Group.
//	handle: A mention handle. Must be unique among channels, users and User
//	Groups.
//	includeCount: Include the number of users in each User Group.
func (sdk *UsergroupsNamespace) Create(ctx context.Context, token string, name string, channels *string, description *string, handle *string, includeCount *bool) (*UsergroupsCreateResponse, error) {
	return UsergroupsCreate(ctx, sdk.config, token, name, channels, description, handle, includeCount)
}

// Disable disables an existing User Group. Supply the encoded User Group identifier and optionally request the number of users in the returned object. The response returns the User Group after it has been disabled.
//
// # Disable an existing User Group
//
// Parameters:
//
//	token: Authentication token. Requires scope: `usergroups:write`
//	usergroup: The encoded ID of the User Group to disable.
//	includeCount: Include the number of users in the User Group.
func (sdk *UsergroupsNamespace) Disable(ctx context.Context, token string, usergroup string, includeCount *bool) (*UsergroupsDisableResponse, error) {
	return UsergroupsDisable(ctx, sdk.config, token, usergroup, includeCount)
}

// Enable enables a disabled User Group for the team. Supply the User Group's encoded ID in `usergroup` and optionally request its member count with `include_count`.
//
// # Enable a User Group
//
// Parameters:
//
//	token: Authentication token. Requires scope: `usergroups:write`
//	usergroup: The encoded ID of the User Group to enable.
//	includeCount: Include the number of users in the User Group.
func (sdk *UsergroupsNamespace) Enable(ctx context.Context, token string, usergroup string, includeCount *bool) (*UsergroupsEnableResponse, error) {
	return UsergroupsEnable(ctx, sdk.config, token, usergroup, includeCount)
}

// List lists the User Groups available for a team. Use the inclusion flags to return member lists, member counts, or disabled User Groups alongside the default User Group details.
//
// # List all User Groups for a team
//
// Parameters:
//
//	token: Authentication token. Requires scope: `usergroups:read`
//	includeUsers: Include the list of users for each User Group.
//	includeCount: Include the number of users in each User Group.
//	includeDisabled: Include disabled User Groups.
func (sdk *UsergroupsNamespace) List(ctx context.Context, token string, includeUsers *bool, includeCount *bool, includeDisabled *bool) (*UsergroupsListResponse, error) {
	return UsergroupsList(ctx, sdk.config, token, includeUsers, includeCount, includeDisabled)
}

// Update updates an existing User Group's name, handle, description, default channels, or member count setting. Supply `usergroup` to identify the group, then include only the properties you want to change.
//
// # Update an existing User Group
//
// Parameters:
//
//	token: Authentication token. Requires scope: `usergroups:write`
//	usergroup: The encoded ID of the User Group to update.
//	handle: A mention handle. Must be unique among channels, users and User
//	Groups.
//	description: A short description of the User Group.
//	channels: A comma separated string of encoded channel IDs for which the User
//	Group uses as a default.
//	includeCount: Include the number of users in the User Group.
//	name: A name for the User Group. Must be unique among User Groups.
func (sdk *UsergroupsNamespace) Update(ctx context.Context, token string, usergroup string, handle *string, description *string, channels *string, includeCount *bool, name *string) (*UsergroupsUpdateResponse, error) {
	return UsergroupsUpdate(ctx, sdk.config, token, usergroup, handle, description, channels, includeCount, name)
}

type UsergroupsUsersNamespace struct {
	config ClientConfig
}

func NewUsergroupsUsersNamespace(config ClientConfig) *UsergroupsUsersNamespace {
	return &UsergroupsUsersNamespace{
		config: config,
	}
}

// List lists the users who belong to a specified User Group. Supply `usergroup` to select the group and use `include_disabled` when results may involve disabled User Groups.
//
// # List all users in a User Group
//
// Parameters:
//
//	token: Authentication token. Requires scope: `usergroups:read`
//	usergroup: The encoded ID of the User Group to update.
//	includeDisabled: Allow results that involve disabled User Groups.
func (sdk *UsergroupsUsersNamespace) List(ctx context.Context, token string, usergroup string, includeDisabled *bool) (*UsergroupsUsersListResponse, error) {
	return UsergroupsUsersList(ctx, sdk.config, token, usergroup, includeDisabled)
}

// Update replaces the complete membership list for a User Group. Supply `usergroup` and the comma-separated `users` value; the submitted list becomes the group's entire user membership.
//
// # Update the list of users for a User Group
//
// Parameters:
//
//	token: Authentication token. Requires scope: `usergroups:write`
//	usergroup: The encoded ID of the User Group to update.
//	users: A comma separated string of encoded user IDs that represent the
//	entire list of users for the User Group.
//	includeCount: Include the number of users in the User Group.
func (sdk *UsergroupsUsersNamespace) Update(ctx context.Context, token string, usergroup string, users string, includeCount *bool) (*UsergroupsUsersUpdateResponse, error) {
	return UsergroupsUsersUpdate(ctx, sdk.config, token, usergroup, users, includeCount)
}

type UsersNamespace struct {
	config ClientConfig
}

func NewUsersNamespace(config ClientConfig) *UsersNamespace {
	return &UsersNamespace{
		config: config,
	}
}

// Conversations lists the conversations that the authenticated user may access. Filter by conversation types, user membership, and archived status, and use `cursor` to retrieve successive pages of results.
//
// List conversations the calling user may access.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:read`
//	user: Browse conversations by a specific user ID's membership. Non-public
//	channels are restricted to those where the calling user shares membership.
//	types: Mix and match channel types by providing a comma-separated list of
//	any combination of `public_channel`, `private_channel`, `mpim`, `im`
//	excludeArchived: Set to `true` to exclude archived channels from the list
//	limit: The maximum number of items to return. Fewer than the requested
//	number of items may be returned, even if the end of the list hasn't been
//	reached. Must be an integer no larger than 1000.
//	cursor: Paginate through collections of data by setting the `cursor`
//	parameter to a `next_cursor` attribute returned by a previous request's
//	`response_metadata`. Default value fetches the first "page" of the
//	collection. See pagination for more detail.
func (sdk *UsersNamespace) Conversations(ctx context.Context, token *string, user *string, types *string, excludeArchived *bool, limit *int64, cursor *string) (map[string]interface{}, error) {
	return UsersConversations(ctx, sdk.config, token, user, types, excludeArchived, limit, cursor)
}

// DeletePhoto deletes the profile photo associated with the authenticated user. Send the required authentication token in the form body to authorize removal of the current photo.
//
// # Delete the user profile photo
//
// Parameters:
//
//	token: Authentication token. Requires scope: `users.profile:write`
func (sdk *UsersNamespace) DeletePhoto(ctx context.Context, token string) (*UsersDeletePhotoResponse, error) {
	return UsersDeletePhoto(ctx, sdk.config, token)
}

// GetPresence retrieves presence information for the authenticated user or another specified user. Omit `user` to retrieve the authenticated user's presence, or provide a user ID to inspect another user's current presence.
//
// Gets user presence information.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `users:read`
//	user: User to get presence info on. Defaults to the authed user.
func (sdk *UsersNamespace) GetPresence(ctx context.Context, token string, user *string) (map[string]interface{}, error) {
	return UsersGetPresence(ctx, sdk.config, token, user)
}

// Identity retrieves the authenticated user's identity and team information. Provide a token with the `identity.basic` scope, with additional identity scopes determining whether fields such as email or avatar details are included.
//
// Get a user's identity.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `identity.basic`
func (sdk *UsersNamespace) Identity(ctx context.Context, token *string) ([]interface{}, error) {
	return UsersIdentity(ctx, sdk.config, token)
}

// Info retrieves information about a specified user or, when `user` is omitted, the user associated with the authentication context. Set `include_locale` to include the user's locale in the returned user object.
//
// Gets information about a user.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `users:read`
//	includeLocale: Set this to `true` to receive the locale for this user.
//	Defaults to `false`
//	user: User to get info on
func (sdk *UsersNamespace) Info(ctx context.Context, token string, includeLocale *bool, user *string) (map[string]interface{}, error) {
	return UsersInfo(ctx, sdk.config, token, includeLocale, user)
}

// List lists all users in a Slack team. Use `cursor` to retrieve subsequent pages, `limit` to control the requested page size, and `include_locale` when you need each user's locale.
//
// Lists all users in a Slack team.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `users:read`
//	limit: The maximum number of items to return. Fewer than the requested
//	number of items may be returned, even if the end of the users list hasn't
//	been reached. Providing no `limit` value will result in Slack attempting to
//	deliver you the entire result set. If the collection is too large you may
//	experience `limit_required` or HTTP 500 errors.
//	cursor: Paginate through collections of data by setting the `cursor`
//	parameter to a `next_cursor` attribute returned by a previous request's
//	`response_metadata`. Default value fetches the first "page" of the
//	collection. See pagination for more detail.
//	includeLocale: Set this to `true` to receive the locale for users. Defaults
//	to `false`
func (sdk *UsersNamespace) List(ctx context.Context, token *string, limit *int64, cursor *string, includeLocale *bool) (*UsersListResponse, error) {
	return UsersList(ctx, sdk.config, token, limit, cursor, includeLocale)
}

// LookupByEmail retrieves the Slack user associated with an email address. Supply `email` to identify the user and use a token with the `users:read.email` scope.
//
// Find a user with an email address.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `users:read.email`
//	email: An email address belonging to a user in the workspace
func (sdk *UsersNamespace) LookupByEmail(ctx context.Context, token string, email string) (map[string]interface{}, error) {
	return UsersLookupByEmail(ctx, sdk.config, token, email)
}

// SetActive attempts to mark a user as active, but the operation is deprecated and non-functional. Provide the authentication token required by the legacy method if you call it.
//
// Marked a user as active. Deprecated and non-functional.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `users:write`
func (sdk *UsersNamespace) SetActive(ctx context.Context, token string) (*UsersSetActiveResponse, error) {
	return UsersSetActive(ctx, sdk.config, token)
}

// SetPhoto updates a user's profile photo. Submit the image with optional crop coordinates and dimensions, using the authentication token included in the form.
//
// # Set the user profile photo
//
// Parameters:
//
//	token: Authentication token. Requires scope: `users.profile:write`
//	cropW: Width/height of crop box (always square)
//	cropX: X coordinate of top-left corner of crop box
//	cropY: Y coordinate of top-left corner of crop box
//	image: File contents via `multipart/form-data`.
func (sdk *UsersNamespace) SetPhoto(ctx context.Context, token string, cropW *string, cropX *string, cropY *string, image *string) (*UsersSetPhotoResponse, error) {
	return UsersSetPhoto(ctx, sdk.config, token, cropW, cropX, cropY, image)
}

// SetPresence sets the authenticated user's manual presence state. Provide `presence` as either `auto` or `away` to control how the user's availability is displayed.
//
// Manually sets user presence.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `users:write`
//	presence: Either `auto` or `away`
func (sdk *UsersNamespace) SetPresence(ctx context.Context, token string, presence string) (*UsersSetPresenceResponse, error) {
	return UsersSetPresence(ctx, sdk.config, token, presence)
}

type UsersProfileNamespace struct {
	config ClientConfig
}

func NewUsersProfileNamespace(config ClientConfig) *UsersProfileNamespace {
	return &UsersProfileNamespace{
		config: config,
	}
}

// Get retrieves a user's profile information. Omit `user` to retrieve the authenticated user's profile, or provide a user ID to retrieve another user's profile, and set `include_labels` when custom-field labels are needed.
//
// Retrieves a user's profile information.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `users.profile:read`
//	includeLabels: Include labels for each ID in custom profile fields
//	user: User to retrieve profile info for
func (sdk *UsersProfileNamespace) Get(ctx context.Context, token string, includeLabels *bool, user *string) (*UsersProfileGetResponse, error) {
	return UsersProfileGet(ctx, sdk.config, token, includeLabels, user)
}

// Set updates profile information for the authenticated user or, when permitted, another user. Set one field with `name` and `value`, or submit multiple fields through the URL-encoded JSON in `profile`; an administrator on a paid team can target another user with `user`.
//
// Set the profile information for a user.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `users.profile:write`
//	name: Name of a single key to set. Usable only if `profile` is not passed.
//	profile: Collection of key:value pairs presented as a URL-encoded JSON hash.
//	At most 50 fields may be set. Each field name is limited to 255 characters.
//	user: ID of user to change. This argument may only be specified by team
//	admins on paid teams.
//	value: Value to set a single key to. Usable only if `profile` is not passed.
func (sdk *UsersProfileNamespace) Set(ctx context.Context, token string, name *string, profile *string, user *string, value *string) (*UsersProfileSetResponse, error) {
	return UsersProfileSet(ctx, sdk.config, token, name, profile, user, value)
}

type ViewsNamespace struct {
	config ClientConfig
}

func NewViewsNamespace(config ClientConfig) *ViewsNamespace {
	return &ViewsNamespace{
		config: config,
	}
}

// Open opens a view for a user by exchanging a trigger for the supplied view payload. Pass `view` as a JSON-encoded view string together with the `trigger_id` that authorizes the interaction.
//
// Open a view for a user.
//
// Parameters:
//
//	triggerId: Exchange a trigger to post to the user.
//	view: A view payload. This must be a JSON-encoded string.
//	token: Authentication token. Requires scope: `none`
func (sdk *ViewsNamespace) Open(ctx context.Context, triggerId string, view string, token string) (map[string]interface{}, error) {
	return ViewsOpen(ctx, sdk.config, triggerId, view, token)
}

// Publish publishes a static view for a specified user. Provide the target `user_id` and a JSON-encoded `view`, and optionally pass `hash` to protect against concurrent view changes.
//
// Publish a static view for a User.
//
// Parameters:
//
//	userId: `id` of the user you want publish a view to.
//	view: A view payload. This must be a JSON-encoded string.
//	token: Authentication token. Requires scope: `none`
//	hash: A string that represents view state to protect against possible race
//	conditions.
func (sdk *ViewsNamespace) Publish(ctx context.Context, userId string, view string, token string, hash *string) (map[string]interface{}, error) {
	return ViewsPublish(ctx, sdk.config, userId, view, token, hash)
}

// Push pushes a view onto the stack of a root view for a user. Exchange `trigger_id` and provide the new view as a JSON-encoded payload to add it to the view stack.
//
// Push a view onto the stack of a root view.
//
// Parameters:
//
//	triggerId: Exchange a trigger to post to the user.
//	view: A view payload. This must be a JSON-encoded string.
//	token: Authentication token. Requires scope: `none`
func (sdk *ViewsNamespace) Push(ctx context.Context, triggerId string, view string, token string) (map[string]interface{}, error) {
	return ViewsPush(ctx, sdk.config, triggerId, view, token)
}

// Update updates an existing view identified by its view identifier or developer-defined external identifier. Supply either `view_id` or `external_id`, provide the updated `view` as a JSON-encoded string, and use `hash` to protect against concurrent changes.
//
// Update an existing view.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `none`
//	viewId: A unique identifier of the view to be updated. Either `view_id` or
//	`external_id` is required.
//	externalId: A unique identifier of the view set by the developer. Must be
//	unique for all views on a team. Max length of 255 characters. Either
//	`view_id` or `external_id` is required.
//	view: A view object. This must be a JSON-encoded string.
//	hash: A string that represents view state to protect against possible race
//	conditions.
func (sdk *ViewsNamespace) Update(ctx context.Context, token string, viewId *string, externalId *string, view *string, hash *string) (map[string]interface{}, error) {
	return ViewsUpdate(ctx, sdk.config, token, viewId, externalId, view, hash)
}

type WorkflowsNamespace struct {
	config ClientConfig
}

func NewWorkflowsNamespace(config ClientConfig) *WorkflowsNamespace {
	return &WorkflowsNamespace{
		config: config,
	}
}

// StepCompleted submits the successful completion of an app's workflow step execution. Provide `workflow_step_execute_id` to identify the execution and include `outputs` when the step produces configured output values.
//
// Indicate that an app's step in a workflow completed execution.
//
// Parameters:
//
//	workflowStepExecuteId: Context identifier that maps to the correct workflow
//	step execution.
//	token: Authentication token. Requires scope: `workflow.steps:execute`
//	outputs: Key-value object of outputs from your step. Keys of this object
//	reflect the configured `key` properties of your `outputs` array from your
//	`workflow_step` object.
func (sdk *WorkflowsNamespace) StepCompleted(ctx context.Context, workflowStepExecuteId string, token string, outputs *string) (map[string]interface{}, error) {
	return WorkflowsStepCompleted(ctx, sdk.config, workflowStepExecuteId, token, outputs)
}

// StepFailed submits a failure notification for an app's workflow step execution. Identify the execution with `workflow_step_execute_id` and provide `error` as a JSON-based object containing a human-readable `message` property.
//
// Indicate that an app's step in a workflow failed to execute.
//
// Parameters:
//
//	workflowStepExecuteId: Context identifier that maps to the correct workflow
//	step execution.
//	error_: A JSON-based object with a `message` property that should contain a
//	human readable error message.
//	token: Authentication token. Requires scope: `workflow.steps:execute`
func (sdk *WorkflowsNamespace) StepFailed(ctx context.Context, workflowStepExecuteId string, error_ string, token string) (map[string]interface{}, error) {
	return WorkflowsStepFailed(ctx, sdk.config, workflowStepExecuteId, error_, token)
}

// UpdateStep updates the configuration for a workflow extension step. Use `workflow_step_edit_id` to identify the configuration context, then provide JSON-encoded `inputs` and `outputs` or override the displayed `step_name` and `step_image_url`. Embedded variables in `inputs` are defined and replaced by the workflow system, so you cannot create custom runtime variables.
//
// Update the configuration for a workflow extension step.
//
// Parameters:
//
//	workflowStepEditId: A context identifier provided with `view_submission`
//	payloads used to call back to `workflows.updateStep`.
//	token: Authentication token. Requires scope: `workflow.steps:execute`
//	inputs: A JSON key-value map of inputs required from a user during
//	configuration. This is the data your app expects to receive when the
//	workflow step starts. **Please note**: the embedded variable format is set
//	and replaced by the workflow system. You cannot create custom variables that
//	will be replaced at runtime. Read more about variables in workflow steps
//	here.
//	outputs: An JSON array of output objects used during step execution. This is
//	the data your app agrees to provide when your workflow step was executed.
//	stepName: An optional field that can be used to override the step name that
//	is shown in the Workflow Builder.
//	stepImageUrl: An optional field that can be used to override app image that
//	is shown in the Workflow Builder.
func (sdk *WorkflowsNamespace) UpdateStep(ctx context.Context, workflowStepEditId string, token string, inputs *string, outputs *string, stepName *string, stepImageUrl *string) (map[string]interface{}, error) {
	return WorkflowsUpdateStep(ctx, sdk.config, workflowStepEditId, token, inputs, outputs, stepName, stepImageUrl)
}

type SlackWeb struct {
	AdminApps                        *AdminAppsNamespace
	AdminAppsApproved                *AdminAppsApprovedNamespace
	AdminAppsRequests                *AdminAppsRequestsNamespace
	AdminAppsRestricted              *AdminAppsRestrictedNamespace
	AdminConversations               *AdminConversationsNamespace
	AdminConversationsEkm            *AdminConversationsEkmNamespace
	AdminConversationsRestrictAccess *AdminConversationsRestrictAccessNamespace
	AdminEmoji                       *AdminEmojiNamespace
	AdminInviteRequests              *AdminInviteRequestsNamespace
	AdminInviteRequestsApproved      *AdminInviteRequestsApprovedNamespace
	AdminInviteRequestsDenied        *AdminInviteRequestsDeniedNamespace
	AdminTeamsAdmins                 *AdminTeamsAdminsNamespace
	AdminTeams                       *AdminTeamsNamespace
	AdminTeamsOwners                 *AdminTeamsOwnersNamespace
	AdminTeamsSettings               *AdminTeamsSettingsNamespace
	AdminUsergroups                  *AdminUsergroupsNamespace
	AdminUsers                       *AdminUsersNamespace
	AdminUsersSession                *AdminUsersSessionNamespace
	Api                              *ApiNamespace
	AppsEventAuthorizations          *AppsEventAuthorizationsNamespace
	AppsPermissions                  *AppsPermissionsNamespace
	AppsPermissionsResources         *AppsPermissionsResourcesNamespace
	AppsPermissionsScopes            *AppsPermissionsScopesNamespace
	AppsPermissionsUsers             *AppsPermissionsUsersNamespace
	Apps                             *AppsNamespace
	Auth                             *AuthNamespace
	Bots                             *BotsNamespace
	Calls                            *CallsNamespace
	CallsParticipants                *CallsParticipantsNamespace
	Chat                             *ChatNamespace
	ChatScheduledMessages            *ChatScheduledMessagesNamespace
	Conversations                    *ConversationsNamespace
	Dialog                           *DialogNamespace
	Dnd                              *DndNamespace
	Emoji                            *EmojiNamespace
	FilesComments                    *FilesCommentsNamespace
	Files                            *FilesNamespace
	FilesRemote                      *FilesRemoteNamespace
	Migration                        *MigrationNamespace
	Oauth                            *OauthNamespace
	OauthV2                          *OauthV2Namespace
	Pins                             *PinsNamespace
	Reactions                        *ReactionsNamespace
	Reminders                        *RemindersNamespace
	Rtm                              *RtmNamespace
	Search                           *SearchNamespace
	Stars                            *StarsNamespace
	Team                             *TeamNamespace
	TeamProfile                      *TeamProfileNamespace
	Usergroups                       *UsergroupsNamespace
	UsergroupsUsers                  *UsergroupsUsersNamespace
	Users                            *UsersNamespace
	UsersProfile                     *UsersProfileNamespace
	Views                            *ViewsNamespace
	Workflows                        *WorkflowsNamespace
}

func NewSlackWeb(config ClientConfig) *SlackWeb {
	return &SlackWeb{
		AdminApps:                        NewAdminAppsNamespace(config),
		AdminAppsApproved:                NewAdminAppsApprovedNamespace(config),
		AdminAppsRequests:                NewAdminAppsRequestsNamespace(config),
		AdminAppsRestricted:              NewAdminAppsRestrictedNamespace(config),
		AdminConversations:               NewAdminConversationsNamespace(config),
		AdminConversationsEkm:            NewAdminConversationsEkmNamespace(config),
		AdminConversationsRestrictAccess: NewAdminConversationsRestrictAccessNamespace(config),
		AdminEmoji:                       NewAdminEmojiNamespace(config),
		AdminInviteRequests:              NewAdminInviteRequestsNamespace(config),
		AdminInviteRequestsApproved:      NewAdminInviteRequestsApprovedNamespace(config),
		AdminInviteRequestsDenied:        NewAdminInviteRequestsDeniedNamespace(config),
		AdminTeamsAdmins:                 NewAdminTeamsAdminsNamespace(config),
		AdminTeams:                       NewAdminTeamsNamespace(config),
		AdminTeamsOwners:                 NewAdminTeamsOwnersNamespace(config),
		AdminTeamsSettings:               NewAdminTeamsSettingsNamespace(config),
		AdminUsergroups:                  NewAdminUsergroupsNamespace(config),
		AdminUsers:                       NewAdminUsersNamespace(config),
		AdminUsersSession:                NewAdminUsersSessionNamespace(config),
		Api:                              NewApiNamespace(config),
		AppsEventAuthorizations:          NewAppsEventAuthorizationsNamespace(config),
		AppsPermissions:                  NewAppsPermissionsNamespace(config),
		AppsPermissionsResources:         NewAppsPermissionsResourcesNamespace(config),
		AppsPermissionsScopes:            NewAppsPermissionsScopesNamespace(config),
		AppsPermissionsUsers:             NewAppsPermissionsUsersNamespace(config),
		Apps:                             NewAppsNamespace(config),
		Auth:                             NewAuthNamespace(config),
		Bots:                             NewBotsNamespace(config),
		Calls:                            NewCallsNamespace(config),
		CallsParticipants:                NewCallsParticipantsNamespace(config),
		Chat:                             NewChatNamespace(config),
		ChatScheduledMessages:            NewChatScheduledMessagesNamespace(config),
		Conversations:                    NewConversationsNamespace(config),
		Dialog:                           NewDialogNamespace(config),
		Dnd:                              NewDndNamespace(config),
		Emoji:                            NewEmojiNamespace(config),
		FilesComments:                    NewFilesCommentsNamespace(config),
		Files:                            NewFilesNamespace(config),
		FilesRemote:                      NewFilesRemoteNamespace(config),
		Migration:                        NewMigrationNamespace(config),
		Oauth:                            NewOauthNamespace(config),
		OauthV2:                          NewOauthV2Namespace(config),
		Pins:                             NewPinsNamespace(config),
		Reactions:                        NewReactionsNamespace(config),
		Reminders:                        NewRemindersNamespace(config),
		Rtm:                              NewRtmNamespace(config),
		Search:                           NewSearchNamespace(config),
		Stars:                            NewStarsNamespace(config),
		Team:                             NewTeamNamespace(config),
		TeamProfile:                      NewTeamProfileNamespace(config),
		Usergroups:                       NewUsergroupsNamespace(config),
		UsergroupsUsers:                  NewUsergroupsUsersNamespace(config),
		Users:                            NewUsersNamespace(config),
		UsersProfile:                     NewUsersProfileNamespace(config),
		Views:                            NewViewsNamespace(config),
		Workflows:                        NewWorkflowsNamespace(config),
	}
}
