// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

// Add adds new participants to an existing Call. Supply the Call `id` returned by calls.add and the `users` value describing the users to add. Use this method after creating a Call when you need to register additional participants.
//
// Registers new participants added to a Call.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `calls:write`
//	id: `id` returned by the `calls.add` method.
//	users: The list of users to add as participants in the Call. Read more on
//	how to specify users here.
func (sdk *CallsParticipantsNamespace) Add(ctx context.Context, token string, id string, users string) (map[string]interface{}, error) {
	return CallsParticipantsAdd(ctx, sdk.config, token, id, users)
}

// Remove removes participants from an existing Call. Supply the Call `id` returned by calls.add and the `users` value identifying the participants to remove. Use this method when participants no longer need access to the Call.
//
// Registers participants removed from a Call.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `calls:write`
//	id: `id` returned by the `calls.add` method.
//	users: The list of users to remove as participants in the Call. Read more on
//	how to specify users here.
func (sdk *CallsParticipantsNamespace) Remove(ctx context.Context, token string, id string, users string) (map[string]interface{}, error) {
	return CallsParticipantsRemove(ctx, sdk.config, token, id, users)
}

type ChatNamespace struct {
	config ClientConfig
}

func NewChatNamespace(config ClientConfig) *ChatNamespace {
	return &ChatNamespace{
		config: config,
	}
}

// Delete deletes a message from a channel. Supply `ts` and `channel` to identify the message, and use `as_user` to control whether deletion occurs as the authenticated user or with bot scope. Use this method only when the authenticated user or bot has permission to delete the specified message.
//
// Deletes a message.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `chat:write`
//	ts: Timestamp of the message to be deleted.
//	channel: Channel containing the message to be deleted.
//	asUser: Pass true to delete the message as the authed user with
//	`chat:write:user` scope. Bot users in this context are considered authed
//	users. If unused or false, the message will be deleted with `chat:write:bot`
//	scope.
func (sdk *ChatNamespace) Delete(ctx context.Context, token *string, ts *float64, channel *string, asUser *bool) (*ChatDeleteResponse, error) {
	return ChatDelete(ctx, sdk.config, token, ts, channel, asUser)
}

// DeleteScheduledMessage deletes a pending scheduled message from the message queue. Supply `channel` and the `scheduled_message_id` returned by chat.scheduleMessage to identify the queued message. Use `as_user` when the deletion must be performed as the authenticated user rather than with bot scope.
//
// Deletes a pending scheduled message from the queue.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `chat:write`
//	channel: The channel the scheduled_message is posting to
//	scheduledMessageId: `scheduled_message_id` returned from call to
//	chat.scheduleMessage
//	asUser: Pass true to delete the message as the authed user with
//	`chat:write:user` scope. Bot users in this context are considered authed
//	users. If unused or false, the message will be deleted with `chat:write:bot`
//	scope.
func (sdk *ChatNamespace) DeleteScheduledMessage(ctx context.Context, token string, channel string, scheduledMessageId string, asUser *bool) (*ChatDeleteScheduledMessageResponse, error) {
	return ChatDeleteScheduledMessage(ctx, sdk.config, token, channel, scheduledMessageId, asUser)
}

// GetPermalink retrieves a permalink for a specific message in a conversation or channel. Supply `channel` and the message's `message_ts` value to identify the message, together with the authentication `token`. Use the returned URI to link directly to that message.
//
// # Retrieve a permalink URL for a specific extant message
//
// Parameters:
//
//	token: Authentication token. Requires scope: `none`
//	channel: The ID of the conversation or channel containing the message
//	messageTs: A message's `ts` value, uniquely identifying it within a channel
func (sdk *ChatNamespace) GetPermalink(ctx context.Context, token string, channel string, messageTs string) (*ChatGetPermalinkResponse, error) {
	return ChatGetPermalink(ctx, sdk.config, token, channel, messageTs)
}

// MeMessage sends a me message to a channel, private group, or direct message channel. Supply `channel` and `text` to identify the destination and message content, and use `thread_ts` to post within an existing thread. Use `as_user`, `icon_emoji`, `icon_url`, or `username` to control the message authorship and appearance when permitted.
//
// Share a me message into a channel.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `chat:write`
//	channel: Channel to send message to. Can be a public channel, private group
//	or IM channel. Can be an encoded ID, or a name.
//	text: Text of the message to send.
func (sdk *ChatNamespace) MeMessage(ctx context.Context, token *string, channel *string, text *string) (*ChatMeMessageResponse, error) {
	return ChatMeMessage(ctx, sdk.config, token, channel, text)
}

// PostEphemeral sends an ephemeral message that is visible only to one user in a channel. Supply `channel` and `user` to identify the destination, and provide message content through `text`, `blocks`, or `attachments`. Use `thread_ts` to display the ephemeral message in an existing active thread.
//
// Sends an ephemeral message to a user in a channel.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `chat:write`
//	channel: Channel, private group, or IM channel to send message to. Can be an
//	encoded ID, or a name.
//	user: `id` of the user who will receive the ephemeral message. The user
//	should be in the channel specified by the `channel` argument.
//	asUser: Pass true to post the message as the authed user. Defaults to true
//	if the chat:write:bot scope is not included. Otherwise, defaults to false.
//	attachments: A JSON-based array of structured attachments, presented as a
//	URL-encoded string.
//	blocks: A JSON-based array of structured blocks, presented as a URL-encoded
//	string.
//	iconEmoji: Emoji to use as the icon for this message. Overrides `icon_url`.
//	Must be used in conjunction with `as_user` set to `false`, otherwise
//	ignored. See authorship below.
//	iconUrl: URL to an image to use as the icon for this message. Must be used
//	in conjunction with `as_user` set to false, otherwise ignored. See
//	authorship below.
//	linkNames: Find and link channel names and usernames.
//	parse: Change how messages are treated. Defaults to `none`. See below.
//	text: How this field works and whether it is required depends on other
//	fields you use in your API call. See below for more detail.
//	threadTs: Provide another message's `ts` value to post this message in a
//	thread. Avoid using a reply's `ts` value; use its parent's value instead.
//	Ephemeral messages in threads are only shown if there is already an active
//	thread.
//	username: Set your bot's user name. Must be used in conjunction with
//	`as_user` set to false, otherwise ignored. See authorship below.
func (sdk *ChatNamespace) PostEphemeral(ctx context.Context, token string, channel string, user string, asUser *bool, attachments *string, blocks *string, iconEmoji *string, iconUrl *string, linkNames *bool, parse *string, text *string, threadTs *string, username *string) (*ChatPostEphemeralResponse, error) {
	return ChatPostEphemeral(ctx, sdk.config, token, channel, user, asUser, attachments, blocks, iconEmoji, iconUrl, linkNames, parse, text, threadTs, username)
}

// PostMessage sends a message to a channel, private group, or direct message channel. Supply `channel` and message content through `text`, `blocks`, or `attachments`, and use `thread_ts` when replying to an existing message. Use the authorship and unfurling options to control how the message is presented.
//
// Sends a message to a channel.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `chat:write`
//	channel: Channel, private group, or IM channel to send message to. Can be an
//	encoded ID, or a name. See below for more details.
//	asUser: Pass true to post the message as the authed user, instead of as a
//	bot. Defaults to false. See authorship below.
//	attachments: A JSON-based array of structured attachments, presented as a
//	URL-encoded string.
//	blocks: A JSON-based array of structured blocks, presented as a URL-encoded
//	string.
//	iconEmoji: Emoji to use as the icon for this message. Overrides `icon_url`.
//	Must be used in conjunction with `as_user` set to `false`, otherwise
//	ignored. See authorship below.
//	iconUrl: URL to an image to use as the icon for this message. Must be used
//	in conjunction with `as_user` set to false, otherwise ignored. See
//	authorship below.
//	linkNames: Find and link channel names and usernames.
//	mrkdwn: Disable Slack markup parsing by setting to `false`. Enabled by
//	default.
//	parse: Change how messages are treated. Defaults to `none`. See below.
//	replyBroadcast: Used in conjunction with `thread_ts` and indicates whether
//	reply should be made visible to everyone in the channel or conversation.
//	Defaults to `false`.
//	text: How this field works and whether it is required depends on other
//	fields you use in your API call. See below for more detail.
//	threadTs: Provide another message's `ts` value to make this message a reply.
//	Avoid using a reply's `ts` value; use its parent instead.
//	unfurlLinks: Pass true to enable unfurling of primarily text-based content.
//	unfurlMedia: Pass false to disable unfurling of media content.
//	username: Set your bot's user name. Must be used in conjunction with
//	`as_user` set to false, otherwise ignored. See authorship below.
func (sdk *ChatNamespace) PostMessage(ctx context.Context, token string, channel string, asUser *string, attachments *string, blocks *string, iconEmoji *string, iconUrl *string, linkNames *bool, mrkdwn *bool, parse *string, replyBroadcast *bool, text *string, threadTs *string, unfurlLinks *bool, unfurlMedia *bool, username *string) (*ChatPostMessageResponse, error) {
	return ChatPostMessage(ctx, sdk.config, token, channel, asUser, attachments, blocks, iconEmoji, iconUrl, linkNames, mrkdwn, parse, replyBroadcast, text, threadTs, unfurlLinks, unfurlMedia, username)
}

// ScheduleMessage schedules a message to be sent to a channel at a future time. Provide `channel` and `post_at`, then use `text`, `blocks`, or `attachments` to define the message content. A successful response includes the scheduled message identifier and scheduled timestamp.
//
// Schedules a message to be sent to a channel.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `chat:write`
//	channel: Channel, private group, or DM channel to send message to. Can be an
//	encoded ID, or a name. See below for more details.
//	text: How this field works and whether it is required depends on other
//	fields you use in your API call. See below for more detail.
//	postAt: Unix EPOCH timestamp of time in future to send the message.
//	parse: Change how messages are treated. Defaults to `none`. See
//	[chat.postMessage](chat.postMessage#formatting).
//	asUser: Pass true to post the message as the authed user, instead of as a
//	bot. Defaults to false. See [chat.postMessage](chat.postMessage#authorship).
//	linkNames: Find and link channel names and usernames.
//	attachments: A JSON-based array of structured attachments, presented as a
//	URL-encoded string.
//	blocks: A JSON-based array of structured blocks, presented as a URL-encoded
//	string.
//	unfurlLinks: Pass true to enable unfurling of primarily text-based content.
//	unfurlMedia: Pass false to disable unfurling of media content.
//	threadTs: Provide another message's `ts` value to make this message a reply.
//	Avoid using a reply's `ts` value; use its parent instead.
//	replyBroadcast: Used in conjunction with `thread_ts` and indicates whether
//	reply should be made visible to everyone in the channel or conversation.
//	Defaults to `false`.
func (sdk *ChatNamespace) ScheduleMessage(ctx context.Context, token *string, channel *string, text *string, postAt *string, parse *string, asUser *bool, linkNames *bool, attachments *string, blocks *string, unfurlLinks *bool, unfurlMedia *bool, threadTs *float64, replyBroadcast *bool) (*ChatScheduleMessageResponse, error) {
	return ChatScheduleMessage(ctx, sdk.config, token, channel, text, postAt, parse, asUser, linkNames, attachments, blocks, unfurlLinks, unfurlMedia, threadTs, replyBroadcast)
}

// Unfurl submits custom unfurl behavior for URLs in a user-posted message. Supply the target `channel` and message `ts`, then provide URL mappings through `unfurls` or authentication guidance through the user-authentication fields. The request requires an authentication token with the `links:write` scope.
//
// # Provide custom unfurl behavior for user-posted URLs
//
// Parameters:
//
//	token: Authentication token. Requires scope: `links:write`
//	channel: Channel ID of the message
//	ts: Timestamp of the message to add unfurl behavior to.
//	unfurls: URL-encoded JSON map with keys set to URLs featured in the the
//	message, pointing to their unfurl blocks or message attachments.
//	userAuthMessage: Provide a simply-formatted string to send as an ephemeral
//	message to the user as invitation to authenticate further and enable full
//	unfurling behavior
//	userAuthRequired: Set to `true` or `1` to indicate the user must install
//	your Slack app to trigger unfurls for this domain
//	userAuthUrl: Send users to this custom URL where they will complete
//	authentication in your app to fully trigger unfurling. Value should be
//	properly URL-encoded.
func (sdk *ChatNamespace) Unfurl(ctx context.Context, token string, channel string, ts string, unfurls *string, userAuthMessage *string, userAuthRequired *bool, userAuthUrl *string) (*ChatUnfurlResponse, error) {
	return ChatUnfurl(ctx, sdk.config, token, channel, ts, unfurls, userAuthMessage, userAuthRequired, userAuthUrl)
}

// Update updates an existing message in a channel. Supply `channel` and `ts`, then change the message text or provide new `blocks` or `attachments`; omitted content fields retain their existing values unless the request explicitly replaces them. Use `parse` and `link_names` to control message formatting and linking.
//
// Updates a message.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `chat:write`
//	channel: Channel containing the message to be updated.
//	ts: Timestamp of the message to be updated.
//	asUser: Pass true to update the message as the authed user. Bot users in
//	this context are considered authed users.
//	attachments: A JSON-based array of structured attachments, presented as a
//	URL-encoded string. This field is required when not presenting `text`. If
//	you don't include this field, the message's previous `attachments` will be
//	retained. To remove previous `attachments`, include an empty array for this
//	field.
//	blocks: A JSON-based array of structured blocks, presented as a URL-encoded
//	string. If you don't include this field, the message's previous `blocks`
//	will be retained. To remove previous `blocks`, include an empty array for
//	this field.
//	linkNames: Find and link channel names and usernames. Defaults to `none`. If
//	you do not specify a value for this field, the original value set for the
//	message will be overwritten with the default, `none`.
//	parse: Change how messages are treated. Defaults to `client`, unlike
//	`chat.postMessage`. Accepts either `none` or `full`. If you do not specify a
//	value for this field, the original value set for the message will be
//	overwritten with the default, `client`.
//	text: New text for the message, using the default formatting rules. It's not
//	required when presenting `blocks` or `attachments`.
func (sdk *ChatNamespace) Update(ctx context.Context, token string, channel string, ts string, asUser *string, attachments *string, blocks *string, linkNames *string, parse *string, text *string) (*ChatUpdateResponse, error) {
	return ChatUpdate(ctx, sdk.config, token, channel, ts, asUser, attachments, blocks, linkNames, parse, text)
}

type ChatScheduledMessagesNamespace struct {
	config ClientConfig
}

func NewChatScheduledMessagesNamespace(config ClientConfig) *ChatScheduledMessagesNamespace {
	return &ChatScheduledMessagesNamespace{
		config: config,
	}
}

// List lists messages that are scheduled for delivery. Use `channel`, `latest`, and `oldest` to limit the results, and use `cursor` to continue from a previous page. The response includes scheduled message records and pagination metadata.
//
// Returns a list of scheduled messages.
//
// Parameters:
//
//	channel: The channel of the scheduled messages
//	latest: A UNIX timestamp of the latest value in the time range
//	oldest: A UNIX timestamp of the oldest value in the time range
//	limit: Maximum number of original entries to return.
//	cursor: For pagination purposes, this is the `cursor` value returned from a
//	previous call to `chat.scheduledmessages.list` indicating where you want to
//	start this call from.
//	token: Authentication token. Requires scope: `none`
func (sdk *ChatScheduledMessagesNamespace) List(ctx context.Context, channel *string, latest *float64, oldest *float64, limit *int64, cursor *string, token *string) (*ChatScheduledMessagesListResponse, error) {
	return ChatScheduledMessagesList(ctx, sdk.config, channel, latest, oldest, limit, cursor, token)
}

type ConversationsNamespace struct {
	config ClientConfig
}

func NewConversationsNamespace(config ClientConfig) *ConversationsNamespace {
	return &ConversationsNamespace{
		config: config,
	}
}

// Archive archives a conversation so it is no longer active. Provide the conversation `channel` identifier for the conversation you want to archive. The operation returns a success confirmation when the archive is applied.
//
// Archives a conversation.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:write`
//	channel: ID of conversation to archive
func (sdk *ConversationsNamespace) Archive(ctx context.Context, token *string, channel *string) (*ConversationsArchiveResponse, error) {
	return ConversationsArchive(ctx, sdk.config, token, channel)
}

// Close closes a direct message or multiperson direct message conversation. Provide the conversation `channel` identifier to close it. The response indicates whether the conversation was already closed or the operation was a no-op.
//
// Closes a direct message or multi-person direct message.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:write`
//	channel: Conversation to close.
func (sdk *ConversationsNamespace) Close(ctx context.Context, token *string, channel *string) (*ConversationsCloseResponse, error) {
	return ConversationsClose(ctx, sdk.config, token, channel)
}

// Create creates a public or private channel-based conversation. Provide `name` for the channel name and set `is_private` to `true` when the conversation should be private. The response contains the created conversation object.
//
// # Initiates a public or private channel-based conversation
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:write`
//	name: Name of the public or private channel to create
//	isPrivate: Create a private channel instead of a public one
func (sdk *ConversationsNamespace) Create(ctx context.Context, token *string, name *string, isPrivate *bool) (*ConversationsCreateResponse, error) {
	return ConversationsCreate(ctx, sdk.config, token, name, isPrivate)
}

// History lists messages and events from a conversation's history. Use `latest` and `oldest` to define a time range, `inclusive` to include boundary timestamps, and `cursor` to paginate through results. The response includes messages, pagination state, and channel action metadata.
//
// Fetches a conversation's history of messages and events.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:history`
//	channel: Conversation ID to fetch history for.
//	latest: End of time range of messages to include in results.
//	oldest: Start of time range of messages to include in results.
//	inclusive: Include messages with latest or oldest timestamp in results only
//	when either timestamp is specified.
//	limit: The maximum number of items to return. Fewer than the requested
//	number of items may be returned, even if the end of the users list hasn't
//	been reached.
//	cursor: Paginate through collections of data by setting the `cursor`
//	parameter to a `next_cursor` attribute returned by a previous request's
//	`response_metadata`. Default value fetches the first "page" of the
//	collection. See pagination for more detail.
func (sdk *ConversationsNamespace) History(ctx context.Context, token *string, channel *string, latest *float64, oldest *float64, inclusive *bool, limit *int64, cursor *string) (*ConversationsHistoryResponse, error) {
	return ConversationsHistory(ctx, sdk.config, token, channel, latest, oldest, inclusive, limit, cursor)
}

// Info retrieves information about a conversation. Provide the conversation `channel` identifier and optionally request its locale or member count with `include_locale` and `include_num_members`. The response contains the conversation object.
//
// Retrieve information about a conversation.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:read`
//	channel: Conversation ID to learn more about
//	includeLocale: Set this to `true` to receive the locale for this
//	conversation. Defaults to `false`
//	includeNumMembers: Set to `true` to include the member count for the
//	specified conversation. Defaults to `false`
func (sdk *ConversationsNamespace) Info(ctx context.Context, token *string, channel *string, includeLocale *bool, includeNumMembers *bool) (*ConversationsInfoResponse, error) {
	return ConversationsInfo(ctx, sdk.config, token, channel, includeLocale, includeNumMembers)
}

// Invite invites one or more users to a public or private channel. Provide the destination `channel` and a comma-separated `users` list containing the users to invite. The response contains the updated conversation object after the invitation is processed.
//
// Invites users to a channel.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:write`
//	channel: The ID of the public or private channel to invite user(s) to.
//	users: A comma separated list of user IDs. Up to 1000 users may be listed.
func (sdk *ConversationsNamespace) Invite(ctx context.Context, token *string, channel *string, users *string) (*ConversationsInviteResponse, error) {
	return ConversationsInvite(ctx, sdk.config, token, channel, users)
}

// Join joins an existing conversation for the authenticated user. Supply the conversation identifier in `channel` and use an authentication token with the `channels:write` scope when authorization is required.
//
// Joins an existing conversation.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `channels:write`
//	channel: ID of conversation to join
func (sdk *ConversationsNamespace) Join(ctx context.Context, token *string, channel *string) (*ConversationsJoinResponse, error) {
	return ConversationsJoin(ctx, sdk.config, token, channel)
}

// Kick removes a user from an existing conversation. Provide the conversation in `channel` and the user to remove in `user`, using an authentication token with the `conversations:write` scope when authorization is required.
//
// Removes a user from a conversation.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:write`
//	channel: ID of conversation to remove user from.
//	user: User ID to be removed.
func (sdk *ConversationsNamespace) Kick(ctx context.Context, token *string, channel *string, user *string) (*ConversationsKickResponse, error) {
	return ConversationsKick(ctx, sdk.config, token, channel, user)
}

// Leave leaves an existing conversation for the authenticated user. Supply the conversation identifier in `channel` to specify which conversation to leave, using an authentication token with the `conversations:write` scope when authorization is required.
//
// Leaves a conversation.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:write`
//	channel: Conversation to leave
func (sdk *ConversationsNamespace) Leave(ctx context.Context, token *string, channel *string) (*ConversationsLeaveResponse, error) {
	return ConversationsLeave(ctx, sdk.config, token, channel)
}

// List lists conversations in a Slack team, optionally filtering by archive state and conversation type. Use `types` to select public, private, multi-person direct, or direct conversations, and use `cursor` to retrieve subsequent pages.
//
// Lists all channels in a Slack team.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:read`
//	excludeArchived: Set to `true` to exclude archived channels from the list
//	types: Mix and match channel types by providing a comma-separated list of
//	any combination of `public_channel`, `private_channel`, `mpim`, `im`
//	limit: The maximum number of items to return. Fewer than the requested
//	number of items may be returned, even if the end of the list hasn't been
//	reached. Must be an integer no larger than 1000.
//	cursor: Paginate through collections of data by setting the `cursor`
//	parameter to a `next_cursor` attribute returned by a previous request's
//	`response_metadata`. Default value fetches the first "page" of the
//	collection. See pagination for more detail.
func (sdk *ConversationsNamespace) List(ctx context.Context, token *string, excludeArchived *bool, types *string, limit *int64, cursor *string) (*ConversationsListResponse, error) {
	return ConversationsList(ctx, sdk.config, token, excludeArchived, types, limit, cursor)
}

// Mark sets the authenticated user's read cursor in a conversation. Provide the conversation in `channel` and the timestamp of the most recently seen message in `ts`, using an authentication token with the `conversations:write` scope when authorization is required.
//
// Sets the read cursor in a channel.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:write`
//	channel: Channel or conversation to set the read cursor for.
//	ts: Unique identifier of message you want marked as most recently seen in
//	this conversation.
func (sdk *ConversationsNamespace) Mark(ctx context.Context, token *string, channel *string, ts *float64) (*ConversationsMarkResponse, error) {
	return ConversationsMark(ctx, sdk.config, token, channel, ts)
}

// Members lists the members of an existing conversation. Use `limit` and `cursor` to page through the member list, and authenticate with a token that has the `conversations:read` scope when authorization is required.
//
// Retrieve members of a conversation.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:read`
//	channel: ID of the conversation to retrieve members for
//	limit: The maximum number of items to return. Fewer than the requested
//	number of items may be returned, even if the end of the users list hasn't
//	been reached.
//	cursor: Paginate through collections of data by setting the `cursor`
//	parameter to a `next_cursor` attribute returned by a previous request's
//	`response_metadata`. Default value fetches the first "page" of the
//	collection. See pagination for more detail.
func (sdk *ConversationsNamespace) Members(ctx context.Context, token *string, channel *string, limit *int64, cursor *string) (*ConversationsMembersResponse, error) {
	return ConversationsMembers(ctx, sdk.config, token, channel, limit, cursor)
}

// Open opens or resumes a direct message or multi-person direct message. Supply an existing direct conversation in `channel`, or provide one or more user IDs in `users`; use `return_im` when the full direct-message channel definition is needed in the response.
//
// Opens or resumes a direct message or multi-person direct message.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:write`
//	channel: Resume a conversation by supplying an `im` or `mpim`'s ID. Or
//	provide the `users` field instead.
//	users: Comma separated lists of users. If only one user is included, this
//	creates a 1:1 DM. The ordering of the users is preserved whenever a
//	multi-person direct message is returned. Supply a `channel` when not
//	supplying `users`.
//	returnIm: Boolean, indicates you want the full IM channel definition in the
//	response.
func (sdk *ConversationsNamespace) Open(ctx context.Context, token *string, channel *string, users *string, returnIm *bool) (*ConversationsOpenResponse, error) {
	return ConversationsOpen(ctx, sdk.config, token, channel, users, returnIm)
}

// Rename renames an existing conversation. Provide the conversation identifier in `channel` and the new name in `name`, using an authentication token with the `conversations:write` scope when authorization is required.
//
// Renames a conversation.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:write`
//	channel: ID of conversation to rename
//	name: New name for conversation.
func (sdk *ConversationsNamespace) Rename(ctx context.Context, token *string, channel *string, name *string) (*ConversationsRenameResponse, error) {
	return ConversationsRename(ctx, sdk.config, token, channel, name)
}

// Replies retrieves the messages in a conversation thread. Use `channel` and the parent message timestamp in `ts` to identify the thread, and use time bounds, `limit`, or `cursor` to control the returned messages.
//
// # Retrieve a thread of messages posted to a conversation
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:history`
//	channel: Conversation ID to fetch thread from.
//	ts: Unique identifier of a thread's parent message. `ts` must be the
//	timestamp of an existing message with 0 or more replies. If there are no
//	replies then just the single message referenced by `ts` will return - it is
//	just an ordinary, unthreaded message.
//	latest: End of time range of messages to include in results.
//	oldest: Start of time range of messages to include in results.
//	inclusive: Include messages with latest or oldest timestamp in results only
//	when either timestamp is specified.
//	limit: The maximum number of items to return. Fewer than the requested
//	number of items may be returned, even if the end of the users list hasn't
//	been reached.
//	cursor: Paginate through collections of data by setting the `cursor`
//	parameter to a `next_cursor` attribute returned by a previous request's
//	`response_metadata`. Default value fetches the first "page" of the
//	collection. See pagination for more detail.
func (sdk *ConversationsNamespace) Replies(ctx context.Context, token *string, channel *string, ts *float64, latest *float64, oldest *float64, inclusive *bool, limit *int64, cursor *string) (*ConversationsRepliesResponse, error) {
	return ConversationsReplies(ctx, sdk.config, token, channel, ts, latest, oldest, inclusive, limit, cursor)
}

// SetPurpose sets the purpose of an existing conversation. Provide the conversation in `channel` and the new purpose in `purpose`, using an authentication token with the `conversations:write` scope when authorization is required.
//
// Sets the purpose for a conversation.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:write`
//	channel: Conversation to set the purpose of
//	purpose: A new, specialer purpose
func (sdk *ConversationsNamespace) SetPurpose(ctx context.Context, token *string, channel *string, purpose *string) (*ConversationsSetPurposeResponse, error) {
	return ConversationsSetPurpose(ctx, sdk.config, token, channel, purpose)
}

// SetTopic updates the topic for a conversation. Provide `channel` to identify the conversation and `topic` for the replacement text; the topic does not support formatting or linkification.
//
// Sets the topic for a conversation.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:write`
//	channel: Conversation to set the topic of
//	topic: The new topic string. Does not support formatting or linkification.
func (sdk *ConversationsNamespace) SetTopic(ctx context.Context, token *string, channel *string, topic *string) (*ConversationsSetTopicResponse, error) {
	return ConversationsSetTopic(ctx, sdk.config, token, channel, topic)
}

// Unarchive restores an archived conversation to an active state. Provide `channel` to identify the conversation you want to unarchive.
//
// Reverses conversation archival.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:write`
//	channel: ID of conversation to unarchive
func (sdk *ConversationsNamespace) Unarchive(ctx context.Context, token *string, channel *string) (*ConversationsUnarchiveResponse, error) {
	return ConversationsUnarchive(ctx, sdk.config, token, channel)
}

type DialogNamespace struct {
	config ClientConfig
}

func NewDialogNamespace(config ClientConfig) *DialogNamespace {
	return &DialogNamespace{
		config: config,
	}
}

// Open opens a dialog for a user by exchanging a trigger for a dialog submission. Provide the JSON-encoded `dialog` definition and the `trigger_id` issued for the interaction.
//
// # Open a dialog with a user
//
// Parameters:
//
//	dialog: The dialog definition. This must be a JSON-encoded string.
//	triggerId: Exchange a trigger to post to the user.
//	token: Authentication token. Requires scope: `none`
func (sdk *DialogNamespace) Open(ctx context.Context, dialog string, triggerId string, token string) (*DialogOpenResponse, error) {
	return DialogOpen(ctx, sdk.config, dialog, triggerId, token)
}

type DndNamespace struct {
	config ClientConfig
}

func NewDndNamespace(config ClientConfig) *DndNamespace {
	return &DndNamespace{
		config: config,
	}
}

// DndEnd ends the authenticated user's active Do Not Disturb session immediately. Use this operation when the authenticated user wants to stop the current Do Not Disturb period rather than wait for its scheduled end.
//
// Ends the current user's Do Not Disturb session immediately.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `dnd:write`
func (sdk *DndNamespace) DndEnd(ctx context.Context, token string) (*DndEndDndResponse, error) {
	return DndEndDnd(ctx, sdk.config, token)
}

// EndSnooze ends the authenticated user's active snooze mode immediately. Use this operation to resume the normal Do Not Disturb schedule before the snooze period reaches its end time.
//
// Ends the current user's snooze mode immediately.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `dnd:write`
func (sdk *DndNamespace) EndSnooze(ctx context.Context, token string) (*DndEndSnoozeResponse, error) {
	return DndEndSnooze(ctx, sdk.config, token)
}

// Info retrieves the current Do Not Disturb status for a user. Omit `user` to retrieve the authenticated user's status, or provide a user identifier to inspect another user's status when permitted.
//
// Retrieves a user's current Do Not Disturb status.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `dnd:read`
//	user: User to fetch status for (defaults to current user)
func (sdk *DndNamespace) Info(ctx context.Context, token *string, user *string) (*DndInfoResponse, error) {
	return DndInfo(ctx, sdk.config, token, user)
}

// SetSnooze enables Do Not Disturb snooze mode for the authenticated user or changes its duration. Supply `token` and `num_minutes` to define how long the snooze should remain active.
//
// Turns on Do Not Disturb mode for the current user, or changes its duration.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `dnd:write`
//	numMinutes: Number of minutes, from now, to snooze until.
func (sdk *DndNamespace) SetSnooze(ctx context.Context, token string, numMinutes string) (*DndSetSnoozeResponse, error) {
	return DndSetSnooze(ctx, sdk.config, token, numMinutes)
}

// TeamInfo lists the Do Not Disturb status for up to 50 users on a team. Provide `users` as a comma-separated set of user identifiers, or omit it to use the method's default team scope.
//
// Retrieves the Do Not Disturb status for up to 50 users on a team.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `dnd:read`
//	users: Comma-separated list of users to fetch Do Not Disturb status for
func (sdk *DndNamespace) TeamInfo(ctx context.Context, token *string, users *string) (map[string]interface{}, error) {
	return DndTeamInfo(ctx, sdk.config, token, users)
}

type EmojiNamespace struct {
	config ClientConfig
}

func NewEmojiNamespace(config ClientConfig) *EmojiNamespace {
	return &EmojiNamespace{
		config: config,
	}
}

// List lists the custom emoji available for a team. Use this operation to retrieve the team's custom emoji collection with an authentication token that has emoji read access.
//
// Lists custom emoji for a team.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `emoji:read`
func (sdk *EmojiNamespace) List(ctx context.Context, token string) (map[string]interface{}, error) {
	return EmojiList(ctx, sdk.config, token)
}

type FilesCommentsNamespace struct {
	config ClientConfig
}
