// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

func NewFilesCommentsNamespace(config ClientConfig) *FilesCommentsNamespace {
	return &FilesCommentsNamespace{
		config: config,
	}
}

// Delete deletes an existing comment from a file. Provide `file` to identify the file and `id` to identify the comment you want to remove.
//
// Deletes an existing comment on a file.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `files:write:user`
//	file: File to delete a comment from.
//	id: The comment to delete.
func (sdk *FilesCommentsNamespace) Delete(ctx context.Context, token *string, file *string, id *string) (*FilesCommentsDeleteResponse, error) {
	return FilesCommentsDelete(ctx, sdk.config, token, file, id)
}

type FilesNamespace struct {
	config ClientConfig
}

func NewFilesNamespace(config ClientConfig) *FilesNamespace {
	return &FilesNamespace{
		config: config,
	}
}

// Delete deletes a file identified by its file ID. Use the `file` field to select the file and provide a token with the required file-writing scope. The operation returns a success indicator when the file is deleted.
//
// Deletes a file.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `files:write:user`
//	file: ID of file to delete.
func (sdk *FilesNamespace) Delete(ctx context.Context, token *string, file *string) (*FilesDeleteResponse, error) {
	return FilesDelete(ctx, sdk.config, token, file)
}

// Info retrieves information about a file and its comments. Use `file` to select the file and the pagination parameters to control the comments returned for that file. The response includes the file, comments, and paging metadata.
//
// Gets information about a file.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `files:read`
//	file: Specify a file by providing its ID.
//	limit: The maximum number of items to return. Fewer than the requested
//	number of items may be returned, even if the end of the list hasn't been
//	reached.
//	cursor: Parameter for pagination. File comments are paginated for a single
//	file. Set `cursor` equal to the `next_cursor` attribute returned by the
//	previous request's `response_metadata`. This parameter is optional, but
//	pagination is mandatory: the default value simply fetches the first "page"
//	of the collection of comments. See pagination for more details.
func (sdk *FilesNamespace) Info(ctx context.Context, token *string, file *string, count *string, page *string, limit *int64, cursor *string) (*FilesInfoResponse, error) {
	return FilesInfo(ctx, sdk.config, token, file, count, page, limit, cursor)
}

// List lists files for a team, channel, or user with optional filters. Use `user`, `channel`, `ts_from`, `ts_to`, and `types` to narrow the results, and use the paging parameters to control the returned page. The response includes matching files and paging metadata.
//
// List for a team, in a channel, or from a user with applied filters.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `files:read`
//	user: Filter files created by a single user.
//	channel: Filter files appearing in a specific channel, indicated by its ID.
//	tsFrom: Filter files created after this timestamp (inclusive).
//	tsTo: Filter files created before this timestamp (inclusive).
//	types: Filter files by type (see below). You can pass multiple values in the
//	types argument, like `types=spaces,snippets`.The default value is `all`,
//	which does not filter the list.
//	showFilesHiddenByLimit: Show truncated file info for files hidden due to
//	being too old, and the team who owns the file being over the file limit.
func (sdk *FilesNamespace) List(ctx context.Context, token *string, user *string, channel *string, tsFrom *float64, tsTo *float64, types *string, count *string, page *string, showFilesHiddenByLimit *bool) (*FilesListResponse, error) {
	return FilesList(ctx, sdk.config, token, user, channel, tsFrom, tsTo, types, count, page, showFilesHiddenByLimit)
}

// RevokePublicURL revokes public or external sharing access for a file. Supply the file ID in `file` to identify the file whose public access you want to remove. The response includes the updated file object after access is revoked.
//
// Revokes public/external sharing access for a file
//
// Parameters:
//
//	token: Authentication token. Requires scope: `files:write:user`
//	file: File to revoke
func (sdk *FilesNamespace) RevokePublicURL(ctx context.Context, token *string, file *string) (*FilesRevokePublicURLResponse, error) {
	return FilesRevokePublicURL(ctx, sdk.config, token, file)
}

// SharedPublicURL enables a file for public or external sharing. Supply the file identifier in `file` and an authentication token with the required file-writing scope. The response includes the updated file object after sharing is enabled.
//
// Enables a file for public/external sharing.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `files:write:user`
//	file: File to share
func (sdk *FilesNamespace) SharedPublicURL(ctx context.Context, token *string, file *string) (*FilesSharedPublicURLResponse, error) {
	return FilesSharedPublicURL(ctx, sdk.config, token, file)
}

// Upload uploads or creates a file and can share it with channels or attach it to a message thread. Provide either `file` or `content`, then use `filename`, `title`, `channels`, or `thread_ts` to control how the file is presented and shared. Include an initial message with `initial_comment` when introducing the file in specified channels.
//
// Uploads or creates a file.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `files:write:user`
//	file: File contents via `multipart/form-data`. If omitting this parameter,
//	you must submit `content`.
//	content: File contents via a POST variable. If omitting this parameter, you
//	must provide a `file`.
//	filetype: A file type identifier.
//	filename: Filename of file.
//	title: Title of file.
//	initialComment: The message text introducing the file in specified
//	`channels`.
//	channels: Comma-separated list of channel names or IDs where the file will
//	be shared.
//	threadTs: Provide another message's `ts` value to upload this file as a
//	reply. Never use a reply's `ts` value; use its parent instead.
func (sdk *FilesNamespace) Upload(ctx context.Context, token *string, file *string, content *string, filetype *string, filename *string, title *string, initialComment *string, channels *string, threadTs *float64) (*FilesUploadResponse, error) {
	return FilesUpload(ctx, sdk.config, token, file, content, filetype, filename, title, initialComment, channels, threadTs)
}

type FilesRemoteNamespace struct {
	config ClientConfig
}

func NewFilesRemoteNamespace(config ClientConfig) *FilesRemoteNamespace {
	return &FilesRemoteNamespace{
		config: config,
	}
}

// Add adds a file hosted by a remote service. Supply the remote file identity and metadata such as `title`, `filetype`, and `external_url` to register it. You can also provide `preview_image` and searchable text in `indexable_file_contents`.
//
// Adds a file from a remote service
//
// Parameters:
//
//	token: Authentication token. Requires scope: `remote_files:write`
//	externalId: Creator defined GUID for the file.
//	title: Title of the file being shared.
//	filetype: type of file
//	externalUrl: URL of the remote file.
//	previewImage: Preview of the document via `multipart/form-data`.
//	indexableFileContents: A text file (txt, pdf, doc, etc.) containing textual
//	search terms that are used to improve discovery of the remote file.
func (sdk *FilesRemoteNamespace) Add(ctx context.Context, token *string, externalId *string, title *string, filetype *string, externalUrl *string, previewImage *string, indexableFileContents *string) (map[string]interface{}, error) {
	return FilesRemoteAdd(ctx, sdk.config, token, externalId, title, filetype, externalUrl, previewImage, indexableFileContents)
}

// Info retrieves information about a remote file registered with the service. Identify the file with `file` or the creator-defined `external_id`. The response confirms whether the request succeeded.
//
// Retrieve information about a remote file added to Slack
//
// Parameters:
//
//	token: Authentication token. Requires scope: `remote_files:read`
//	file: Specify a file by providing its ID.
//	externalId: Creator defined GUID for the file.
func (sdk *FilesRemoteNamespace) Info(ctx context.Context, token *string, file *string, externalId *string) (map[string]interface{}, error) {
	return FilesRemoteInfo(ctx, sdk.config, token, file, externalId)
}

// List lists remote files with optional channel and creation-time filters. Use `channel`, `ts_from`, and `ts_to` to narrow the collection, and use `limit` with `cursor` to paginate through results. The response confirms whether the request succeeded.
//
// Retrieve information about a remote file added to Slack
//
// Parameters:
//
//	token: Authentication token. Requires scope: `remote_files:read`
//	channel: Filter files appearing in a specific channel, indicated by its ID.
//	tsFrom: Filter files created after this timestamp (inclusive).
//	tsTo: Filter files created before this timestamp (inclusive).
//	limit: The maximum number of items to return.
//	cursor: Paginate through collections of data by setting the `cursor`
//	parameter to a `next_cursor` attribute returned by a previous request's
//	`response_metadata`. Default value fetches the first "page" of the
//	collection. See pagination for more detail.
func (sdk *FilesRemoteNamespace) List(ctx context.Context, token *string, channel *string, tsFrom *float64, tsTo *float64, limit *int64, cursor *string) (map[string]interface{}, error) {
	return FilesRemoteList(ctx, sdk.config, token, channel, tsFrom, tsTo, limit, cursor)
}

// Remove removes a remote file registered with the service. Identify the remote file with `file`, `external_id`, or both. The operation removes the registered remote file rather than deleting the source file from its external service.
//
// Remove a remote file.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `remote_files:write`
//	file: Specify a file by providing its ID.
//	externalId: Creator defined GUID for the file.
func (sdk *FilesRemoteNamespace) Remove(ctx context.Context, token *string, file *string, externalId *string) (map[string]interface{}, error) {
	return FilesRemoteRemove(ctx, sdk.config, token, file, externalId)
}

// Share shares a remote file into one or more channels. Identify the file with `file`, `external_id`, or both, and provide the destination channel IDs in `channels`. The operation makes the registered remote file available in the specified channels.
//
// Share a remote file into a channel.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `remote_files:share`
//	file: Specify a file registered with Slack by providing its ID. Either this
//	field or `external_id` or both are required.
//	externalId: The globally unique identifier (GUID) for the file, as set by
//	the app registering the file with Slack. Either this field or `file` or both
//	are required.
//	channels: Comma-separated list of channel IDs where the file will be shared.
func (sdk *FilesRemoteNamespace) Share(ctx context.Context, token *string, file *string, externalId *string, channels *string) (map[string]interface{}, error) {
	return FilesRemoteShare(ctx, sdk.config, token, file, externalId, channels)
}

// Update updates an existing remote file registered with the service. Identify the file with `file` or `external_id`, then provide the metadata you want to change. You can update its title, type, URL, preview image, and searchable contents.
//
// Updates an existing remote file.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `remote_files:write`
//	file: Specify a file by providing its ID.
//	externalId: Creator defined GUID for the file.
//	title: Title of the file being shared.
//	filetype: type of file
//	externalUrl: URL of the remote file.
//	previewImage: Preview of the document via `multipart/form-data`.
//	indexableFileContents: File containing contents that can be used to improve
//	searchability for the remote file.
func (sdk *FilesRemoteNamespace) Update(ctx context.Context, token *string, file *string, externalId *string, title *string, filetype *string, externalUrl *string, previewImage *string, indexableFileContents *string) (map[string]interface{}, error) {
	return FilesRemoteUpdate(ctx, sdk.config, token, file, externalId, title, filetype, externalUrl, previewImage, indexableFileContents)
}

type MigrationNamespace struct {
	config ClientConfig
}

func NewMigrationNamespace(config ClientConfig) *MigrationNamespace {
	return &MigrationNamespace{
		config: config,
	}
}

// Exchange maps workspace-specific user IDs to global user IDs for an Enterprise Grid workspace. Supply up to 400 comma-separated user IDs in `users`, and use `to_old` to request conversion from global IDs back to workspace-specific IDs. Include `team_id` when using an organization token to identify the workspace.
//
// For Enterprise Grid workspaces, map local user IDs to global user IDs
//
// Parameters:
//
//	token: Authentication token. Requires scope: `tokens.basic`
//	users: A comma-separated list of user ids, up to 400 per request
//	teamId: Specify team_id starts with `T` in case of Org Token
//	toOld: Specify `true` to convert `W` global user IDs to workspace-specific
//	`U` IDs. Defaults to `false`.
func (sdk *MigrationNamespace) Exchange(ctx context.Context, token string, users string, teamId *string, toOld *bool) (map[string]interface{}, error) {
	return MigrationExchange(ctx, sdk.config, token, users, teamId, toOld)
}

type OauthNamespace struct {
	config ClientConfig
}

func NewOauthNamespace(config ClientConfig) *OauthNamespace {
	return &OauthNamespace{
		config: config,
	}
}

// Access exchanges a temporary OAuth verifier code for an access token for a single-scope authorization flow. Supply the `code` returned through the OAuth callback and the application credentials, and ensure `redirect_uri` matches the URI originally submitted when one was used. Set `single_channel` only when requesting installation to a single channel for a legacy workspace app.
//
// Exchanges a temporary OAuth verifier code for an access token.
//
// Parameters:
//
//	clientId: Issued when you created your application.
//	clientSecret: Issued when you created your application.
//	code: The `code` param returned via the OAuth callback.
//	redirectUri: This must match the originally submitted URI (if one was sent).
//	singleChannel: Request the user to add your app only to a single channel.
//	Only valid with a [legacy workspace
//	app](https://api.slack.com/legacy-workspace-apps).
func (sdk *OauthNamespace) Access(ctx context.Context, clientId *string, clientSecret *string, code *string, redirectUri *string, singleChannel *bool) (map[string]interface{}, error) {
	return OauthAccess(ctx, sdk.config, clientId, clientSecret, code, redirectUri, singleChannel)
}

// Token exchanges a temporary OAuth verifier code for a workspace token. Supply the `code` returned through the OAuth callback and the application credentials, and ensure `redirect_uri` matches the URI originally submitted when one was used. Use `single_channel` to request installation to a single channel when supported by the workspace app.
//
// Exchanges a temporary OAuth verifier code for a workspace token.
//
// Parameters:
//
//	clientId: Issued when you created your application.
//	clientSecret: Issued when you created your application.
//	code: The `code` param returned via the OAuth callback.
//	redirectUri: This must match the originally submitted URI (if one was sent).
//	singleChannel: Request the user to add your app only to a single channel.
func (sdk *OauthNamespace) Token(ctx context.Context, clientId *string, clientSecret *string, code *string, redirectUri *string, singleChannel *bool) (map[string]interface{}, error) {
	return OauthToken(ctx, sdk.config, clientId, clientSecret, code, redirectUri, singleChannel)
}

type OauthV2Namespace struct {
	config ClientConfig
}

func NewOauthV2Namespace(config ClientConfig) *OauthV2Namespace {
	return &OauthV2Namespace{
		config: config,
	}
}

// Access exchanges a temporary OAuth verifier code for access tokens with scopes for a bot user and a user token. Supply the required `code` from the OAuth callback and the application credentials, and provide `redirect_uri` when it was part of the original authorization request. The response confirms whether the token exchange succeeded.
//
// Exchanges a temporary OAuth verifier code for an access token.
//
// Parameters:
//
//	code: The `code` param returned via the OAuth callback.
//	clientId: Issued when you created your application.
//	clientSecret: Issued when you created your application.
//	redirectUri: This must match the originally submitted URI (if one was sent).
func (sdk *OauthV2Namespace) Access(ctx context.Context, code string, clientId *string, clientSecret *string, redirectUri *string) (map[string]interface{}, error) {
	return OauthV2Access(ctx, sdk.config, code, clientId, clientSecret, redirectUri)
}

type PinsNamespace struct {
	config ClientConfig
}

func NewPinsNamespace(config ClientConfig) *PinsNamespace {
	return &PinsNamespace{
		config: config,
	}
}

// Add pins an item to a channel. Supply the target `channel` and, when pinning a message, provide its `timestamp` to identify the item. Use an authentication token with the `pins:write` scope to perform the operation.
//
// Pins an item to a channel.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `pins:write`
//	channel: Channel to pin the item in.
//	timestamp: Timestamp of the message to pin.
func (sdk *PinsNamespace) Add(ctx context.Context, token string, channel string, timestamp *string) (*PinsAddResponse, error) {
	return PinsAdd(ctx, sdk.config, token, channel, timestamp)
}

// List lists the items pinned to a channel. Supply the channel identifier together with an authentication token that has permission to read pins. The response can contain either the pinned item collection or a count, depending on the returned result shape.
//
// Lists items pinned to a channel.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `pins:read`
//	channel: Channel to get pinned items for.
func (sdk *PinsNamespace) List(ctx context.Context, token string, channel string) ([]interface{}, error) {
	return PinsList(ctx, sdk.config, token, channel)
}

// Remove removes a pinned item from a channel. Supply the target `channel` and, when removing a pinned message, provide its `timestamp` to identify the item. Use an authentication token with the `pins:write` scope to perform the operation.
//
// Un-pins an item from a channel.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `pins:write`
//	channel: Channel where the item is pinned to.
//	timestamp: Timestamp of the message to un-pin.
func (sdk *PinsNamespace) Remove(ctx context.Context, token string, channel string, timestamp *string) (*PinsRemoveResponse, error) {
	return PinsRemove(ctx, sdk.config, token, channel, timestamp)
}

type ReactionsNamespace struct {
	config ClientConfig
}

func NewReactionsNamespace(config ClientConfig) *ReactionsNamespace {
	return &ReactionsNamespace{
		config: config,
	}
}

// Add adds an emoji reaction to a message or other supported item. Supply the channel, reaction name, and message timestamp to identify both the reaction and its target. Use an authentication token with the `reactions:write` scope to perform the operation.
//
// Adds a reaction to an item.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `reactions:write`
//	channel: Channel where the message to add reaction to was posted.
//	name: Reaction (emoji) name.
//	timestamp: Timestamp of the message to add reaction to.
func (sdk *ReactionsNamespace) Add(ctx context.Context, token string, channel string, name string, timestamp string) (*ReactionsAddResponse, error) {
	return ReactionsAdd(ctx, sdk.config, token, channel, name, timestamp)
}

// Get retrieves reactions for a message, file, or file comment. Supply the authentication `token` and identify the item with the applicable target parameters; set `full` to request the complete reaction list. The response identifies the item and includes its reactions.
//
// Gets reactions for an item.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `reactions:read`
//	channel: Channel where the message to get reactions for was posted.
//	file: File to get reactions for.
//	fileComment: File comment to get reactions for.
//	full: If true always return the complete reaction list.
//	timestamp: Timestamp of the message to get reactions for.
func (sdk *ReactionsNamespace) Get(ctx context.Context, token string, channel *string, file *string, fileComment *string, full *bool, timestamp *string) (map[string]interface{}, error) {
	return ReactionsGet(ctx, sdk.config, token, channel, file, fileComment, full, timestamp)
}

// List lists reactions made by a specified user or by the authenticated user when `user` is omitted. Use `full` to request complete reaction details and use `cursor`, `page`, or `count` to control pagination and page size. The response includes reaction items, paging information, and continuation metadata.
//
// Lists reactions made by a user.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `reactions:read`
//	user: Show reactions made by this user. Defaults to the authed user.
//	full: If true always return the complete reaction list.
//	cursor: Parameter for pagination. Set `cursor` equal to the `next_cursor`
//	attribute returned by the previous request's `response_metadata`. This
//	parameter is optional, but pagination is mandatory: the default value simply
//	fetches the first "page" of the collection. See pagination for more details.
//	limit: The maximum number of items to return. Fewer than the requested
//	number of items may be returned, even if the end of the list hasn't been
//	reached.
func (sdk *ReactionsNamespace) List(ctx context.Context, token string, user *string, full *bool, count *int64, page *int64, cursor *string, limit *int64) (*ReactionsListResponse, error) {
	return ReactionsList(ctx, sdk.config, token, user, full, count, page, cursor, limit)
}

// Remove removes a reaction from a message, file, or file comment. Supply the reaction `name` and identify the target with the applicable body fields. The response confirms that the reaction was removed.
//
// Removes a reaction from an item.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `reactions:write`
//	name: Reaction (emoji) name.
//	file: File to remove reaction from.
//	fileComment: File comment to remove reaction from.
//	channel: Channel where the message to remove reaction from was posted.
//	timestamp: Timestamp of the message to remove reaction from.
func (sdk *ReactionsNamespace) Remove(ctx context.Context, token string, name string, file *string, fileComment *string, channel *string, timestamp *string) (*ReactionsRemoveResponse, error) {
	return ReactionsRemove(ctx, sdk.config, token, name, file, fileComment, channel, timestamp)
}

type RemindersNamespace struct {
	config ClientConfig
}

func NewRemindersNamespace(config ClientConfig) *RemindersNamespace {
	return &RemindersNamespace{
		config: config,
	}
}

// Add creates a reminder for the authenticated user or for the user specified by `user`. Supply the reminder `text` and its `time`, which can be a Unix timestamp, a delay in seconds, or a natural-language schedule. The response returns the created reminder and its scheduling details.
//
// Creates a reminder.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `reminders:write`
//	text: The content of the reminder
//	time: When this reminder should happen: the Unix timestamp (up to five years
//	from now), the number of seconds until the reminder (if within 24 hours), or
//	a natural language description (Ex. "in 15 minutes," or "every Thursday")
//	user: The user who will receive the reminder. If no user is specified, the
//	reminder will go to user who created it.
func (sdk *RemindersNamespace) Add(ctx context.Context, token string, text string, time string, user *string) (*RemindersAddResponse, error) {
	return RemindersAdd(ctx, sdk.config, token, text, time, user)
}

// Complete marks a reminder as complete. Supply the reminder identifier in `reminder` when completing a specific reminder, and provide the authentication `token` when required by the authorization context. The response confirms completion.
//
// Marks a reminder as complete.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `reminders:write`
//	reminder: The ID of the reminder to be marked as complete
func (sdk *RemindersNamespace) Complete(ctx context.Context, token *string, reminder *string) (*RemindersCompleteResponse, error) {
	return RemindersComplete(ctx, sdk.config, token, reminder)
}

// Delete deletes a reminder. Supply the reminder identifier in `reminder` and provide the authentication `token` when required by the authorization context. The response confirms deletion.
//
// Deletes a reminder.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `reminders:write`
//	reminder: The ID of the reminder
func (sdk *RemindersNamespace) Delete(ctx context.Context, token *string, reminder *string) (*RemindersDeleteResponse, error) {
	return RemindersDelete(ctx, sdk.config, token, reminder)
}

// Info retrieves the details of a reminder. Supply `reminder` to retrieve a specific reminder, or omit it when the authorization context determines the reminder. The response includes the reminder's schedule, recipient, creator, text, and completion information.
//
// Gets information about a reminder.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `reminders:read`
//	reminder: The ID of the reminder
func (sdk *RemindersNamespace) Info(ctx context.Context, token *string, reminder *string) (*RemindersInfoResponse, error) {
	return RemindersInfo(ctx, sdk.config, token, reminder)
}

// List lists all reminders created by or assigned to the authenticated user. Provide the authentication `token` when required by the authorization context. The response returns each reminder with its recipient, schedule, text, and completion information.
//
// Lists all reminders created by or for a given user.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `reminders:read`
func (sdk *RemindersNamespace) List(ctx context.Context, token *string) (*RemindersListResponse, error) {
	return RemindersList(ctx, sdk.config, token)
}

type RtmNamespace struct {
	config ClientConfig
}

func NewRtmNamespace(config ClientConfig) *RtmNamespace {
	return &RtmNamespace{
		config: config,
	}
}

// Connect triggers a Real Time Messaging session for the authenticated user. Supply the `token` with the `rtm:stream` scope and optionally configure presence delivery with `batch_presence_aware` and `presence_sub`. The response provides the session URL, team details, and authenticated user's identity.
//
// Starts a Real Time Messaging session.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `rtm:stream`
//	batchPresenceAware: Batch presence deliveries via subscription. Enabling
//	changes the shape of `presence_change` events. See batch presence.
//	presenceSub: Only deliver presence events when requested by subscription.
//	See presence subscriptions.
func (sdk *RtmNamespace) Connect(ctx context.Context, token string, batchPresenceAware *bool, presenceSub *bool) (*RtmConnectResponse, error) {
	return RtmConnect(ctx, sdk.config, token, batchPresenceAware, presenceSub)
}

type SearchNamespace struct {
	config ClientConfig
}

func NewSearchNamespace(config ClientConfig) *SearchNamespace {
	return &SearchNamespace{
		config: config,
	}
}

// Messages searches messages matching the required `query` string. Use `count` and `page` to control result pages, `sort` and `sort_dir` to order matches, and `highlight` to include query highlight markers. The response confirms whether the search request completed successfully.
//
// Searches for messages matching a query.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `search:read`
//	query: Search query.
//	count: Pass the number of results you want per "page". Maximum of `100`.
//	highlight: Pass a value of `true` to enable query highlight markers (see
//	below).
//	sort: Return matches sorted by either `score` or `timestamp`.
//	sortDir: Change sort direction to ascending (`asc`) or descending (`desc`).
func (sdk *SearchNamespace) Messages(ctx context.Context, token string, query string, count *int64, highlight *bool, page *int64, sort *string, sortDir *string) (map[string]interface{}, error) {
	return SearchMessages(ctx, sdk.config, token, query, count, highlight, page, sort, sortDir)
}

type StarsNamespace struct {
	config ClientConfig
}

func NewStarsNamespace(config ClientConfig) *StarsNamespace {
	return &StarsNamespace{
		config: config,
	}
}

// Add adds a star to a message, channel, file, or file comment. Supply an authentication token with the `stars:write` scope and identify the item using the applicable target fields. The request succeeds only when the item is not already starred.
//
// Adds a star to an item.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `stars:write`
//	channel: Channel to add star to, or channel where the message to add star to
//	was posted (used with `timestamp`).
//	file: File to add star to.
//	fileComment: File comment to add star to.
//	timestamp: Timestamp of the message to add star to.
func (sdk *StarsNamespace) Add(ctx context.Context, token string, channel *string, file *string, fileComment *string, timestamp *string) (*StarsAddResponse, error) {
	return StarsAdd(ctx, sdk.config, token, channel, file, fileComment, timestamp)
}

// List lists the items starred by a user. Use the pagination parameters to retrieve the collection in pages, with `cursor` set to the `next_cursor` value from the previous response when available. The response includes paging information alongside the starred items.
//
// Lists stars for a user.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `stars:read`
//	cursor: Parameter for pagination. Set `cursor` equal to the `next_cursor`
//	attribute returned by the previous request's `response_metadata`. This
//	parameter is optional, but pagination is mandatory: the default value simply
//	fetches the first "page" of the collection. See pagination for more details.
//	limit: The maximum number of items to return. Fewer than the requested
//	number of items may be returned, even if the end of the list hasn't been
//	reached.
func (sdk *StarsNamespace) List(ctx context.Context, token *string, count *string, page *string, cursor *string, limit *int64) (*StarsListResponse, error) {
	return StarsList(ctx, sdk.config, token, count, page, cursor, limit)
}

// Remove removes a star from a message, channel, file, or file comment. Supply an authentication token with the `stars:write` scope and identify the item using the applicable target fields. The request succeeds only when the item is currently starred.
//
// Removes a star from an item.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `stars:write`
//	channel: Channel to remove star from, or channel where the message to remove
//	star from was posted (used with `timestamp`).
//	file: File to remove star from.
//	fileComment: File comment to remove star from.
//	timestamp: Timestamp of the message to remove star from.
func (sdk *StarsNamespace) Remove(ctx context.Context, token string, channel *string, file *string, fileComment *string, timestamp *string) (*StarsRemoveResponse, error) {
	return StarsRemove(ctx, sdk.config, token, channel, file, fileComment, timestamp)
}

type TeamNamespace struct {
	config ClientConfig
}

func NewTeamNamespace(config ClientConfig) *TeamNamespace {
	return &TeamNamespace{
		config: config,
	}
}

// AccessLogs lists access logs for the current team. Use `before` to define the inclusive end of the log range and `count` and `page` to retrieve paginated results. Each response includes login records and paging metadata.
//
// Gets the access logs for the current team.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin`
//	before: End of time range of logs to include in results (inclusive).
func (sdk *TeamNamespace) AccessLogs(ctx context.Context, token string, before *string, count *string, page *string) (*TeamAccessLogsResponse, error) {
	return TeamAccessLogs(ctx, sdk.config, token, before, count, page)
}

// BillableInfo retrieves billable user information for the current team. Use `user` to limit the response to one user, or omit it to request information for all users. The response provides the method's success indicator.
//
// Gets billable users information for the current team.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `admin`
//	user: A user to retrieve the billable information for. Defaults to all
//	users.
func (sdk *TeamNamespace) BillableInfo(ctx context.Context, token string, user *string) (map[string]interface{}, error) {
	return TeamBillableInfo(ctx, sdk.config, token, user)
}

// Info retrieves information about a team. Omit `team` to retrieve the current team, or provide it to request a team visible to the authenticated token through external shared channels. The response includes the team's required identity and profile details.
//
// Gets information about the current team.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `team:read`
//	team: Team to get info on, if omitted, will return information about the
//	current team. Will only return team that the authenticated token is allowed
//	to see through external shared channels
func (sdk *TeamNamespace) Info(ctx context.Context, token string, team *string) (*TeamInfoResponse, error) {
	return TeamInfo(ctx, sdk.config, token, team)
}
