// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"context"
	"encoding/json"
)

// UsersDeletePhotoResponse Schema for successful response from users.deletePhoto method
type UsersDeletePhotoResponse struct {
	Ok DefsOkTrue `json:"ok"`
}

func (value *UsersDeletePhotoResponse) UnmarshalJSON(data []byte) error {
	type UsersDeletePhotoResponseAlias UsersDeletePhotoResponse
	var decoded UsersDeletePhotoResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = UsersDeletePhotoResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewUsersDeletePhotoResponse returns a validated UsersDeletePhotoResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewUsersDeletePhotoResponse(fields UsersDeletePhotoResponse) (*UsersDeletePhotoResponse, error) {
	return ConstructModel(fields)
}

// UsersListResponse Schema for successful response from users.list method
type UsersListResponse struct {
	CacheTs          int64                 `json:"cache_ts"`
	Members          []ObjsUser            `json:"members"`
	Ok               DefsOkTrue            `json:"ok"`
	ResponseMetadata *ObjsResponseMetadata `json:"response_metadata,omitempty"`
}

func (value *UsersListResponse) UnmarshalJSON(data []byte) error {
	type UsersListResponseAlias UsersListResponse
	var decoded UsersListResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = UsersListResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok", "members", "cache_ts"}); err != nil {
		return err
	}
	if err := ValidateItems("members", value.Members, LengthOpts{Min: Ptr[int](1)}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewUsersListResponse returns a validated UsersListResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewUsersListResponse(fields UsersListResponse) (*UsersListResponse, error) {
	return ConstructModel(fields)
}

// UsersSetActiveResponse Schema for successful response from users.setActive method
type UsersSetActiveResponse struct {
	Ok DefsOkTrue `json:"ok"`
}

func (value *UsersSetActiveResponse) UnmarshalJSON(data []byte) error {
	type UsersSetActiveResponseAlias UsersSetActiveResponse
	var decoded UsersSetActiveResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = UsersSetActiveResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewUsersSetActiveResponse returns a validated UsersSetActiveResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewUsersSetActiveResponse(fields UsersSetActiveResponse) (*UsersSetActiveResponse, error) {
	return ConstructModel(fields)
}

// UsersSetPhotoResponse Schema for successful response from users.setPhoto method
type UsersSetPhotoResponse struct {
	Ok      DefsOkTrue                   `json:"ok"`
	Profile UsersSetPhotoResponseProfile `json:"profile"`
}

func (value *UsersSetPhotoResponse) UnmarshalJSON(data []byte) error {
	type UsersSetPhotoResponseAlias UsersSetPhotoResponse
	var decoded UsersSetPhotoResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = UsersSetPhotoResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok", "profile"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewUsersSetPhotoResponse returns a validated UsersSetPhotoResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewUsersSetPhotoResponse(fields UsersSetPhotoResponse) (*UsersSetPhotoResponse, error) {
	return ConstructModel(fields)
}

type UsersSetPhotoResponseProfile struct {
	AvatarHash    string `json:"avatar_hash"`
	Image1024     string `json:"image_1024"`
	Image192      string `json:"image_192"`
	Image24       string `json:"image_24"`
	Image32       string `json:"image_32"`
	Image48       string `json:"image_48"`
	Image512      string `json:"image_512"`
	Image72       string `json:"image_72"`
	ImageOriginal string `json:"image_original"`
}

func (value *UsersSetPhotoResponseProfile) UnmarshalJSON(data []byte) error {
	type UsersSetPhotoResponseProfileAlias UsersSetPhotoResponseProfile
	var decoded UsersSetPhotoResponseProfileAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = UsersSetPhotoResponseProfile(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"image_24", "image_32", "image_48", "image_72", "image_192", "image_512", "image_1024", "image_original", "avatar_hash"}); err != nil {
		return err
	}
	if err := ValidatePattern("avatar_hash", value.AvatarHash, "^[0-9a-f]{12}$"); err != nil {
		return err
	}
	if err := ValidateUri("image_1024", value.Image1024); err != nil {
		return err
	}
	if err := ValidateUri("image_192", value.Image192); err != nil {
		return err
	}
	if err := ValidateUri("image_24", value.Image24); err != nil {
		return err
	}
	if err := ValidateUri("image_32", value.Image32); err != nil {
		return err
	}
	if err := ValidateUri("image_48", value.Image48); err != nil {
		return err
	}
	if err := ValidateUri("image_512", value.Image512); err != nil {
		return err
	}
	if err := ValidateUri("image_72", value.Image72); err != nil {
		return err
	}
	if err := ValidateUri("image_original", value.ImageOriginal); err != nil {
		return err
	}
	return nil
}

// NewUsersSetPhotoResponseProfile returns a validated UsersSetPhotoResponseProfile built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewUsersSetPhotoResponseProfile(fields UsersSetPhotoResponseProfile) (*UsersSetPhotoResponseProfile, error) {
	return ConstructModel(fields)
}

// UsersSetPresenceResponse Schema for successful response from users.setPresence method
type UsersSetPresenceResponse struct {
	Ok DefsOkTrue `json:"ok"`
}

func (value *UsersSetPresenceResponse) UnmarshalJSON(data []byte) error {
	type UsersSetPresenceResponseAlias UsersSetPresenceResponse
	var decoded UsersSetPresenceResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = UsersSetPresenceResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewUsersSetPresenceResponse returns a validated UsersSetPresenceResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewUsersSetPresenceResponse(fields UsersSetPresenceResponse) (*UsersSetPresenceResponse, error) {
	return ConstructModel(fields)
}

// UsersConversations lists the conversations that the authenticated user may access. Filter by conversation types, user membership, and archived status, and use `cursor` to retrieve successive pages of results.
//
// List conversations the calling user may access.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `conversations:read`
//	user: Browse conversations by a specific user ID's membership. Non-public
//	channels are restricted to those where the calling user shares membership.
//	types: Mix and match channel types by providing a comma-separated list of
//	any combination of `public_channel`, `private_channel`, `mpim`, `im`
//	excludeArchived: Set to `true` to exclude archived channels from the list
//	limit: The maximum number of items to return. Fewer than the requested
//	number of items may be returned, even if the end of the list hasn't been
//	reached. Must be an integer no larger than 1000.
//	cursor: Paginate through collections of data by setting the `cursor`
//	parameter to a `next_cursor` attribute returned by a previous request's
//	`response_metadata`. Default value fetches the first "page" of the
//	collection. See pagination for more detail.
func UsersConversations(ctx context.Context, clientConfig ClientConfig, token *string, user *string, types *string, excludeArchived *bool, limit *int64, cursor *string) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "GET", "/users.conversations", &RequestOpts{
		Query: map[string]any{
			"token":            QueryValue{Value: token, Style: "form", Explode: true},
			"user":             QueryValue{Value: user, Style: "form", Explode: true},
			"types":            QueryValue{Value: types, Style: "form", Explode: true},
			"exclude_archived": QueryValue{Value: excludeArchived, Style: "form", Explode: true},
			"limit":            QueryValue{Value: limit, Style: "form", Explode: true},
			"cursor":           QueryValue{Value: cursor, Style: "form", Explode: true},
		},
		OperationID: "UsersConversations",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}

// UsersDeletePhoto deletes the profile photo associated with the authenticated user. Send the required authentication token in the form body to authorize removal of the current photo.
//
// Delete the user profile photo
//
// Parameters:
//
//	token: Authentication token. Requires scope: `users.profile:write`
func UsersDeletePhoto(ctx context.Context, clientConfig ClientConfig, token string) (*UsersDeletePhotoResponse, error) {
	resp, err := DoCfg[UsersDeletePhotoResponse](ctx, &clientConfig, "POST", "/users.deletePhoto", &RequestOpts{
		Body: map[string]any{
			"token": token,
		},
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "UsersDeletePhoto",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// UsersGetPresence retrieves presence information for the authenticated user or another specified user. Omit `user` to retrieve the authenticated user's presence, or provide a user ID to inspect another user's current presence.
//
// Gets user presence information.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `users:read`
//	user: User to get presence info on. Defaults to the authed user.
func UsersGetPresence(ctx context.Context, clientConfig ClientConfig, token string, user *string) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "GET", "/users.getPresence", &RequestOpts{
		Query: map[string]any{
			"token": QueryValue{Value: token, Style: "form", Explode: true},
			"user":  QueryValue{Value: user, Style: "form", Explode: true},
		},
		OperationID: "UsersGetPresence",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}

// UsersIdentity retrieves the authenticated user's identity and team information. Provide a token with the `identity.basic` scope, with additional identity scopes determining whether fields such as email or avatar details are included.
//
// Get a user's identity.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `identity.basic`
func UsersIdentity(ctx context.Context, clientConfig ClientConfig, token *string) ([]interface{}, error) {
	resp, err := DoCfg[[]interface{}](ctx, &clientConfig, "GET", "/users.identity", &RequestOpts{
		Query: map[string]any{
			"token": QueryValue{Value: token, Style: "form", Explode: true},
		},
		OperationID: "UsersIdentity",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}

// UsersInfo retrieves information about a specified user or, when `user` is omitted, the user associated with the authentication context. Set `include_locale` to include the user's locale in the returned user object.
//
// Gets information about a user.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `users:read`
//	includeLocale: Set this to `true` to receive the locale for this user.
//	Defaults to `false`
//	user: User to get info on
func UsersInfo(ctx context.Context, clientConfig ClientConfig, token string, includeLocale *bool, user *string) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "GET", "/users.info", &RequestOpts{
		Query: map[string]any{
			"token":          QueryValue{Value: token, Style: "form", Explode: true},
			"include_locale": QueryValue{Value: includeLocale, Style: "form", Explode: true},
			"user":           QueryValue{Value: user, Style: "form", Explode: true},
		},
		OperationID: "UsersInfo",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}

// UsersList lists all users in a Slack team. Use `cursor` to retrieve subsequent pages, `limit` to control the requested page size, and `include_locale` when you need each user's locale.
//
// Lists all users in a Slack team.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `users:read`
//	limit: The maximum number of items to return. Fewer than the requested
//	number of items may be returned, even if the end of the users list hasn't
//	been reached. Providing no `limit` value will result in Slack attempting to
//	deliver you the entire result set. If the collection is too large you may
//	experience `limit_required` or HTTP 500 errors.
//	cursor: Paginate through collections of data by setting the `cursor`
//	parameter to a `next_cursor` attribute returned by a previous request's
//	`response_metadata`. Default value fetches the first "page" of the
//	collection. See pagination for more detail.
//	includeLocale: Set this to `true` to receive the locale for users. Defaults
//	to `false`
func UsersList(ctx context.Context, clientConfig ClientConfig, token *string, limit *int64, cursor *string, includeLocale *bool) (*UsersListResponse, error) {
	resp, err := DoCfg[UsersListResponse](ctx, &clientConfig, "GET", "/users.list", &RequestOpts{
		Query: map[string]any{
			"token":          QueryValue{Value: token, Style: "form", Explode: true},
			"limit":          QueryValue{Value: limit, Style: "form", Explode: true},
			"cursor":         QueryValue{Value: cursor, Style: "form", Explode: true},
			"include_locale": QueryValue{Value: includeLocale, Style: "form", Explode: true},
		},
		OperationID: "UsersList",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// UsersLookupByEmail retrieves the Slack user associated with an email address. Supply `email` to identify the user and use a token with the `users:read.email` scope.
//
// Find a user with an email address.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `users:read.email`
//	email: An email address belonging to a user in the workspace
func UsersLookupByEmail(ctx context.Context, clientConfig ClientConfig, token string, email string) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "GET", "/users.lookupByEmail", &RequestOpts{
		Query: map[string]any{
			"token": QueryValue{Value: token, Style: "form", Explode: true},
			"email": QueryValue{Value: email, Style: "form", Explode: true},
		},
		OperationID: "UsersLookupByEmail",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}

// UsersSetActive attempts to mark a user as active, but the operation is deprecated and non-functional. Provide the authentication token required by the legacy method if you call it.
//
// Marked a user as active. Deprecated and non-functional.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `users:write`
func UsersSetActive(ctx context.Context, clientConfig ClientConfig, token string) (*UsersSetActiveResponse, error) {
	resp, err := DoCfg[UsersSetActiveResponse](ctx, &clientConfig, "POST", "/users.setActive", &RequestOpts{
		Headers: OperationHeaders(map[string]any{
					"token": token,
		}),
		OperationID: "UsersSetActive",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// UsersSetPhoto updates a user's profile photo. Submit the image with optional crop coordinates and dimensions, using the authentication token included in the form.
//
// Set the user profile photo
//
// Parameters:
//
//	token: Authentication token. Requires scope: `users.profile:write`
//	cropW: Width/height of crop box (always square)
//	cropX: X coordinate of top-left corner of crop box
//	cropY: Y coordinate of top-left corner of crop box
//	image: File contents via `multipart/form-data`.
func UsersSetPhoto(ctx context.Context, clientConfig ClientConfig, token string, cropW *string, cropX *string, cropY *string, image *string) (*UsersSetPhotoResponse, error) {
	resp, err := DoCfg[UsersSetPhotoResponse](ctx, &clientConfig, "POST", "/users.setPhoto", &RequestOpts{
		Body: map[string]any{
			"token":  token,
			"crop_w": cropW,
			"crop_x": cropX,
			"crop_y": cropY,
			"image":  image,
		},
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "UsersSetPhoto",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// UsersSetPresence sets the authenticated user's manual presence state. Provide `presence` as either `auto` or `away` to control how the user's availability is displayed.
//
// Manually sets user presence.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `users:write`
//	presence: Either `auto` or `away`
func UsersSetPresence(ctx context.Context, clientConfig ClientConfig, token string, presence string) (*UsersSetPresenceResponse, error) {
	resp, err := DoCfg[UsersSetPresenceResponse](ctx, &clientConfig, "POST", "/users.setPresence", &RequestOpts{
		Body: map[string]any{
			"presence": presence,
		},
		Headers: OperationHeaders(map[string]any{
					"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "UsersSetPresence",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}
