// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"context"
	"encoding/json"
)

// UsergroupsUsersListResponse Schema for successful response from usergroups.users.list method
type UsergroupsUsersListResponse struct {
	Ok    DefsOkTrue `json:"ok"`
	Users []string   `json:"users"`
}

func (value *UsergroupsUsersListResponse) UnmarshalJSON(data []byte) error {
	type UsergroupsUsersListResponseAlias UsergroupsUsersListResponse
	var decoded UsergroupsUsersListResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = UsergroupsUsersListResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok", "users"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewUsergroupsUsersListResponse returns a validated UsergroupsUsersListResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewUsergroupsUsersListResponse(fields UsergroupsUsersListResponse) (*UsergroupsUsersListResponse, error) {
	return ConstructModel(fields)
}

// UsergroupsUsersUpdateResponse Schema for successful response from usergroups.users.update method
type UsergroupsUsersUpdateResponse struct {
	Ok        DefsOkTrue  `json:"ok"`
	Usergroup ObjsSubteam `json:"usergroup"`
}

func (value *UsergroupsUsersUpdateResponse) UnmarshalJSON(data []byte) error {
	type UsergroupsUsersUpdateResponseAlias UsergroupsUsersUpdateResponse
	var decoded UsergroupsUsersUpdateResponseAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = UsergroupsUsersUpdateResponse(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ok", "usergroup"}); err != nil {
		return err
	}
	if err := ValidateEnum("ok", value.Ok, []DefsOkTrue{true}); err != nil {
		return err
	}
	return nil
}

// NewUsergroupsUsersUpdateResponse returns a validated UsergroupsUsersUpdateResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewUsergroupsUsersUpdateResponse(fields UsergroupsUsersUpdateResponse) (*UsergroupsUsersUpdateResponse, error) {
	return ConstructModel(fields)
}

// UsergroupsUsersList lists the users who belong to a specified User Group. Supply `usergroup` to select the group and use `include_disabled` when results may involve disabled User Groups.
//
// List all users in a User Group
//
// Parameters:
//
//	token: Authentication token. Requires scope: `usergroups:read`
//	usergroup: The encoded ID of the User Group to update.
//	includeDisabled: Allow results that involve disabled User Groups.
func UsergroupsUsersList(ctx context.Context, clientConfig ClientConfig, token string, usergroup string, includeDisabled *bool) (*UsergroupsUsersListResponse, error) {
	resp, err := DoCfg[UsergroupsUsersListResponse](ctx, &clientConfig, "GET", "/usergroups.users.list", &RequestOpts{
		Query: map[string]any{
			"token":            QueryValue{Value: token, Style: "form", Explode: true},
			"usergroup":        QueryValue{Value: usergroup, Style: "form", Explode: true},
			"include_disabled": QueryValue{Value: includeDisabled, Style: "form", Explode: true},
		},
		OperationID: "UsergroupsUsersList",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// UsergroupsUsersUpdate replaces the complete membership list for a User Group. Supply `usergroup` and the comma-separated `users` value; the submitted list becomes the group's entire user membership.
//
// Update the list of users for a User Group
//
// Parameters:
//
//	token: Authentication token. Requires scope: `usergroups:write`
//	usergroup: The encoded ID of the User Group to update.
//	users: A comma separated string of encoded user IDs that represent the
//	entire list of users for the User Group.
//	includeCount: Include the number of users in the User Group.
func UsergroupsUsersUpdate(ctx context.Context, clientConfig ClientConfig, token string, usergroup string, users string, includeCount *bool) (*UsergroupsUsersUpdateResponse, error) {
	resp, err := DoCfg[UsergroupsUsersUpdateResponse](ctx, &clientConfig, "POST", "/usergroups.users.update", &RequestOpts{
		Body: map[string]any{
			"usergroup":     usergroup,
			"users":         users,
			"include_count": includeCount,
		},
		Headers: OperationHeaders(map[string]any{
					"token": token,
		}),
		ContentType: "application/x-www-form-urlencoded",
		OperationID: "UsergroupsUsersUpdate",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}
