// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

// ViewsOpen opens a view for a user by exchanging a trigger for the supplied view payload. Pass `view` as a JSON-encoded view string together with the `trigger_id` that authorizes the interaction.
//
// Open a view for a user.
//
// Parameters:
//
//	triggerId: Exchange a trigger to post to the user.
//	view: A view payload. This must be a JSON-encoded string.
//	token: Authentication token. Requires scope: `none`
func ViewsOpen(ctx context.Context, clientConfig ClientConfig, triggerId string, view string, token string) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "GET", "/views.open", &RequestOpts{
		Query: map[string]any{
			"trigger_id": QueryValue{Value: triggerId, Style: "form", Explode: true},
			"view":       QueryValue{Value: view, Style: "form", Explode: true},
		},
		Headers: OperationHeaders(map[string]any{
					"token": token,
		}),
		OperationID: "ViewsOpen",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}

// ViewsPublish publishes a static view for a specified user. Provide the target `user_id` and a JSON-encoded `view`, and optionally pass `hash` to protect against concurrent view changes.
//
// Publish a static view for a User.
//
// Parameters:
//
//	userId: `id` of the user you want publish a view to.
//	view: A view payload. This must be a JSON-encoded string.
//	token: Authentication token. Requires scope: `none`
//	hash: A string that represents view state to protect against possible race
//	conditions.
func ViewsPublish(ctx context.Context, clientConfig ClientConfig, userId string, view string, token string, hash *string) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "GET", "/views.publish", &RequestOpts{
		Query: map[string]any{
			"user_id": QueryValue{Value: userId, Style: "form", Explode: true},
			"view":    QueryValue{Value: view, Style: "form", Explode: true},
			"hash":    QueryValue{Value: hash, Style: "form", Explode: true},
		},
		Headers: OperationHeaders(map[string]any{
					"token": token,
		}),
		OperationID: "ViewsPublish",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}

// ViewsPush pushes a view onto the stack of a root view for a user. Exchange `trigger_id` and provide the new view as a JSON-encoded payload to add it to the view stack.
//
// Push a view onto the stack of a root view.
//
// Parameters:
//
//	triggerId: Exchange a trigger to post to the user.
//	view: A view payload. This must be a JSON-encoded string.
//	token: Authentication token. Requires scope: `none`
func ViewsPush(ctx context.Context, clientConfig ClientConfig, triggerId string, view string, token string) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "GET", "/views.push", &RequestOpts{
		Query: map[string]any{
			"trigger_id": QueryValue{Value: triggerId, Style: "form", Explode: true},
			"view":       QueryValue{Value: view, Style: "form", Explode: true},
		},
		Headers: OperationHeaders(map[string]any{
					"token": token,
		}),
		OperationID: "ViewsPush",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}

// ViewsUpdate updates an existing view identified by its view identifier or developer-defined external identifier. Supply either `view_id` or `external_id`, provide the updated `view` as a JSON-encoded string, and use `hash` to protect against concurrent changes.
//
// Update an existing view.
//
// Parameters:
//
//	token: Authentication token. Requires scope: `none`
//	viewId: A unique identifier of the view to be updated. Either `view_id` or
//	`external_id` is required.
//	externalId: A unique identifier of the view set by the developer. Must be
//	unique for all views on a team. Max length of 255 characters. Either
//	`view_id` or `external_id` is required.
//	view: A view object. This must be a JSON-encoded string.
//	hash: A string that represents view state to protect against possible race
//	conditions.
func ViewsUpdate(ctx context.Context, clientConfig ClientConfig, token string, viewId *string, externalId *string, view *string, hash *string) (map[string]interface{}, error) {
	resp, err := DoCfg[map[string]interface{}](ctx, &clientConfig, "GET", "/views.update", &RequestOpts{
		Query: map[string]any{
			"view_id":     QueryValue{Value: viewId, Style: "form", Explode: true},
			"external_id": QueryValue{Value: externalId, Style: "form", Explode: true},
			"view":        QueryValue{Value: view, Style: "form", Explode: true},
			"hash":        QueryValue{Value: hash, Style: "form", Explode: true},
		},
		Headers: OperationHeaders(map[string]any{
					"token": token,
		}),
		OperationID: "ViewsUpdate",
	})
	if err != nil {
		return nil, err
	}
	return resp.Data, nil
}
